### ISSUE TITLE
[Android] ClassNotFoundException when unmarshalling: com.mapswithme.maps.bookmarks.data.BookmarkCategory

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#143]
```
Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.mapswithme.maps.bookmarks.data.BookmarkCategory
       at android.os.Parcel.readParcelableCreator(Parcel.java:2925)
       at android.os.Parcel.readParcelable(Parcel.java:2851)
       at android.os.Parcel.readValue(Parcel.java:2754)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
       at android.os.BaseBundle.unparcel(BaseBundle.java:226)
       at android.os.BaseBundle.containsKey(BaseBundle.java:476)
       at android.content.Intent.hasExtra(Intent.java:6959)
       at android.app.Activity.finish(Activity.java:5583)
       at android.app.Activity.finish(Activity.java:5595)
       at android.app.Activity.finishAfterTransition(Activity.java:5650)
       at android.app.Activity.onBackPressed(Activity.java:3077)
       at androidx.activity.ComponentActivity.access$001(ComponentActivity.java:50)
       at androidx.activity.ComponentActivity$1.run(ComponentActivity.java:72)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:194)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:286)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onBackPressed(BaseMwmFragmentActivity.java:276)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onHomeOptionItemSelected(BaseMwmFragmentActivity.java:212)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onOptionsItemSelected(BaseMwmFragmentActivity.java:204)
       at android.app.Activity.onMenuItemSelected(Activity.java:3518)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
       at android.view.View.performClick(View.java:6312)
       at android.view.View$PerformClick.run(View.java:24811)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/b9d287dae949bc1ed0793ed2832c4fce?time=last-seven-days&sessionEventKey=601D06C701AC00010D81336242245604_1504146887391346951

**Comment by rtsisyk** [comment]
This problem happened during development.

**Comment by rtsisyk** [comment]
This issue doesn't happen anymore.
