### ISSUE TITLE
Support Android Watch (Including Huawei Watch 3)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1451]
Now the app crashes with this error (looks like there is no WebView, or it is disabled):

```
0-21 20:56:57.480  8652  8652 E AndroidRuntime: FATAL EXCEPTION: main
10-21 20:56:57.480  8652  8652 E AndroidRuntime: Process: app.organicmaps.debug, PID: 8652
10-21 20:56:57.480  8652  8652 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.organicmaps.debug/com.mapswithme.maps.MwmActivity}: android.view.InflateException: Binary XML file line #83 in app.organicmaps.debug:layout/activity_map: Binary XML file line #83 in app.organicmaps.debug:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
10-21 20:56:57.480  8652  8652 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #83 in app.organicmaps.debug:layout/activity_map: Binary XML file line #83 in app.organicmaps.debug:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
10-21 20:56:57.480  8652  8652 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #83 in app.organicmaps.debug:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
10-21 20:56:57.480  8652  8652 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:864)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
10-21 20:56:57.480  8652  8652 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at com.mapswithme.maps.MwmActivity.onSafeCreate(MwmActivity.java:426)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(BaseMwmFragmentActivity.java:87)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8214)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8202)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
10-21 20:56:57.485  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
10-21 20:56:57.489  8652  8652 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:242)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.getFactory(WebView.java:2591)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.ensureProviderCreated(WebView.java:2585)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.setOverScrollMode(WebView.java:2696)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.view.View.<init>(View.java:5212)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.view.View.<init>(View.java:5353)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.view.ViewGroup.<init>(ViewGroup.java:709)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:57)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.<init>(WebView.java:426)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.<init>(WebView.java:367)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.<init>(WebView.java:350)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        at android.webkit.WebView.<init>(WebView.java:337)
10-21 20:56:57.489  8652  8652 E AndroidRuntime:        ... 58 more
10-21 20:56:57.508  1236  5504 W ActivityTaskManager:   finishTopCrashedActivityLocked Force finishing activity app.organicmaps.debug/com.mapswithme.maps.MwmActivity
```

**Comment by mirko77** [comment]
Any updates on this?

**Comment by demirdegerli** [comment]
I am running the app perfectly fine on Samsung Galaxy Watch 4 Classic

**Comment by mirko77** [comment]
I do not have a device unfortunately
