### ISSUE TITLE
Fialing to start on WearOS 

### ISSUE THREAD

**Issue by A4E** [organicmaps/organicmaps#1635]
Current beta buld (2021.11.28-10-Google-beta) fails to start on WearOS 3 device (Samsung Galaxy Watch4, SM-R870). Here is the errors from the logcat:
```
2021-11-29 16:27:08.976 6705-6705/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.organicmaps.beta, PID: 6705
    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.organicmaps.beta/com.mapswithme.maps.MwmActivity}: android.view.InflateException: Binary XML file line #83 in app.organicmaps.beta:layout/activity_map: Binary XML file line #83 in app.organicmaps.beta:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3456)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:7690)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: android.view.InflateException: Binary XML file line #83 in app.organicmaps.beta:layout/activity_map: Binary XML file line #83 in app.organicmaps.beta:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
     Caused by: android.view.InflateException: Binary XML file line #83 in app.organicmaps.beta:layout/activity_map: Error inflating class com.mapswithme.maps.widget.placepage.PlacePageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.mapswithme.maps.MwmActivity.onSafeCreate(MwmActivity.java:426)
        at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(BaseMwmFragmentActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:8009)
        at android.app.Activity.performCreate(Activity.java:7993)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:7690)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
2021-11-29 16:27:08.978 6705-6705/? E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #21 in app.organicmaps.beta:layout/place_page: Binary XML file line #15 in app.organicmaps.beta:layout/place_page_bookmark_details: Error inflating class android.webkit.WebView
    Caused by: android.view.InflateException: Binary XML file line #15 in app.organicmaps.beta:layout/place_page_bookmark_details: Error inflating class android.webkit.WebView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createView(LayoutInflater.java:774)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.mapswithme.maps.widget.placepage.PlacePageView.init(PlacePageView.java:677)
        at com.mapswithme.maps.widget.placepage.PlacePageView.<init>(PlacePageView.java:296)
        at com.mapswithme.maps.widget.placepage.PlacePageView.<init>(PlacePageView.java:289)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.mapswithme.maps.MwmActivity.onSafeCreate(MwmActivity.java:426)
        at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(BaseMwmFragmentActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:8009)
        at android.app.Activity.performCreate(Activity.java:7993)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
```

**Comment by A4E** [comment]
It seems that current WebView isn't supported on wearables.
You can call [getCurrentWebViewPackage](https://developer.android.com/reference/androidx/webkit/WebViewCompat#getCurrentWebViewPackage(android.content.Context)) to determine if WebView is supported or not

**Comment by biodranik** [comment]
Yes, there is no webview. But it's used in the PlacePage code to display bookmark's notes (it can be formatted as HTML). A proper fix would be to dynamically check if WebView is present, and use some simple TextView wrapper instead (for example, https://developer.android.com/reference/android/text/Html )

See also #1451
