### ISSUE TITLE
[editor] Multiple uploads of Notes (often) and POIs (rare) into OSM after editing.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#2071]
Old issues here:
https://github.com/mapsme/omim/issues/4663
https://github.com/mapsme/omim/issues/4819

Reproduced with added POIs here: 
First changeset https://www.openstreetmap.org/changeset/117079677 and SpyHeat hardware shop is mentioned in next several changesets. The last is https://www.openstreetmap.org/changeset/117213466

**Comment by literannn** [comment]
one more issue
https://www.openstreetmap.org/note/3122429

(duplicating note is under that)

**Comment by biodranik** [comment]
@literannn can you please clarify about the duplicating note? I can't see it.

**Comment by biodranik** [comment]
@literannn interesting, the second one was uploaded after several days from the first one. Please let us know if you see it again (also you can type `?edits` in the search box to debug your edits, and ideally record logs if you can reproduce the issue).

**Comment by literannn** [comment]
i have no Organic Maps on my phone :-) I only work with notes hard, that's why I'm here

**Comment by literannn** [comment]
we've got the third!
https://www.openstreetmap.org/note/3131905

**Comment by biodranik** [comment]
OMG, that should be fixed asap.

**Comment by biodranik** [comment]
Looks like it's an iOS-only bug (the user also uses iPhone). TODO: add ios/android tag/label into uploaded notes for easier debugging.

**Comment by daganzdaanda** [comment]
Hi, I was just looking through some duplicated OSM notes and found some that were added by organic maps, also over quite a span of time: 
https://www.openstreetmap.org/note/3350004
https://www.openstreetmap.org/note/3350005
https://www.openstreetmap.org/note/3350430
https://www.openstreetmap.org/note/3350436
https://www.openstreetmap.org/note/3350635

There's a list of potential duplicated notes at https://community.openstreetmap.org/t/potential-note-duplicates-worldwide/9517
Maybe it helps to narrow down the bug...

**Comment by biodranik** [comment]
It looks like some exception happens (network one?) that prohibits OM to store the mark that notes were successfully uploaded. It would be great to find an easier way to reproduce it...

P.S. Debug build of Organic Maps works with the dev API version of OpenStreetMap: https://master.apis.dev.openstreetmap.org

**Comment by daganzdaanda** [comment]
It seems it is an really old issue already, see the link to the first issue from Nov 2016 on mapsme in the top post.

**Comment by biodranik** [comment]
Yes, it's quite old. Is it clear where it happens? Android, iOS or both?

**Comment by deevroman** [comment]
It's not just iOS that's the problem:
- https://www.openstreetmap.org/note/3838708
- https://www.openstreetmap.org/note/3838709
- https://www.openstreetmap.org/note/3838710
@RedAuburn These are your notes, and the notes are only two hours old.

I was also able to get in touch with another Android user who had his notes duplicated a year ago
https://www.openstreetmap.org/note/3233105
https://www.openstreetmap.org/note/3228728

**Comment by RedAuburn** [comment]
yeah :/ i was in an area with poor signal, maybe the upload is only partially completing & attempts to restart?

**Comment by biodranik** [comment]
@RedAuburn that's a good theory. Another possibility is that the system kills a partially done upload. Can someone try to set a "bad connection" environment and try to reproduce the issue?

**Comment by kmpoppe** [comment]
Good afternoon everyone.

> There's a list of potential duplicated notes at https://community.openstreetmap.org/t/potential-note-duplicates-worldwide/9517
> Maybe it helps to narrow down the bug...

This is now at https://community.openstreetmap.org/t/potential-note-duplicates-worldwide-september-2023-update/104390.

On the [wiki page](https://wiki.openstreetmap.org/wiki/User:Kmpoppe/Potential_Note_Duplicates) I have now, apart from marking duplicates from StreetComplete with "SC", added a marking of MapsMe ("MM") and OrganicMaps ("OM") that get superscripted after the note number. 

Of the 22.6k notes that are potential duplicates, MapsMe created 17.2k, OrganicMaps 1.4k.

The thing I've seen lately, which makes me a bit nervous is, that OM copied MM's behaviour in that Notes get created _even though_ a changeset with the changes described is uploaded at the same time.

A very good MM example are these:

* Object: [n/11091348405](https://www.osm.org/node/11091348405)
  * Notes: [3843923](https://osm.org/note/3843923) [3843933](https://osm.org/note/3843933) [3843937](https://osm.org/note/3843937) [3843943](https://osm.org/note/3843943)
* Object: [n/11091326105](https://www.osm.org/node/11091326105)
  * Notes: [3843879](https://osm.org/note/3843879) [3843882](https://osm.org/note/3843882) [3843889](https://osm.org/note/3843889) [3843930](https://osm.org/note/3843930)

For OM a smaller example is this:
* Object: [n/9551518755](https://www.osm.org/node/9551518755)
  * Notes: [3770261](https://osm.org/note/3770261) [3770262](https://osm.org/note/3770261)

Is that intentional? To me, it feels superflous to create a note for a change that gets uploaded directly?!

Kai

**Comment by deevroman** [comment]
Another observation: some of the duplicate notes are sent anonymously.

[3852069](https://www.openstreetmap.org/note/3852069)
[3871298](https://www.openstreetmap.org/note/3871298) <- anonymous
[3880416](https://www.openstreetmap.org/note/3880416)
[3894711](https://www.openstreetmap.org/note/3894711)

[3541476](https://www.openstreetmap.org/note/3541476) <- anonymous
[3541479](https://www.openstreetmap.org/note/3541479)

This is probably just a coincidence of bugs in the note submission module, but maybe these problems have something in common. I've created a separate issue https://github.com/organicmaps/organicmaps/issues/6360

**Comment by biodranik** [comment]
The OSM feature was updated. But the connection was interrupted by the system killing OM in the background, so OM didn't mark that feature as uploaded:
```
01-19 09:20:44.452 (main) D/OMcore: editor/osm_editor.cpp:921 GetStats(): Edited features status:
01-19 09:20:44.472 (main) D/OMcore: editor/osm_editor.cpp:935 GetStats(): 2024-01-04T12:43:02Z Uploaded  Area m2::Point<d>(XXXXXX)
01-19 09:20:44.475 (main) D/OMcore: editor/osm_editor.cpp:935 GetStats(): 2024-01-17T01:14:41Z Needs Retry DirectRequest Network error while connecting to https://api.openstreetmap.org/api/0.6/map?bbox=XXXXXXXXXX Point m2::Point<d>(XXXXXXXX)
```


```
01-19 09:20:57.194 (main) D/MwmApplication: MwmApplication.java:356 onBackground(): 
01-19 09:20:57.243 (main) I/app.organicmaps.location: MwmApplication.java:370 onBackground(): Stopping location in the background
01-19 09:20:57.246 (main) D/app.organicmaps.location: LocationHelper.java:355 stop(): Already stopped
01-19 09:20:57.383 (Thread-4) D/HttpClient: HttpClient.java:68 run(): Connecting to https://api.openstreetmap.org/api/0.6/map?bbox=<XXXXXXXXXXXXXXXXXXXX>
01-19 09:20:58.375 (main) D/MwmActivity: MwmActivity.java:2178 onTrimMemory(): trim memory, level = 80
01-19 09:20:58.376 (main) I/OMcore: map/framework.cpp:1156 MemoryWarning(): MemoryWarning
01-19 09:21:00.431 (Thread-4) W/OMcore: core/jni_helper.cpp:203 HandleJavaException(): java.net.ConnectException: Failed to connect to api.openstreetmap.org/184.104.179.140:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at app.organicmaps.util.HttpClient.run(HttpClient.java:145)

01-19 09:21:00.455 (Thread-4) W/OMcore: editor/osm_editor.cpp:745 operator()(): NetworkError /home/vagrant/build/app.organicmaps/editor/osm_auth.cpp:392, "DirectRequest Network error while connecting to https://api.openstreetmap.org/api/0.6/map?bbox=XXXXXXXXXXXXXXXX"
01-19 09:21:00.458 (main) D/OMcore: editor/xml_feature.cpp:598 ToXML(): Skipping type serialization: building
```

**Comment by eisams** [comment]
This just happened to me, I indicated that a lift_gate was non-existing and a triplicate note was created

It was also anonymous, even though I'm logged into OSM on Organic Maps
https://www.openstreetmap.org/note/4233193
https://www.openstreetmap.org/note/4233197
https://www.openstreetmap.org/note/4233214

**Comment by map-per** [comment]
A solution could be to first download existing notes in the area and check whether there already is a note with the same text.

**Comment by map-per** [comment]
I took a look at the multiple uploads POIs problem from https://github.com/organicmaps/organicmaps/issues/2071#issue-1129603995:

The edits are:
- https://www.openstreetmap.org/changeset/117079677
- https://www.openstreetmap.org/changeset/117119578
- https://www.openstreetmap.org/changeset/117139929
- https://www.openstreetmap.org/changeset/117179126
- https://www.openstreetmap.org/changeset/117213466

The edits are from different days and the pattern is always: 
- OM adds a POI
- the OSM user literan comes to clean up the data
   -> no POI in the original position
- OM re-adds the POI
- ...

So this looks like the uploads had some error (e.g. Network error) and OM considered the upload as failed. OM has logic to prevent multiple uploads in such cases, but that didn't work in this case because the uploaded POIs were moved / removed by literan.

To me this "incident" looks uncritical as POIs are usually not moved / deleted directly after an OM upload.

**Comment by vng** [comment]
I had the same issue 2 days ago with the new editor (https://github.com/organicmaps/organicmaps/pull/9242)

- Added hairdresser https://www.openstreetmap.org/changeset/159418301 and got "Request Network error", but the POIs were added successfully!
- Edited hairdresser placement manually with ID https://www.openstreetmap.org/changeset/159418646
- OM added hairdresser again to the old coordinates https://www.openstreetmap.org/changeset/159478553

**Comment by map-per** [comment]
I did not change the upload trigger code, so I don't think this is related to this PR

**Comment by matheusgomesms** [comment]
Bug still going on, iOS:

Original note (uploaded almost instantaneously): https://www.openstreetmap.org/note/4608103
23 hours later: https://www.openstreetmap.org/note/4609325
27 hours later: https://www.openstreetmap.org/note/4609503
27 hours later (1 min after previous note): https://www.openstreetmap.org/note/4609504
28 hours later: https://www.openstreetmap.org/note/4609575

No network problem, and I believe the app was closed/killed in most or maybe all the times these notes were uploaded.

**Comment by biodranik** [comment]
The proper fix should upload osm edits in a foreground service, so the system won't kill OM during that process.

**Comment by kmpoppe** [comment]
With 2025.05.20-5-FDroid OrganicMaps created 35(!) duplicates (First Note https://osm.org/note/4798428) and an currently unknown version created 14 duplicates (First Note https://osm.orgnote/4791250) - this is getting slightly out of hand :-/

**Comment by biodranik** [comment]
@kmpoppe is 2025.05.20 Android version the first one when such (mass uploads at the same moment) issues appear?

**Comment by kmpoppe** [comment]
@biodranik It was the first time I was told the version of the software by the user after I closed all the dupes.

As said before, the are a lot of occasions where OM created a duplicate (1,378 out of 82,949 notes are potential duplicates, see [here](https://dupnotes.webmapping.cyou/)) but this high frequency and long time span is new. 

Another instance is developing [at this place](https://osm.org/note/4801754), with currently 10 dupes.

K

**Comment by biodranik** [comment]
@kmpoppe thanks! What's the best way to retrieve all dupe notes at the given map point (including resolved ones)?

**Comment by kmpoppe** [comment]
@biodranik I could create a "live" (15 minute intervals) "Organic Maps"-only CSV of duplicates. Would that help?

**Comment by biodranik** [comment]
To debug the issue, I'm interested in high-precision details about duped notes':
- coordinates
- texts
- timestamps
, and how many of them were published. If it were possible to get users' Android version, that would also help a lot. An additional important piece of information: did users with dups add Organic Maps to the [exceptions list of battery saver/battery optimizer](https://www.reddit.com/r/galaxys10/comments/d8xgwo/is_there_a_way_to_exclude_certain_apps_from/)?

**Comment by kmpoppe** [comment]
Welp ;-)

I can provide coordinates and timestamps (snapshot date/time as well as open and close date/times). I could save the text of the notes but I'd need the patterns that get created as to reduced resource-usage.

Everything else (Android or iOS Version, settings) will not be retrievable, notes do not have structured fields like changesets that would allow the app to pass those infos on so that's currently unavailable.

Alas, that'll be a JSON then, CSV is not gonna cut it for the amount of info you'd want :D

**Comment by matheusgomesms** [comment]
Just to clarify, this bug happens too in iOS (where this battery-saver thing doesn't exist there).

**Comment by kmpoppe** [comment]
There is now [this JSON](https://dupnotes.webmapping.cyou/organic-maps/om-dupe-notes.json) with [this Schema](https://dupnotes.webmapping.cyou/organic-maps/om-dupe-notes.schema.json) that'll give you 
* an array of duplicates, ordered by country and lat/lon which in turn includes 
  * an array of notes described by 
    * id, created at, closed at and snaphot date time as well as the platform (Android, iOS, unknown) - as you have started adding #android and #ios later, there are notes that don't have this information.

The file gets statically recreated every 15 minutes at 10, 25, 40 and 55 past the hour, creation takes about 5-7 minutes because calculating the duplication points takes some sweet time.

This is about the amount of data that's in the database without any further additions. As said, if you want a text analysis for all those notes, I'd need regex patterns of what could be sent by the app and which part you'd like to add to the analysis.

HTH.

K

**Comment by pbiering** [comment]
OS here: Android 13 (iodeOS 4.23 2025-04-25), also happen imho with an older OM version already as there was an update recently.

**Comment by biodranik** [comment]
Thanks a lot! Where is the source code and branch for the currently running OpenStreetMap.org notes API in production? Does it make sense to filter duplicate notes there and return HTTP 200 for clients in such cases? My current assumption is that clients do not receive HTTP 200 for whatever reason from the OpenStreetMap.org server.

**Comment by kmpoppe** [comment]
The implementation app is at https://github.com/openstreetmap/openstreetmap-website/tree/master/app/views/notes.
Filtering out duplicates doesn't make sense (just my 2 cents!) because there might always be legit reasons to create a second note instead of commenting on an existing one (i.e. when offensive text was created).
As the API can also return all notes for any given lat/lon it would be a lot easier when apps would check if a note with the exact same content they want to create already exists - yet I understand that that's not as easy to implement as 1,2,3!

**Comment by biodranik** [comment]
> Filtering out duplicates doesn't make sense (just my 2 cents!) because there might always be legit reasons to create a second note instead of commenting on an existing one (i.e. when offensive text was created).

Can you please clarify your point? Why doesn't it make sense to filter _duplicate create note requests with equal coordinates and text_? The server already knows that there is a note at that coordinate. With exactly the same text. Why can't it just avoid duplication? If the text is different, then it is not a duplication.

**Comment by kmpoppe** [comment]
This is _my_ opinion, I do not speak for the openstreetmap-website team. OSM has never restricted what users can do with the API (creating multiple objects on top of one another), so it's fair to not handle Notes differently.

As there are discussions about "Upgrading" Notes to also have meta data fields, just like objects, you might want to chime in on https://github.com/openstreetmap/openstreetmap-website/issues/5294 with the idea of preventing duplicate creation when lat/lon and text are identical.

**Comment by biodranik** [comment]
iOS notes are duplicated with 22 seconds delay:
https://www.openstreetmap.org/api/0.6/notes/4806460
https://www.openstreetmap.org/api/0.6/notes/4806461

And 33 seconds delay:
https://www.openstreetmap.org/api/0.6/notes/4806452
https://www.openstreetmap.org/api/0.6/notes/4806453

**Comment by biodranik** [comment]
If anyone could reproduce it, please check if the latest beta fixed it: https://cdn.organicmaps.app/apk/OrganicMaps-25070546-google-beta.apk

**Comment by biodranik** [comment]
Are there any issues with the latest publicly released July OM version?

**Comment by kmpoppe** [comment]
Hey @biodranik, so this is the amount of notes that are in the duplicates list for OM:

Count | OSM Snapshot Date | Days since snapshot | Notes per day
-- | -- | -- | -- 
2 | 2025-07-14 02:04:03 | 7 | 0.2857
98 | 2025-07-08 15:45:36 | 13 | 7.5385
5 | 2025-07-01 00:23:12 | 20 | 0.2500
385 | 2025-06-08 00:18:23 | 43 | 8.9535
24 | 2025-05-31 01:21:10 | 51 | 0.4706
1 | 2025-05-24 00:43:09 | 58 | 0.0172
627 | 2025-05-11 16:17:16 | 71 | 8.8310
552 | 2025-04-18 15:38:17 | 94 | 5.8723
17 | 2025-03-29 11:08:01 | 114 | 0.1491
990 | 2025-02-27 10:33:49 | 144 | 6.8750
4 | 2025-02-18 17:15:35 | 153 | 0.0261
278 | 2025-02-13 05:46:10 | 158 | 1.7595
488 | 2025-01-21 15:15:53 | 181 | 2.6961
1 | 2025-01-08 00:30:44 | 194 | 0.0052

As there isn't a version number in the note text but only the snapshot date, I calculated the notes per day the snapshot is out, with Early-July being responsible for less dupes than Early-June and Early-May.

So I guess we'll have to see how this evolves when more people update to the July public version. Updating is currently not enforced through the app or the app store, right?

K

**Comment by biodranik** [comment]
Thanks for the stats! Updating is not enforced, right. And the fix scope was only Android. So let's observe what's going on.

**Comment by kmpoppe** [comment]
Early June Snapshot has 103 duplicates, 1.9 per Day, Early July has 31, 1.3 per Day - Android only. Yet, without any version info, it's still hard to judge.

**Comment by biodranik** [comment]
@hemanggs would you mind to replace the current uploader implementation with a foreground service? That should fix the issue.

- Start it when user hides OM (is it possible?)
- Show notification with the amount of remaining uploads
- Hide it when upload finished
- Show errors if any

**Comment by hemanggs** [comment]
> @hemanggs would you mind to replace the current uploader implementation with a foreground service? That should fix the issue.
> 
> - Start it when user hides OM (is it possible?)
> - Show notification with the amount of remaining uploads
> - Hide it when upload finished
> - Show errors if any

Sure i'd love to work on this post completing the complex types PR

**Comment by biodranik** [comment]
@kirylkaveryn Notes uploading API is very simple and doesn't have complex changeset open/close logic. Maybe you can spot something suspicious in the current implementation. Here is one of the recent iOS note duplication examples: https://www.openstreetmap.org/user/Heisl_2049/notes

**Comment by pwbriggs** [comment]
Looks like this is still happening: https://www.openstreetmap.org/user/Aoot/notes. Can we get a fix on this? [NeisBot]'s #DuplicateNote task seems to be auto-closing these for now, but mappers are still getting false notifications when all these duplicate notes open.

[NeisBot]: https://www.openstreetmap.org/user/NeisBot

**Comment by kmpoppe** [comment]
Update as of September 2025:

| Count | OSM Snapshot Date | Days since snapshot | Notes per day |
|---|---|---|---|
| 23 | 2025-08-08 13:08:07 | 41 | 0.5610 |
| 43 | 2025-08-04 17:20:14 | 45 | 0.9556 |
| 1 | 2025-07-14 02:04:03 | 66 | 0.0152 |
| 140 | 2025-07-08 15:45:36 | 72 | 1.9444 |
| 2 | 2025-07-01 00:23:12 | 79 | 0.0253 |
| 484 | 2025-06-08 00:18:23 | 102 | 4.7451 |
| 1 | 2025-05-24 00:43:09 | 117 | 0.0085 |
| 536 | 2025-05-11 16:17:16 | 130 | 4.1231 |
| 291 | 2025-04-18 15:38:17 | 153 | 1.9020 |
| 21 | 2025-03-29 11:08:01 | 173 | 0.1214 |
| 463 | 2025-02-27 10:33:49 | 203 | 2.2808 |
| 4 | 2025-02-18 17:15:35 | 212 | 0.0189 |
| 91 | 2025-02-13 05:46:10 | 217 | 0.4194 |
| 213 | 2025-01-21 15:15:53 | 240 | 0.8875 |

These are Android created notes only, with the latest snapshot being over a month old it seems the amount of notes has been reduced.

**Comment by biodranik** [comment]
@kmpoppe what are the dupe stats by OM versions for Android?

@kirylkaveryn What's left to fix it on iOS?

**Comment by kmpoppe** [comment]
> [@kmpoppe](https://github.com/kmpoppe) what are the dupe stats by OM versions for Android?

I'm not sure what you mean? The stats above are Android only (#android in the open comment) grouped by snapshot date. As far as I've seen there's still no version information in the open comments from OM, is there?

**Comment by biodranik** [comment]
Ah sorry, you're right, version is added only for additions/map edits, not for notes. Let's track it too to observe improvements and regressions: https://github.com/organicmaps/organicmaps/pull/11375

**Comment by vng** [comment]
Should be fixed in the 2025.10.05 version.
