### ISSUE TITLE
[Android]: A crash in com.mapswithme.maps.widget.menu.GuestsRoomsMenuRender

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#256]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapswithme.maps.widget.InteractiveCounterView.getCurrentValue()' on a null object reference
       at com.mapswithme.maps.widget.menu.GuestsRoomsMenuRenderer.onHide(GuestsRoomsMenuRenderer.java:53)
       at com.mapswithme.maps.widget.menu.BottomSheetMenuController$1.onStateChanged(BottomSheetMenuController.java:41)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1114)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1545)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
 ```
 
 https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps/issues/e1ba2e8946b662840fc2b727b43bba46?time=last-seven-days&sessionEventKey=60521EF5016A000135613133605DC710_1519093347945924587
https://play.google.com/console/u/0/developers/8084273541548442467/app/4974916572853654059/vitals/crashes/83835940/details?installedFrom=PLAY_STORE&days=30

**Comment by rtsisyk** [comment]
Fixed by 9ecde05d09976d22e29d5da2acc461e973c33289
