### ISSUE TITLE
[generator] Generator is failing

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#3019]
I'm trying to build maps using the generator but I keep running into this error:

```
davidmartinez@Mac-mini-de-David python % python3 -m maps_generator --countries="Spain_Comunidad Foral de Navarra" --skip="Coastline"
[2022-07-24 16:50:39,296] INFO env Start setup ...
[2022-07-24 16:50:39,296] INFO env Check osm tools ...
[2022-07-24 16:50:39,296] INFO env Osm tools found - /Users/davidmartinez/osmctools/osmconvert, /Users/davidmartinez/osmctools/osmupdate, /Users/davidmartinez/osmctools/osmfilter
[2022-07-24 16:50:39,297] INFO env Check generator tool ...
[2022-07-24 16:50:39,297] INFO env Looking for generator tool in /Users/davidmartinez/git/omim-build-release ...
[2022-07-24 16:50:39,297] INFO env Generator tool found - /Users/davidmartinez/git/omim-build-release/generator_tool
[2022-07-24 16:50:39,297] INFO env Build name is 2022_07_24__16_50_39.
[2022-07-24 16:50:39,297] INFO env Build path is /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39.
[2022-07-24 16:50:39,297] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39 ...
[2022-07-24 16:50:39,297] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data ...
[2022-07-24 16:50:39,297] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data/borders ...
[2022-07-24 16:50:39,298] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/draft ...
[2022-07-24 16:50:39,298] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/osm2ft ...
[2022-07-24 16:50:39,298] INFO env The following 1 maps will build: Spain_Comunidad Foral de Navarra.
[2022-07-24 16:50:39,298] INFO env Finish setup
[2022-07-24 16:50:39,298] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/logs ...
[2022-07-24 16:50:39,298] INFO stages Stage DownloadAndConvertPlanet: start ...
[2022-07-24 16:50:39,298] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/status ...
[2022-07-24 16:50:39,313] INFO file Trying to download /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.osm.pbf from http://download.geofabrik.de/europe/spain/navarra-latest.osm.pbf.
[2022-07-24 16:50:39,313] INFO file Trying to download /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.osm.pbf.md5 from http://download.geofabrik.de/europe/spain/navarra-latest.osm.pbf.md5.
[2022-07-24 16:50:39,605] INFO file File /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.osm.pbf.md5 was downloaded from http://download.geofabrik.de/europe/spain/navarra-latest.osm.pbf.md5.
[2022-07-24 16:51:58,349] INFO file File /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.osm.pbf was downloaded from http://download.geofabrik.de/europe/spain/navarra-latest.osm.pbf.
[2022-07-24 16:51:58,913] INFO stages Stage DownloadAndConvertPlanet: finished in 0:01:19.614567
[2022-07-24 16:51:58,913] INFO stages Stage Preprocess: start ...
[2022-07-24 16:51:59,002] INFO gen_tool Run generator tool [generator_tool version 2022.07.23-7 (f7c8f9bb)]: /Users/davidmartinez/git/omim-build-release/generator_tool --threads_count=1 --intermediate_data_path=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data --cache_path=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.o5m --node_storage=map --user_resource_path=/Users/davidmartinez/git/organicmaps/data --preprocess=true 
[2022-07-24 16:52:00,157] INFO stages Stage Preprocess: finished in 0:00:01.243961
[2022-07-24 16:52:00,157] INFO stages Stage Features: start ...
[2022-07-24 16:52:00,158] INFO stages Test test_booking_data was skipped.
[2022-07-24 16:52:00,180] INFO gen_tool Run generator tool [generator_tool version 2022.07.23-7 (f7c8f9bb)]: /Users/davidmartinez/git/omim-build-release/generator_tool --threads_count=8 --data_path=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data --intermediate_data_path=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data --cache_path=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/planet.o5m --node_storage=map --user_resource_path=/Users/davidmartinez/git/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --generate_packed_borders=true 
[2022-07-24 16:52:09,091] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/220724 ...
[2022-07-24 16:52:09,091] INFO stages Stage Features: finished in 0:00:08.933225
[2022-07-24 16:52:09,091] INFO stages Stage Mwm: start ...
[2022-07-24 17:03:19,380] INFO env Create /Users/davidmartinez/git/maps_build/2022_07_24__16_50_39/stats ...
[2022-07-24 17:03:19,384] INFO stages Stage Mwm: finished in 0:11:10.292585
[2022-07-24 17:03:19,384] ERROR env Uncaught exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/__main__.py", line 303, in <module>
    main()
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/__main__.py", line 299, in main
    generate_maps(env, from_stage)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/maps_generator.py", line 43, in generate_maps
    run_generation(env, stages, from_stage)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 173, in apply
    pool.map(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 174, in <lambda>
    lambda c: StageMwm.make_mwm(c, env),
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 206, in make_mwm
    stage(country=country)(env)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages.py", line 268, in apply
    method(obj, env, country, *args, logger=_logger, **kwargs)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages.py", line 243, in apply
    method(obj, env, country, *args, **kwargs)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 319, in apply
    steps.step_statistics(env, country, **kwargs)
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/steps.py", line 427, in step_statistics
    make_stats(
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/statistics.py", line 101, in make_stats
    stats = process_stat(config, read_stat(f))
  File "/Users/davidmartinez/git/organicmaps/tools/python/maps_generator/generator/statistics.py", line 42, in read_stat
    "name": m.group(1).replace("|", "-"),
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by dvdmrtnz** [comment]
@vng Thanks!
