### ISSUE TITLE
Pressing a POI with `building:min_level=*` crashes the app

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3079]
The affected buildings appear flat on the map, and pressing on them instantly crashes the app.
debug log:
```
msg: java.lang.IllegalArgumentException: Illegal metaType arg!
stacktrace: java.lang.IllegalArgumentException: Illegal metaType arg!
	at com.mapswithme.maps.bookmarks.data.Metadata$MetadataType.fromInt(Unknown Source:22)
	at com.mapswithme.maps.bookmarks.data.Metadata.addMetadata(Unknown Source:0)
	at com.mapswithme.maps.bookmarks.data.MapObject.addMetadata(Unknown Source:2)
	at com.mapswithme.maps.Framework.nativePlacePageActivationListener(Native Method)
	at com.mapswithme.maps.MwmActivity.onStart(Unknown Source:3)
```
It still crashes when `building:levels=*` is tagged.

Test examples: 
https://www.openstreetmap.org/way/626655654
anything that matches this query: https://overpass-turbo.eu/s/1kGi

It doesn't crash the app on iOS, but that might just be down to different error handling.

**Comment by rtsisyk** [comment]
Please feel free to re-open if problem still exists.
