### ISSUE TITLE
[android] Crash when you change screen orientation

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3369]
- Open app
- Open menu burger
- Switch screen orientation
- App crashed
```
09-07 17:49:21.363  7047  7047 E AndroidRuntime: FATAL EXCEPTION: main
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Process: app.organicmaps, PID: 7047
09-07 17:49:21.363  7047  7047 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.organicmaps/com.mapswithme.maps.MwmActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.mapswithme.util.bottomsheet.MenuBottomSheetFragment: could not find Fragment constructor
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5791)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5682)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.mapswithme.util.bottomsheet.MenuBottomSheetFragment: could not find Fragment constructor
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.Fragment.instantiate(Unknown Source:94)09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentContainer.instantiate(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$2.instantiate(Unknown Source:17)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentState.instantiate(Unknown Source:2)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.<init>(Unknown Source:13)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(Unknown Source:119)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.attachController(Unknown Source:140)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentController.attachHost(Unknown Source:4)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.lambda$init$1(Unknown Source:3)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.a(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.b.onContextAvailable(Unknown Source:2)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(Unknown Source:20)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.activity.ComponentActivity.onCreate(Unknown Source:7)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onCreate(Unknown Source:0)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(Unknown Source:33)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8290)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8269)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        ... 15 more
09-07 17:49:21.363  7047  7047 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: com.mapswithme.util.bottomsheet.MenuBottomSheetFragment.<init> []
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.Class.getConstructor0(Class.java:2363)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at java.lang.Class.getConstructor(Class.java:1759)
09-07 17:49:21.363  7047  7047 E AndroidRuntime:        at androidx.fragment.app.Fragment.instantiate(Unknown Source:15)09-07 17:49:21.363  7047  7047 E AndroidRuntime:        ... 33 more
```
Pixel 6 - Android 13
version 2022.08.23-5-Google

Problem is fixed on [debug version](https://github.com/organicmaps/organicmaps/actions/runs/3008434506)

But in debug version menu burger is hide when you change screen orientation and you can't expand menu.

**Before (debug version)**
<img src="https://user-images.githubusercontent.com/87148630/188924065-3961eeb7-2838-4f80-8bfb-faf49e03ea46.png" height="500"/>

**After (debug version)**
<img src="https://user-images.githubusercontent.com/87148630/188924326-52bb072f-981f-409a-85a9-cce8b9cdd8d3.png" width="500"/>

cc @arnaudvergnet

**Comment by arnaudvergnet** [comment]
Same issue happens when any other menu is opened during orientation change

**Comment by rtsisyk** [comment]
@arnaudvergnet , It looke like that @Jean-BaptisteC has the same issue with overlapping gesture bar.

**Comment by arnaudvergnet** [comment]
https://github.com/organicmaps/organicmaps/pull/3377 should fix it yes

**Comment by Jean-BaptisteC** [comment]
Do you want i test fix on my phone ?

**Comment by arnaudvergnet** [comment]
@Jean-BaptisteC if it is not too much bother for you it would help thanks!
