### ISSUE TITLE
[android] Crash in Google Play Services "Location is disabled" dialog

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3585]
```
10-11 20:20:55.451 17897 17897 E AndroidRuntime: FATAL EXCEPTION: main
10-11 20:20:55.451 17897 17897 E AndroidRuntime: Process: app.organicmaps.debug, PID: 17897
10-11 20:20:55.451 17897 17897 E AndroidRuntime: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:325)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationDisabled(LocationHelper.java:343)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:296)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider.lambda$start$1$com-mapswithme-maps-location-GoogleFusedLocationProvider(GoogleFusedLocationProvider.java:98)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider$$ExternalSyntheticLambda1.onFailure(Unknown Source:2)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

_Originally posted by @Jean-BaptisteC in https://github.com/organicmaps/organicmaps/issues/3537#issuecomment-1275106065_

**Comment by Jean-BaptisteC** [comment]
App crashes when i allow location permission (see screenshots) and if location is disabled.
<img src="https://user-images.githubusercontent.com/87148630/195253563-0705b33a-5b62-4b3e-b819-7db4b9ae629f.png" height="600"/>

Android 13 - Pixel 6
