### ISSUE TITLE
[android] Crash on Editor login to OSM

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3597]
> The app restarts when I click the login button after entering my credentials. Credentials are correct for sure since I see that OAuth1 tokens were issued in my OpenStreetMap account. 

```
10-12 11:07:27.871 E/AndroidRuntime( 4756): FATAL EXCEPTION: main
10-12 11:07:27.871 E/AndroidRuntime( 4756): Process: app.organicmaps, PID: 4756
10-12 11:07:27.871 E/AndroidRuntime( 4756): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.mapswithme.maps.editor.OsmLoginFragment.onAuthSuccess(Unknown Source:27)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.mapswithme.maps.editor.OsmLoginFragment.processAuth(Unknown Source:30)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.mapswithme.maps.editor.OsmLoginFragment.lambda$login$3(Unknown Source:0)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.mapswithme.maps.editor.OsmLoginFragment.a(Unknown Source:0)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.mapswithme.maps.editor.l.run(Unknown Source:6)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at android.os.Handler.handleCallback(Handler.java:873)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at android.os.Looper.loop(Looper.java:193)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
10-12 11:07:27.871 E/AndroidRuntime( 4756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-12 11:07:27.896 I/Process ( 4756): Sending signal. PID: 4756 SIG: 9
```

**Comment by biodranik** [comment]
@arnaudvergnet This one is a critical one.

**Comment by arnaudvergnet** [comment]
I'll see what I can do about this issue tomorrow but I don't have much time to work on OM.

**Comment by arnaudvergnet** [comment]
https://master.apis.dev.openstreetmap.org/ seems to be down so I cannot test on debug.

**Comment by biodranik** [comment]
Fix locally editor/osm_auth.cpp by using release server instead of the debug one for debug builds:

```
OsmOAuth OsmOAuth::ServerAuth()
{
#ifdef DEBUG
  return DevServerAuth();
#else
  return ProductionServerAuth();
#endif
}
```

```
OsmOAuth OsmOAuth::ServerAuth()
{
#ifdef DEBUG
  return ProductionServerAuth();
#else
  return ProductionServerAuth();
#endif
}
```
