### ISSUE TITLE
Downloading fails

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3748]
seems the CDN can't serve files: https://cdn.organicmaps.app/maps/221019/WorldCoasts.mwm

android log:
```
java.net.SocketException: Connection reset
 at java.net.SocketInputStream.read(SocketInputStream.java:157)
 at java.net.SocketInputStream.read(SocketInputStream.java:144)
 at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
 at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
 at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
 at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
 at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
 at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
 at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
 at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
 at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
 at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
 at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
 at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
 at java.io.FilterInputStream.read(FilterInputStream.java:107)
 at app.organicmaps.downloader.ChunkTask.downloadFromStreamImpl(Unknown Source:2)
 at app.organicmaps.downloader.ChunkTask.downloadFromStream(Unknown Source:14)
 at app.organicmaps.downloader.ChunkTask.doInBackground(Unknown Source:394)
 at app.organicmaps.downloader.ChunkTask.doInBackground(Unknown Source:2)
 at android.os.AsyncTask$3.call(AsyncTask.java:394)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:920)
I  platform/chunks_download_strategy.cpp:157 ChunkFinished(): Thread for url https://cdn.organicmaps.app/maps/221019/WorldCoasts.mwm failed to download chunk number 0
W  platform/http_request.cpp:240 OnFinish(): /storage/emulated/0/Android/data/app.organicmaps.beta/files/221019/WorldCoasts.mwm HttpRequest error: IO exception
```

**Comment by biodranik** [comment]
It was a temporary issue, should work now.
