### ISSUE TITLE
[android] ClassNotFoundException app.organicmaps.editor.data.FeatureCategory

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3757]
- 2022.10.25-4-Google-beta (22102504)
- Android 12
- POCO X3 NFC

```
Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: app.organicmaps.editor.data.FeatureCategory
       at android.os.Parcel.readParcelableCreator(Parcel.java:3416)
       at android.os.Parcel.readParcelable(Parcel.java:3324)
       at android.os.Parcel.readValue(Parcel.java:3226)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:935)
       at app.organicmaps.editor.EditorHostFragment.onViewCreated(EditorHostFragment.java:61)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:4)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:272)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:124)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:30)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:27)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:9)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:11)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:20)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at app.organicmaps.base.BaseMwmFragmentActivity.onStart(BaseMwmFragmentActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
       at android.app.Activity.performStart(Activity.java:8195)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3796)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8319)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

CC: @AndrewShkrob

**Comment by biodranik** [comment]
There are many references in the code to `FeatureCategory` class.

Here we put two putExtra values into the intent:
```
  @Override
  public void onFeatureCategorySelected(FeatureCategory category)
  {
    Editor.createMapObject(category);
    final Intent intent = new Intent(this, EditorActivity.class);
    intent.putExtra(EXTRA_FEATURE_CATEGORY, category);
    intent.putExtra(EditorActivity.EXTRA_NEW_OBJECT, true);
    startActivity(intent);
  }
}
```

They are extracted like this in `EditorHostFragment.java`: 
```
    if (getArguments() != null)
      mIsNewObject = getArguments().getBoolean(EditorActivity.EXTRA_NEW_OBJECT, false);
```

I have several ideas:
```
This class was deprecated in API level 28.
Use the [Jetpack Fragment Library](https://developer.android.com/jetpack) [Fragment](https://developer.android.com/reference/androidx/fragment/app/Fragment.html) for consistent behavior across all devices and access to [Lifecycle](https://developer.android.com/topic/libraries/architecture/lifecycle).
``

Another possible solution would be to update to the latest androidx dependencies in build.gradle.

**Comment by biodranik** [comment]
How to reproduce it?

**Comment by AndrewShkrob** [comment]
There such lines in `FeatureCategoryFragment.onViewCreated`

```java
if (getArguments() != null && getArguments().containsKey(FeatureCategoryActivity.EXTRA_FEATURE_CATEGORY))
  mSelectedCategory = getArguments().getParcelable(FeatureCategoryActivity.EXTRA_FEATURE_CATEGORY);
```

According to the documentation of `getParcelable`:
> Note: if the expected value is not a class provided by the Android platform, you must call setClassLoader(ClassLoader) with the proper ClassLoader first. Otherwise, this method might throw an exception or return null.

Maybe providing a ClassLoader of `FeatureCategory` would be a fix?

But I can't check as I'm not able to reproduce.

**Comment by biodranik** [comment]
You're most likely right! Good catch.

**Comment by rtsisyk** [comment]
> But I can't check as I'm not able to reproduce.

I don't know how to reproduce either. This ticket is a crash report from beta program. Can we try to add the classloader optimistically?
