### ISSUE TITLE
[android] android.content.ActivityNotFoundException: No Activity found to handle null

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3787]
- 2022.10.31-10-Google-beta (22103110)
- Android 12
- Mi 9 SE 1 

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle null
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2121)
       at android.app.Activity.startIntentSenderForResultInner(Activity.java:5673)
       at android.app.Activity.startIntentSenderForResult(Activity.java:5639)
       at androidx.activity.ComponentActivity.startIntentSenderForResult(ComponentActivity.java)
       at androidx.core.app.ActivityCompat$Api16Impl.startIntentSenderForResult(ActivityCompat.java)
       at androidx.core.app.ActivityCompat.startIntentSenderForResult(ActivityCompat.java)
       at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:142)
       at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:31)
       at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:1)
       at app.organicmaps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:28)
       at app.organicmaps.location.GoogleFusedLocationProvider.lambda$start$1(GoogleFusedLocationProvider.java:26)
       at app.organicmaps.location.GoogleFusedLocationProvider.$r8$lambda$dIkHCfw3ZIFPV5oe9T4QaLXcD1Q(GoogleFusedLocationProvider.java)
       at app.organicmaps.location.GoogleFusedLocationProvider$$InternalSyntheticLambda$1$0e6be5e7ffccd3465e211e92c793458a7ae217e4fd25ef39301a64df6fbaa530$1.onFailure(GoogleFusedLocationProvider.java:2)
       at com.google.android.gms.tasks.zzk.run(zzk.java:31)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
# Crashlytics - Custom logs
# Application: app.organicmaps.beta
# Platform: android
# Version: 2022.10.31-10-Google-beta (22103110)
# Issue: b4b9545507a15029fab5cee7cd9e32ce
# Session: 63609695030F000117758D9C294E32B9_DNE_0_v2
# Date: Tue Nov 01 2022 05:46:31 GMT+0200 (Eastern European Standard Time)

 0 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: SplashActivity: onCreate() activity: app.organicmaps.SplashActivity@587daf4
 1 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: SplashActivity: onStart() activity: app.organicmaps.SplashActivity@587daf4
 2 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: SplashActivity: onResume() activity: app.organicmaps.SplashActivity@587daf4
 3 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: SplashActivity: onPause() activity: app.organicmaps.SplashActivity@587daf4
 4 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: DownloadResourcesLegacyActivity: onCreate() activity: app.organicmaps.DownloadResourcesLegacyActivity@3d8cab2
 5 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: DownloadResourcesLegacyActivity: onSafeCreate() activity: app.organicmaps.DownloadResourcesLegacyActivity@3d8cab2
 6 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/DownloadResourcesLegacyActivity: Incoming intent uri: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=app.organicmaps.beta/app.organicmaps.DownloadResourcesActivity bnds=[0,81][1080,2337] }
 7 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: MwmActivity: onCreate() activity: app.organicmaps.MwmActivity@8b2904c
 8 | Tue Nov 01 2022 05:46:29 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: MwmActivity: onSafeCreate() activity: app.organicmaps.MwmActivity@8b2904c
 9 | Tue Nov 01 2022 05:46:30 GMT+0200 (Eastern European Standard Time) | I/BaseActivityDelegate: MwmActivity: onStart() activity: app.organicmaps.MwmActivity@8b2904c
```

**Comment by biodranik** [comment]
@rtsisyk location was there with a null activity? That's bad:
```
at app.organicmaps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:28)
```

**Comment by rtsisyk** [comment]
> @rtsisyk location was there with a null activity? That's bad:
> 
> ```
> at app.organicmaps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:28)
> ```

We check that LocationHelper is attached to activity in onLocationResolutionRequired(). It is not clear what was null.

**Comment by biodranik** [comment]
Could it be that pendingIntent is null or invalid?
```
  public void onLocationResolutionRequired(@Nullable PendingIntent pendingIntent)
  {
    Logger.d(TAG);

    if (mResolutionRequest == null) {
      onLocationDisabled();
      return;
    }

    IntentSenderRequest intentSenderRequest = new IntentSenderRequest.Builder(pendingIntent.getIntentSender())
        .build();
    mResolutionRequest.launch(intentSenderRequest);
  }
```

**Comment by rtsisyk** [comment]
Android 10
Model:Redmi 4X

https://console.firebase.google.com/project/omapsapp/crashlytics/app/android:app.organicmaps.beta/issues/e70dfa9f46d943454f5735d1709cab69?time=last-seven-days&sessionEventKey=64258F01024200015474B05FBEC2CB2B_1794776842395263122

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle null
       at android.app.Instrumentation.checkStartActivityResult(:128)
       at android.app.Activity.startIntentSenderForResultInner(:81)
       at android.app.Activity.startIntentSenderForResult(:15)
       at androidx.activity.ComponentActivity.startIntentSenderForResult(ComponentActivity.java)
       at androidx.core.app.ActivityCompat$Api16Impl.startIntentSenderForResult()
       at androidx.core.app.ActivityCompat.startIntentSenderForResult(ActivityCompat.java)
       at androidx.activity.ComponentActivity$2.onLaunch(:144)
       at androidx.activity.result.ActivityResultRegistry$2.launch(:31)
       at androidx.activity.result.ActivityResultLauncher.launch(:1)
       at app.organicmaps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:47)
       at app.organicmaps.location.GoogleFusedLocationProvider.lambda$start$1(GoogleFusedLocationProvider.java:2)
       at android.os.Handler.handleCallback(:2)
       at android.os.Handler.dispatchMessage(:4)
       at android.os.Looper.loop(:242)
       at android.app.ActivityThread.main(:101)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(:11)
       at com.android.internal.os.ZygoteInit.main(:275)
```

**Comment by rtsisyk** [comment]
Need to find a way how to reproduce this issue...
