### ISSUE TITLE
[android] Crash in the Editor

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3945]
```
--------- beginning of crash
11-22 13:16:57.331 E/AndroidRuntime( 7260): FATAL EXCEPTION: main
11-22 13:16:57.331 E/AndroidRuntime( 7260): Process: app.organicmaps, PID: 7260
11-22 13:16:57.331 E/AndroidRuntime( 7260): java.lang.IllegalStateException: Unexpected mPositionChooserMode
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at app.organicmaps.MwmActivity.lambda$initPositionChooser$3(Unknown Source:24)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at app.organicmaps.MwmActivity.i(Unknown Source:0)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at app.organicmaps.x.onClick(Unknown Source:2)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.view.View.performClick(View.java:7862)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.widget.TextView.performClick(TextView.java:15004)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.view.View.performClickInternal(View.java:7831)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.view.View.access$3600(View.java:879)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.view.View$PerformClick.run(View.java:29359)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.os.Handler.handleCallback(Handler.java:883)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.os.Looper.loop(Looper.java:237)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at java.lang.reflect.Method.invoke(Native Method)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
11-22 13:16:57.331 E/AndroidRuntime( 7260): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
--------- beginning of main
```

**Comment by vng** [comment]
This is my crash report. So, I added a bunch of POIs (10-20, cafes, buildings, names and addresses) and got first crash. Then got second crash when pressing crosshair to add next POI. Then sent report.

**Comment by biodranik** [comment]
I saw only one crash in the log. @rtsisyk it can be related to your recent crosshair API-related changes.

**Comment by rtsisyk** [comment]
I added a workaround.

**Comment by rtsisyk** [comment]
Fixed by #6586
