### ISSUE TITLE
Unable to run map_generator on osm.pbf and o5m extract files

### ISSUE THREAD

**Issue by hallahan** [organicmaps/organicmaps#4392]
I am trying to run maps_generator on a small extract of the Yukon Territories, Canada from Geofabrik. What am I doing wrong?

https://osm-internal.download.geofabrik.de/north-america/canada/yukon.html

I am running the following command.

```
python -m maps_generator --countries="World, WorldCoasts, Yukon_North, Yukon_Whitehorse"
```

Getting this error:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/maps_generator.py", line 6, in <module>
    from maps_generator.generator import stages_declaration as sd
  File "/Users/n/code/organicmaps/tools/python/maps_generator/maps_generator.py", line 6, in <module>
    from maps_generator.generator import stages_declaration as sd
ModuleNotFoundError: No module named 'maps_generator.generator'; 'maps_generator' is not a package
```

MacBookAir10,1
macOS 13.1 Ventura
Python 3.10.9

Using this for an ini:

```
[Main]
# If the flag DEBUG is set a special small planet file will be downloaded.
DEBUG: 0
# The path where the planet will be downloaded and the maps are generated.
MAIN_OUT_PATH: ~/maps_build
# The path where caches for nodes, ways, relations are stored.
# CACHE_PATH:


[Developer]
# The path where the generator_tool will be searched.
BUILD_PATH: ~/code/omim-build-release
# The path to the project directory omim.
OMIM_PATH: ~/code/organicmaps


[Generator tool]
# The path to the omim/data.
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# Do not change it. This is determined automatically.
# NODE_STORAGE: map


[Osm tools]
# The path to the osmctools sources.
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
# The path where osmctools will be searched or will be built.
OSM_TOOLS_PATH: ~/osmctools


[Stages]
# Run osmupdate tool for planet.
NEED_PLANET_UPDATE: 0
# Auto detection.
THREADS_COUNT_FEATURES_STAGE: 0
# If you want to calculate diffs, you need to specify, where old maps are
DATA_ARCHIVE_DIR: ${Generator tool:USER_RESOURCE_PATH}
# You may specify, how many versions in the archive to use for diff calculation
DIFF_VERSION_DEPTH: 2


[Logging]
# The path where maps_generator log will be saved.
# LOG_FILE_PATH: generation.log


[External]
# Note: If you want to set a directory name you have to add "/" to the end of url.
# In each field where you need to specify a URL, you can specify the path to the file system using file:///path/to/file

# The url to the planet file.
PLANET_URL: file:///opt/geodata/yukon.osm.pbf
# The url to the file with md5 sum of the planet.
PLANET_MD5_URL: file:///opt/geodata/yukon.osm.pbf.md5
# The base url to WorldCoasts.geom and WorldCoasts.rawgeom (without file name).
# Files latest_coasts.geom and latest_coasts.rawgeom must be at this URL.
# For example, if PLANET_COASTS_URL = https://somesite.com/download/
# The https://somesite.com/download/latest_coasts.geom url will be used to download latest_coasts.geom and
# the https://somesite.com/download/latest_coasts.rawgeom url will be used to download latest_coasts.rawgeom.
# PLANET_COASTS_URL:
# Set to 'true' to build special routing section in World.mwm for alerting about absent regions without which the
# route can't be built.
NEED_BUILD_WORLD_ROADS: true
# The url to the subway file.
SUBWAY_URL: https://cdn.organicmaps.app/subway.json

# The url of the location with the transit files extracted from GTFS.
# TRANSIT_URL:

# Urls for production maps generation.
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# SRTM_PATH:
# ISOLINES_PATH:
# UK_POSTCODES_URL:
# US_POSTCODES_URL:


[Common]
# Auto detection.
THREADS_COUNT: 0


[Stats]
# Path to rules for calculating statistics by type
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
```

**Comment by endim8** [comment]
make sure you're running the `maps_generator` command from `organicmaps/tools/python`, not the maps_generator sub-folder

**Comment by hallahan** [comment]
Ah, good catch. I'm a little bit further now... It looks like the omim-generator_tool binary is not found.

```
n@m python % python -m maps_generator --countries="World, WorldCoasts, Canada_Yukon_North, Canada_Yukon_Whitehorse"
[2023-02-03 12:08:34,134] INFO env Start setup ...
[2023-02-03 12:08:34,134] INFO env Check osm tools ...
[2023-02-03 12:08:34,134] INFO env Osm tools found - /Users/n/osmctools/osmconvert, /Users/n/osmctools/osmupdate, /Users/n/osmctools/osmfilter
[2023-02-03 12:08:34,134] INFO env Check generator tool ...
[2023-02-03 12:08:34,134] INFO env Looking for generator tool in /Users/n/code/omim-build-release ...
[2023-02-03 12:08:34,151] INFO env Looking for generator tool in /Users/n/code/omim-build-release ...
[2023-02-03 12:08:34,165] ERROR env Uncaught exception: [FileNotFoundError('generator_tool not found in /Users/n/code/omim-build-release'), FileNotFoundError('omim-generator_tool not found in /Users/n/code/omim-build-release')]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/__main__.py", line 303, in <module>
    main()
  File "/Users/n/code/organicmaps/tools/python/maps_generator/__main__.py", line 285, in main
    env = Env(
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/env.py", line 424, in __init__
    self.gen_tool = self.setup_generator_tool()
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/env.py", line 529, in setup_generator_tool
    raise Exception(exceptions)
Exception: [FileNotFoundError('generator_tool not found in /Users/n/code/omim-build-release'), FileNotFoundError('omim-generator_tool not found in /Users/n/code/omim-build-release')]
```

Note that I did build via:

```
./tools/unix/build_omim.sh -r desktop
```

**Comment by hallahan** [comment]
Is there a specific build command to create omim-generator_tool ?

**Comment by endim8** [comment]
> Is there a specific build command to create omim-generator_tool ?

Yup, try `./tools/unix/build_omim.sh -r generator_tool` :)

I think I'll have a look at improving those docs...

**Comment by hallahan** [comment]
Looks like I also needed to:

```
./tools/unix/build_omim.sh -r world_roads_builder_tool
```

**Comment by hallahan** [comment]
Now I am getting the error:

```
[2023-02-03 12:24:08,707] ERROR env Uncaught exception: [Errno 20] Not a directory: '/opt/geodata/yukon.osm.pbf'
```

My ini has this for planet URL:

```
PLANET_URL: file:///opt/geodata/yukon.osm.pbf
PLANET_MD5_URL: file:///opt/geodata/yukon.osm.pbf.md5
```

What should I be doing instead? I could just link to GeoFabrik directly, but I worry there will be issues with that new OSM Internal auth wall they put up...

**Comment by biodranik** [comment]
Strange. Is there anything else in the log? Can you try with o5m format instead of pbf?

**Comment by hallahan** [comment]
This is the full stack in the log:

```
[2023-02-03 12:24:08,707] ERROR env Uncaught exception: [Errno 20] Not a directory: '/opt/geodata/yukon.osm.pbf'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/__main__.py", line 303, in <module>
    main()
  File "/Users/n/code/organicmaps/tools/python/maps_generator/__main__.py", line 299, in main
    generate_maps(env, from_stage)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/maps_generator.py", line 43, in generate_maps
    run_generation(env, stages, from_stage)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 60, in apply
    steps.step_download_and_convert_planet(
  File "/Users/n/code/organicmaps/tools/python/maps_generator/generator/steps.py", line 57, in step_download_and_convert_planet
    download_files(
  File "/Users/n/code/organicmaps/tools/python/maps_generator/utils/file.py", line 175, in download_files
    pool.starmap(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/n/code/organicmaps/tools/python/maps_generator/utils/file.py", line 68, in download_file
    copy_overwrite(file_uri_to_path(url), name)
  File "/Users/n/code/organicmaps/tools/python/maps_generator/utils/file.py", line 192, in copy_overwrite
    shutil.copytree(from_path, to_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
NotADirectoryError: [Errno 20] Not a directory: '/opt/geodata/yukon.osm.pbf'
```

For some reason it wants the file to be a dir. I'm guessing the `file://` expects a dir and a file name is hardcoded?

**Comment by hallahan** [comment]
> Strange. Is there anything else in the log? Can you try with o5m format instead of pbf?

I've never used o5m before. That's one of the more obscure OSM formats. I see the project compiles `osmconvert`, though I don't see it in `omim-build_release`.

**Comment by endim8** [comment]
(in the meantime, Geofabrik links work nicely. You only have to login with OSM for the extracts with user metadata, which isn't used by OM anyway)

**Comment by hallahan** [comment]
It looks like I need a latest_coasts.rawgeom file that has not yet been open-sourced?

I get this error:

```
requests.exceptions.MissingSchema: Invalid URL 'latest_coasts.rawgeom': No schema supplied. Perhaps you meant http://latest_coasts.rawgeom?
```

Then, I try again without `WorldCoasts` and I get this error:

```
requests.exceptions.MissingSchema: Invalid URL 'latest_coasts.geom': No schema supplied. Perhaps you meant http://latest_coasts.geom?
```

**Comment by endim8** [comment]
ah, i think the latest_coasts file is only generated in a whole-world generation. 

Viktor said it will be uploaded soon, but in the meantime you can add --skip="Coastline". (at least it works for london, i've never had to generate a mwm on the coast)

**Comment by hallahan** [comment]
Ok, now a little further...

It appears to have worked according to the logs, but I don't see the MWM file in maps_build.
<img width="414" alt="Screenshot 2023-02-03 at 1 24 17 PM" src="https://user-images.githubusercontent.com/556367/216713631-f6629d61-caaf-4764-aaa9-1844b90c879f.png">

```
...
[2023-02-03 13:19:37,906] INFO stages Stage Mwm: finished in 0:00:59.773982
[2023-02-03 13:19:37,906] INFO stages Stage CountriesTxt: start ...
[2023-02-03 13:19:37,974] INFO stages Stage CountriesTxt: finished in 0:00:00.067902
[2023-02-03 13:19:37,974] INFO stages Stage Statistics: start ...
[2023-02-03 13:19:38,022] INFO stages Stage Statistics: finished in 0:00:00.046960
[2023-02-03 13:19:38,022] INFO stages Stage Cleanup: start ...
[2023-02-03 13:19:38,022] INFO stages_declaration osm2ft files will be moved from /Users/n/maps_build/2023_02_03__13_18_08/230203 to /Users/n/maps_build/2023_02_03__13_18_08/osm2ft.
[2023-02-03 13:19:38,022] INFO stages_declaration /Users/n/maps_build/2023_02_03__13_18_08/draft will be removed.
[2023-02-03 13:19:38,022] INFO stages Stage Cleanup: finished in 0:00:00.000596
```

**Comment by hallahan** [comment]
Success!

That's a good start for today! 

How do I open a specific MWM file in the desktop app?

<img width="315" alt="Screenshot 2023-02-03 at 1 33 19 PM" src="https://user-images.githubusercontent.com/556367/216714858-7517abd7-5fee-4628-971c-ad646a203e9f.png">

**Comment by hallahan** [comment]
Just for future reference, this is the command that worked. 

Make sure pwd is in `tools/python`.

```
python -m maps_generator --countries="Canada_Yukon_North, Canada_Yukon_Whitehorse" --skip="Coastline"
```

And this is the var/etc/map_generator.ini file:

```
[Main]
# If the flag DEBUG is set a special small planet file will be downloaded.
DEBUG: 0
# The path where the planet will be downloaded and the maps are generated.
MAIN_OUT_PATH: ~/maps_build
# The path where caches for nodes, ways, relations are stored.
# CACHE_PATH:


[Developer]
# The path where the generator_tool will be searched.
BUILD_PATH: ~/code/omim-build-release
# The path to the project directory omim.
OMIM_PATH: ~/code/organicmaps


[Generator tool]
# The path to the omim/data.
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# Do not change it. This is determined automatically.
# NODE_STORAGE: map


[Osm tools]
# The path to the osmctools sources.
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
# The path where osmctools will be searched or will be built.
OSM_TOOLS_PATH: ~/osmctools


[Stages]
# Run osmupdate tool for planet.
NEED_PLANET_UPDATE: 0
# Auto detection.
THREADS_COUNT_FEATURES_STAGE: 0
# If you want to calculate diffs, you need to specify, where old maps are
DATA_ARCHIVE_DIR: ${Generator tool:USER_RESOURCE_PATH}
# You may specify, how many versions in the archive to use for diff calculation
DIFF_VERSION_DEPTH: 2


[Logging]
# The path where maps_generator log will be saved.
# LOG_FILE_PATH: generation.log


[External]
# Note: If you want to set a directory name you have to add "/" to the end of url.
# In each field where you need to specify a URL, you can specify the path to the file system using file:///path/to/file

# The url to the planet file.
PLANET_URL: https://download.geofabrik.de/north-america/canada/yukon-latest.osm.pbf
# The url to the file with md5 sum of the planet.
PLANET_MD5_URL: https://download.geofabrik.de/north-america/canada/yukon-latest.osm.pbf.md5
# The base url to WorldCoasts.geom and WorldCoasts.rawgeom (without file name).
# Files latest_coasts.geom and latest_coasts.rawgeom must be at this URL.
# For example, if PLANET_COASTS_URL = https://somesite.com/download/
# The https://somesite.com/download/latest_coasts.geom url will be used to download latest_coasts.geom and
# the https://somesite.com/download/latest_coasts.rawgeom url will be used to download latest_coasts.rawgeom.
# PLANET_COASTS_URL:
# Set to 'true' to build special routing section in World.mwm for alerting about absent regions without which the
# route can't be built.
NEED_BUILD_WORLD_ROADS: true
# The url to the subway file.
SUBWAY_URL: https://cdn.organicmaps.app/subway.json

# The url of the location with the transit files extracted from GTFS.
# TRANSIT_URL:

# Urls for production maps generation.
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# SRTM_PATH:
# ISOLINES_PATH:
# UK_POSTCODES_URL:
# US_POSTCODES_URL:


[Common]
# Auto detection.
THREADS_COUNT: 0


[Stats]
# Path to rules for calculating statistics by type
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
```

**Comment by endim8** [comment]
> Success!

woo 🥳

> How do I open a specific MWM file in the desktop app?

the desktop app uses a symlink to the gitrepo /data/ folder, so move the .mwm files to `organicmaps/data/230121` (might not be 230121, whichever folder's name is 6 numbers) then re-open the app and they'll be loaded :)

**Comment by endim8** [comment]
Can confirm that an .o5m file fails with the same NotADirectoryError

**Comment by hallahan** [comment]
I'll change the title to the issue to this problem.

**Comment by pastk** [comment]
Now the docs clearly state that the planet is supposed to be in osm.pbf format.
If you think that o5m should be supported then maybe better create a new issue (this one if full of unrelated info already)..
