### ISSUE TITLE
Map Generation fails on version check after building in conteiner

### ISSUE THREAD

**Issue by danvyr** [organicmaps/organicmaps#4739]
**Describe the issue**
Trying  to build and run generator_tool in container
 
**System information:**
 - Operating system and its version:   Ubuntu 22

**Additional context**
After commented this line all working: https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/generator/gen_tool.py#L153

organicmaps@4b28a419eb92:~$ /organicmaps/omim-build-release/generator_tool --version
generator_tool version 2023.03.09-0-00000000-Linux

[2023-03-09 12:17:37,284] ERROR env Uncaught exception: The launch of /organicmaps/omim-build-release/generator_tool --version failed.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/organicmaps/organicmaps/tools/python/maps_generator/__main__.py", line 303, in <module>
    main()
  File "/organicmaps/organicmaps/tools/python/maps_generator/__main__.py", line 299, in main
    generate_maps(env, from_stage)
  File "/organicmaps/organicmaps/tools/python/maps_generator/maps_generator.py", line 43, in generate_maps
    run_generation(env, stages, from_stage)
  File "/organicmaps/organicmaps/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 102, in apply
    steps.step_preprocess(env, **kwargs)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/steps.py", line 95, in step_preprocess
    run_gen_tool(
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 163, in run_gen_tool
    GenTool(*args, **kwargs).run()
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 138, in run
    self.run_async()
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 128, in run_async
    f"Run generator tool [{self.get_build_version()}]:" f" {' '.join(cmd)} "
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 153, in get_build_version
    wait_and_raise_if_fail(p)
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/exceptions.py", line 38, in wait_and_raise_if_fail
    raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /organicmaps/omim-build-release/generator_tool --version failed.

**Comment by strump** [comment]
Do you use docker? Can you run manually `/organicmaps/omim-build-release/generator_tool --version` and see output?

**Comment by danvyr** [comment]
yes I used docker

4b28a419eb92:~$ /organicmaps/omim-build-release/generator_tool --version
generator_tool version 2023.03.09-0-00000000-Linux

**Comment by biodranik** [comment]
Some dependencies like Qt libraries may not be found in a container for some reason (paths? arch?)

**Comment by danvyr** [comment]
I tried to add to second image all I installing in first image with same result
https://github.com/danvyr/osmmapsconverter/blob/9413fffd34f8e02e4b871695b849a189a4558141/organicmap/Dockerfile#L6

But why it's working with this line commented https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/generator/gen_tool.py#L152?

**Comment by strump** [comment]
@danvyr you can add more logging to `tools/python/maps_generator/generator/exceptions.py` replace

```
raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
```

with more verbose:

```
raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed with {p.returncode}.\nstdout: {p.stdout.read()}\nstderr: {p.stderr.read()}")
```

**Comment by danvyr** [comment]
So the problem that **generator_tool** can't create   **/organicmaps/.config/OMaps**

Solution in my situation was to add in Dockerfile 
`mkdir /organicmaps/.config/OMaps`

But anyway that is strange because user have all required permission for that
```
organicmaps@a4fc533b4142:~$ whoami 
organicmaps
organicmaps@a4fc533b4142:~$ ls -l
total 32
-rw-rw-r--  1 organicmaps organicmaps 1230 Nov 18 16:05 generate_map.sh
-rw-rw-r--  1 organicmaps organicmaps  716 Nov 18 16:05 map_generator.ini.template
drwxr-xr-x  1 organicmaps organicmaps 4096 Mar 14 11:20 maps_build
-rw-rw-r--  1 organicmaps organicmaps 1659 Nov 18 16:05 move_result.py
drwxr-xr-x 36 organicmaps organicmaps 4096 Mar 14 11:44 omim-build-release
drwxr-xr-x  1 organicmaps organicmaps 4096 Mar 14 11:20 organicmaps
drwxr-xr-x  1 organicmaps organicmaps 4096 Mar 14 11:20 out
organicmaps@a4fc533b4142:~$ ls -l /
drwxr-xr-x   1 organicmaps organicmaps 4096 Mar 14 11:44 organicmaps

```

The error:

```
  File "/organicmaps/organicmaps/tools/python/maps_generator/generator/exceptions.py", line 39, in wait_and_raise_if_fail
    raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed with {p.returncode}.\nstdout: {p.stdout.read()}\nstderr: {p.stderr.read()}")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /organicmaps/omim-build-release/generator_tool --version failed with -6.
stdout: b''
stderr: b'LOG TID(1) WARNING 6.705e-06 platform/platform_qt.cpp:62 MkDir(): Can\'t create directory:  /organicmaps/.config\nterminate called after throwing an instance of \'FileSystemException\'\n  what():  FileSystemException /organicmaps/platform/platform_linux.cpp:92, "Can\'t create directory /organicmaps/.config/OMaps"\nCore exception: Can\'t create directory /organicmaps/.config/OMaps\n 0# 0x0000560853266D4A in /organicmaps/omim-build-release/generator_tool\n 1# 0x00007FE0AF33B520 in /lib/x86_64-linux-gnu/libc.so.6\n 2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6\n 3# raise in /lib/x86_64-linux-gnu/libc.so.6\n 4# abort in /lib/x86_64-linux-gnu/libc.so.6\n 5# 0x00007FE0AF6CCBBE in /lib/x86_64-linux-gnu/libstdc++.so.6\n 6# 0x00007FE0AF6D824C in /lib/x86_64-linux-gnu/libstdc++.so.6\n 7# 0x00007FE0AF6D82B7 in /lib/x86_64-linux-gnu/libstdc++.so.6\n 8# 0x00007FE0AF6D8518 in /lib/x86_64-linux-gnu/libstdc++.so.6\n 9# 0x000056085322837A in /organicmaps/omim-build-release/generator_tool\n10# 0x000056085396D522 in /organicmaps/omim-build-release/generator_tool\n11# 0x00005608532526B5 in /organicmaps/omim-build-release/generator_tool\n12# 0x000056085323B6D9 in /organicmaps/omim-build-release/generator_tool\n13# 0x00007FE0AF322D90 in /lib/x86_64-linux-gnu/libc.so.6\n14# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6\n15# 0x0000560853252095 in /organicmaps/omim-build-release/generator_tool\n'

```

**Comment by strump** [comment]
By default mkdir fails to create directory `/organicmaps/.config/OMaps` if parent directory `/organicmaps/.config` doesn't exists.

**Comment by biodranik** [comment]
There is this piece of code in platform/platform_linux.cpp that should work (but it doesn't, for some reason). Let's debug it, for example, by printing logs and errors in Platform::MkDirRecursively and platform::MkDir

```
  // XDG config directory, usually ~/.config/OMaps/
  m_settingsDir = JoinPath(
      QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation).toStdString(),
      "OMaps");
  if (!IsFileExistsByFullPath(JoinPath(m_settingsDir, SETTINGS_FILE_NAME)) && !MkDirRecursively(m_settingsDir))
    MYTHROW(FileSystemException, ("Can't create directory", m_settingsDir));
```

**Comment by trundev** [comment]
Just struggled with this in GitHub Actions.
My wild guess is that the two instances of the `generator_tool`, run by the python script (one for actual work, another to add version-info to log), both try to create the `~/.config/OMaps/` folder. One of these instances create the folder first, in the other `MkDirRecursively()` fails, because it already exists. I.e. some racing condition.

I workaround it by first run `generator_tool --version` alone, then the python script. Hope this makes any sense :)
