### ISSUE TITLE
[android] ANR in app.organicmaps.downloader.ChunkTask::nativeOnWrite

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#4897]
Version: 2023.03.31-4-Google-beta (23033104)
OS version: android12
Model:Redmi Note 9
Date: 31 Mar 2023, 23:21:01 

https://console.firebase.google.com/project/omapsapp/crashlytics/app/android:app.organicmaps.beta/issues/45df488b45a4d9374a8f894735a65f52?time=last-seven-days&sessionEventKey=642737F6003F000174D00C443404C1E1_1795253645142069848

```
main (native):tid=1 systid=29904 
#00 pc 0xd82c8 libc.so (write + 8) (BuildId: 8607e22d19978fe368fdf8f39b0835df)
#01 pc 0xe3d7c libc.so (__swrite + 52) (BuildId: 8607e22d19978fe368fdf8f39b0835df)
#02 pc 0xe53a8 libc.so (__fseeko64(__sFILE*, long, int, int) + 448) (BuildId: 8607e22d19978fe368fdf8f39b0835df)
#03 pc 0xf6a690 liborganicmaps.so (base::FileData::Seek(unsigned long) [file_data.cpp:123]) (BuildId: 926ecf475b8ef2c3abbbe17e8b3fefa46b7ed37b)
#04 pc 0xf450d8 liborganicmaps.so (downloader::FileHttpRequest::OnWrite(long, void const*, unsigned long) [http_request.cpp:190]) (BuildId: 926ecf475b8ef2c3abbbe17e8b3fefa46b7ed37b)
#05 pc 0x7eda90 liborganicmaps.so (Java_app_organicmaps_downloader_ChunkTask_nativeOnWrite [HttpThread.cpp:92]) (BuildId: 926ecf475b8ef2c3abbbe17e8b3fefa46b7ed37b)
#06 pc 0x461554 libart.so (art_quick_generic_jni_trampoline + 148) (BuildId: 289d75599f6112d5757113220599e90b)
#07 pc 0x2017dcc memfd:jit-cache (app.organicmaps.downloader.ChunkTask.onProgressUpdate + 172)
#08 pc 0x20a2b0 libart.so (nterp_helper + 4016) (BuildId: 289d75599f6112d5757113220599e90b)
#09 pc 0x3c0ee8 base.vdex (app.organicmaps.downloader.ChunkTask.onProgressUpdate + 4)
#10 pc 0x2acaa88 memfd:jit-zygote-cache (android.os.AsyncTask$InternalHandler.handleMessage + 152)
#11 pc 0x2067108 memfd:jit-zygote-cache (android.os.Handler.dispatchMessage + 184)
#12 pc 0x2b141bc memfd:jit-zygote-cache (android.os.Looper.loopOnce + 1068)
#13 pc 0x2084700 memfd:jit-zygote-cache (android.os.Looper.loop + 576)
#14 pc 0x209398 libart.so (nterp_helper + 152) (BuildId: 289d75599f6112d5757113220599e90b)
#15 pc 0x1ca85e framework.jar (android.app.ActivityThread.main + 294)
#16 pc 0x457e00 libart.so (art_quick_invoke_static_stub + 576) (BuildId: 289d75599f6112d5757113220599e90b)
#17 pc 0x48c038 libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long) + 1560) (BuildId: 289d75599f6112d5757113220599e90b)
#18 pc 0x48b9f8 libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277) + 48) (BuildId: 289d75599f6112d5757113220599e90b)
#19 pc 0x461554 libart.so (art_quick_generic_jni_trampoline + 148) (BuildId: 289d75599f6112d5757113220599e90b)
#20 pc 0x3013808 memfd:jit-zygote-cache (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 136)
#21 pc 0x20b0d4 libart.so (nterp_helper + 7636) (BuildId: 289d75599f6112d5757113220599e90b)
#22 pc 0x257824 framework.jar (com.android.internal.os.ZygoteInit.main + 632)
#23 pc 0x457e00 libart.so (art_quick_invoke_static_stub + 576) (BuildId: 289d75599f6112d5757113220599e90b)
#24 pc 0x58bbc4 libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list) + 912) (BuildId: 289d75599f6112d5757113220599e90b)
#25 pc 0x609af8 libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list) + 172) (BuildId: 289d75599f6112d5757113220599e90b)
#26 pc 0xb0b28 libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...) + 120) (BuildId: 33cc17c07772f5872660248e833abf08)
#27 pc 0xbc26c libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool) + 948) (BuildId: 33cc17c07772f5872660248e833abf08)
#28 pc 0x2580 app_process64 (main + 1320) (BuildId: 469d43e945c656826adddaafd0f4f12c)
#29 pc 0x82180 libc.so (__libc_init + 96) (BuildId: 8607e22d19978fe368fdf8f39b0835df)
       at app.organicmaps.downloader.ChunkTask.nativeOnWrite(Native method)
       at app.organicmaps.downloader.ChunkTask.onProgressUpdate(unavailable:18)
       at app.organicmaps.downloader.ChunkTask.onProgressUpdate(unavailable:2)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8280)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by biodranik** [comment]
It is highly likely caused by a slow or damaged SD-card. We should detect slow SD cards automatically and suggest users to replace them.
