### ISSUE TITLE
Public Transit: maps_generator doesn't accept file input

### ISSUE THREAD

**Issue by koenvanhollebeke** [organicmaps/organicmaps#5184]
Hi,
Compiled successfully generator tool, world_roads_builder_tool and gtfs_converter. Building of maps from planet URL files (pbf&md5) works.

However the suggested format from [here](https://github.com/organicmaps/organicmaps/tree/master/tools/python/maps_generator), either file:///path/to/file or file://path/to/file as input for the planet and transit files/directory results in an error running the maps_generator:

> koenvh@koenvh-VivoBook-ASUSLaptop-E210MAB-E210MA:~/organicmaps/tools/python$ python3 -m maps_generator --countries="Indonesia_Jawa Barat" --skip="Coastline"
[2023-05-18 18:10:20,407] INFO env Start setup ...
[2023-05-18 18:10:20,408] INFO env Check osm tools ...
[2023-05-18 18:10:20,408] INFO env Osm tools found - /home/koenvh/osmctools/osmconvert, /home/koenvh/osmctools/osmupdate, /home/koenvh/osmctools/osmfilter
[2023-05-18 18:10:20,408] INFO env Check generator tool ...
[2023-05-18 18:10:20,408] INFO env Looking for generator tool in /home/koenvh/omim-build-release ...
[2023-05-18 18:10:20,409] INFO env Generator tool found - /home/koenvh/omim-build-release/generator_tool
[2023-05-18 18:10:20,409] INFO env Build name is 2023_05_18__18_10_20.
[2023-05-18 18:10:20,409] INFO env Build path is /home/koenvh/maps_build/2023_05_18__18_10_20.
[2023-05-18 18:10:20,409] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20 ...
[2023-05-18 18:10:20,409] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/intermediate_data ...
[2023-05-18 18:10:20,409] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/intermediate_data/borders ...
[2023-05-18 18:10:20,410] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/draft ...
[2023-05-18 18:10:20,410] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/osm2ft ...
[2023-05-18 18:10:20,410] INFO env The following 1 maps will build: Indonesia_Jawa Barat.
[2023-05-18 18:10:20,410] INFO env Finish setup
[2023-05-18 18:10:20,411] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/logs ...
[2023-05-18 18:10:20,411] INFO stages Stage DownloadAndConvertPlanet: start ...
[2023-05-18 18:10:20,411] INFO env Create /home/koenvh/maps_build/2023_05_18__18_10_20/status ...
[2023-05-18 18:10:20,416] INFO file Trying to download /home/koenvh/maps_build/2023_05_18__18_10_20/planet.osm.pbf from file://home/koenvh/Downloads/jakarta-latest.osm.pbf.
[2023-05-18 18:10:20,416] INFO file Trying to download /home/koenvh/maps_build/2023_05_18__18_10_20/planet.osm.pbf.md5 from file://home/koenvh/Downloads/jakarta-latest.osm.pbf.md5.
[2023-05-18 18:10:20,417] INFO stages Stage DownloadAndConvertPlanet: finished in 0:00:00.006257
[2023-05-18 18:10:20,418] ERROR env Uncaught exception: [Errno 2] No such file or directory: '/koenvh/Downloads/jakarta-latest.osm.pbf'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/__main__.py", line 303, in <module>
    main()
  File "/home/koenvh/organicmaps/tools/python/maps_generator/__main__.py", line 299, in main
    generate_maps(env, from_stage)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/maps_generator.py", line 43, in generate_maps
    run_generation(env, stages, from_stage)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 60, in apply
    steps.step_download_and_convert_planet(
  File "/home/koenvh/organicmaps/tools/python/maps_generator/generator/steps.py", line 57, in step_download_and_convert_planet
    download_files(
  File "/home/koenvh/organicmaps/tools/python/maps_generator/utils/file.py", line 175, in download_files
    pool.starmap(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/koenvh/organicmaps/tools/python/maps_generator/utils/file.py", line 68, in download_file
    copy_overwrite(file_uri_to_path(url), name)
  File "/home/koenvh/organicmaps/tools/python/maps_generator/utils/file.py", line 192, in copy_overwrite
    shutil.copytree(from_path, to_path)
  File "/usr/lib/python3.10/shutil.py", line 556, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/koenvh/Downloads/jakarta-latest.osm.pbf'

Had a similar problem with the gtfs_converter:
> ./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds="file:///home/koenvh/Downloads/" --path_json="file:///home/koenvh/Downloads/" --path_resources="file:///home/koenvh/omim-build-release/data/" LOG TID(1) WARNING 3.4137e-05 gtfs_converter/gtfs_converter.cpp:295 main(): Some paths set in options are not valid. Check the directories: file:///home/koenvh/Downloads/ file:///home/koenvh/Downloads/ file:///home/koenvh/omim-build-release/data/ gtfs_converter: Reads GTFS feeds or subway transit.json, produces json with global ids for generator.

which was resolved using the following syntax:
> ./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=/home/koenvh/Downloads/ --path_json=/home/koenvh/Downloads/ --path_resources=/home/koenvh/omim-build-release/data/

Unfortunately trying the same file/directory formatting as input for the maps_generator in the ini file doesn't work.

**System information:**
 - Operating system and its version: [Ubuntu 22]
 - Organic Maps version: [built from master]

**Comment by vng** [comment]
```
/home/koenvh/maps_build/2023_05_18__18_10_20/planet.osm.pbf from file://home/koenvh/Downloads/jakarta-latest.osm.pbf.
[2023-05-18 18:10:20,416] INFO file Trying to download /home/koenvh/maps_build/2023_05_18__18_10_20/planet.osm.pbf.md5 from file://home/koenvh/Downloads/jakarta-latest.osm.pbf.md5.
[2023-05-18 18:10:20,417] INFO stages Stage DownloadAndConvertPlanet: finished in 0:00:00.006257
[2023-05-18 18:10:20,418] ERROR env Uncaught exception: [Errno 2] No such file or directory: '/koenvh/Downloads/jakarta-latest.osm.pbf'
```

Make sure that you have 3 slashes as described in Readme: ```file:///path/to/file```
file:// - is a scheme and actual path is /home/...

**Comment by koenvanhollebeke** [comment]
Hi,
Tried it also with 3 slashes... no avail:

> [2023-05-20 09:37:06,100] INFO env Create /home/koenvh/maps_build/2023_05_20__09_37_06/status ...
[2023-05-20 09:37:06,105] INFO file Trying to download /home/koenvh/maps_build/2023_05_20__09_37_06/planet.osm.pbf from file:///home/koenvh/Downloads/jakarta.pbf.
[2023-05-20 09:37:06,105] INFO file Trying to download /home/koenvh/maps_build/2023_05_20__09_37_06/planet.osm.pbf.md5 from file:///home/koenvh/Downloads/jakarta.md5.
[2023-05-20 09:37:06,108] INFO stages Stage DownloadAndConvertPlanet: finished in 0:00:00.008389
[2023-05-20 09:37:06,108] ERROR env Uncaught exception: [Errno 20] Not a directory: '/home/koenvh/Downloads/jakarta.pbf'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

Added a screenshot of the file directory and location... Any ideas?

![Screenshot from 2023-05-20 09-43-43](https://github.com/organicmaps/organicmaps/assets/133847300/439ec5dc-cff8-4c7c-80d2-b0283385b37c)

**Comment by koenvanhollebeke** [comment]
Hi,
Found out the problem: file:///path/to/file expects a path ONLY (as the error indicates). The description in the readme is ambiguous... Files load from that indicated directory but not if the osm.pbf and osm.pbf.md5 file are together in one directory. This is probably also the explanation for not loading files in #4392

But then we run into another problem: I am not an md5sum expert but downloaded from the same osm source (ie https://osmtoday.com/asia/indonesia/jakarta.html) and placed in 2 separate directories (such that the maps_generator code loads them both) results in:

> [2023-05-20 14:15:34,882] INFO file Trying to download /home/koenvh/maps_build/2023_05_20__14_15_34/planet.osm.pbf from file:///home/koenvh/inputpbf/.
[2023-05-20 14:15:34,882] INFO file Trying to download /home/koenvh/maps_build/2023_05_20__14_15_34/planet.osm.pbf.md5 from file:///home/koenvh/inputmd5/.
[2023-05-20 14:15:34,883] INFO file File /home/koenvh/maps_build/2023_05_20__14_15_34/planet.osm.pbf.md5 was copied from file:///home/koenvh/inputmd5/.
[2023-05-20 14:15:34,961] INFO file File /home/koenvh/maps_build/2023_05_20__14_15_34/planet.osm.pbf was copied from file:///home/koenvh/inputpbf/.
[2023-05-20 14:15:34,962] INFO stages Stage DownloadAndConvertPlanet: finished in 0:00:00.083942
[2023-05-20 14:15:34,962] ERROR env Uncaught exception: Wrong md5 sum for /home/koenvh/maps_build/2023_05_20__14_15_34/planet.osm.pbf.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

Files are correctly placed into 2 folders (planet.osm.pbf, planet.osm.pbf.md5) under the built, but md5sum check goes wrong.
![Screenshot from 2023-05-20 14-16-56](https://github.com/organicmaps/organicmaps/assets/133847300/94667ac1-212b-4eb9-b669-796fb9d8ec42)

**Comment by vng** [comment]
Aha, you have python 3.10+
Python recently changed their copy API behavior:
Try this branch and let us know if it helps: https://github.com/organicmaps/organicmaps/pull/5200

**Comment by koenvanhollebeke** [comment]
Trying now. there might be an error in the from_path and to_path for the def copy_overwrite in file.py. 
Logging shows in my case:
from_path = /home/koenvh/inputjson/jakarta_subway2.json 
to_path = /home/koenvh/maps_build/2023_05_20__14_40_47/intermediate_data/mapsme_osm_subways.transit.json/jakarta_subway2.json

to_path should be /home/koenvh/maps_build/2023_05_20__14_40_47/intermediate_data/mapsme_osm_subways.transit.json only not?

**Comment by koenvanhollebeke** [comment]
> Aha, you have python 3.10+ Python recently changed their copy API behavior: Try this branch and let us know if it helps: #5200

Doesn't work neither - did a quick local copy of the changes to def copy_overwrite as indicated in #5200. I get this:

> INFO file Trying to download /home/koenvh/maps_build/2023_05_20__14_54_19/intermediate_data/mapsme_osm_subways.transit.json/jakarta_subway2.json from file:///home/koenvh/inputjson/jakarta_subway2.json.
[2023-05-20 14:59:27,048] WARNING file Copy error: [Errno 2] No such file or directory: '/home/koenvh/maps_build/2023_05_20__14_54_19/intermediate_data/mapsme_osm_subways.transit.json/jakarta_subway2.json'.
[2023-05-20 14:59:27,054] INFO stages Stage Mwm: finished in 0:02:33.068213
[2023-05-20 14:59:27,057] ERROR env Uncaught exception: [Errno 2] No such file or directory: '/home/koenvh/maps_build/2023_05_20__14_54_19/intermediate_data/mapsme_osm_subways.transit.json/jakarta_subway2.json'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

**Comment by vng** [comment]
This is another problem with subway jsons. Should check your map_generator.ini file

Your initial error was about ```Stage DownloadAndConvertPlanet``` and coping planet files. Is it solved?

**Comment by koenvanhollebeke** [comment]
> This is another problem with subway jsons. Should check your map_generator.ini file
> 
> Your initial error was about `Stage DownloadAndConvertPlanet` and coping planet files. Is it solved?

No, that's not fixed neither: 
- in case the planet.osm.pbf and planet.osm.pbf.md5 files (downloaded from a repository having those files) are placed in the same directory (eg. /home/koenvh/Downloads) the maps_generator ONLY loads the md5 file and gives an error on a wrong checksum
- in case the planet.osm.pbf and planet.osm.pbf.md5 files are placed in separate directories (eg. /home/koenvh/pbf and /home/koenvh/md5) both files are loaded into resp. planet.osm.pbf and planet.osm.pbf.md5 directories under the built, but the maps_generator still crashes on the md5 checksum check.

This doesn't happen when downloading the pbf and md5 files (same source) directly via url.
Attached is the maps_generator.ini file. Line 55 and 60 are enabled for the above second case (and line 56 & 61 disabled of course)
[map_generator.ini.txt](https://github.com/organicmaps/organicmaps/files/11522773/map_generator.ini.txt)

**Comment by vng** [comment]
```
# PLANET_URL: file:///home/koenvh/inputpbf/
PLANET_URL: https://osmtoday.com/asia/indonesia/jakarta.pbf
```
This is **not** right. Documentation says that ```you can specify the path to the file system using file:///path/to/file```
But you passed some folder?

**Comment by koenvanhollebeke** [comment]
The ini file with:

> PLANET_URL: file:///home/koenvh/inputpbf/
PLANET_MD5_URL: file:///home/koenvh/inputmd5/

passes the files correctly to the directories in the built
![Screenshot from 2023-05-20 14-16-56](https://github.com/organicmaps/organicmaps/assets/133847300/6d351199-3b14-4c80-9904-d2dfad457764)

**Comment by vng** [comment]
I don't have much time to make this kind of support, sorry.
- PLANET_URL and PLANET_MD5_URL should be a full path to the _file_ starting with scheme file://
- This fix should be merged https://github.com/organicmaps/organicmaps/pull/5200

**Comment by koenvanhollebeke** [comment]
OK, thanks for your time on this

**Comment by koenvanhollebeke** [comment]
maps_generator file input format solved
