### ISSUE TITLE
[android] Crash in Pedestrian and Car navigation

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5429]
This crash is from the [beta](https://github.com/organicmaps/organicmaps/tree/beta) branch. The user says it reproduces only on one of his devices (could it depend on the Android version or the screen size?).

**User confirms the crash in the landscape layout**

It looks like a release blocker. @arnaudvergnet @rtsisyk 

https://github.com/organicmaps/organicmaps/assets/170263/c5f43710-1b2f-4cd0-9e18-016006e0f864

Android version: 13 (API 33)
Device: samsung SM-P613 (gta4xlvewifi)
Supported ABIs: arm64-v8a armeabi-v7a armeabi
App version: app.organicmaps.beta 2023.06.26-11-Google-beta

```
07-02 08:18:57.562 E/AndroidRuntime(24915): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingBottomMenuController.showRoutingDetails(Unknown Source:84)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingBottomMenuController.showAltitudeChartAndRoutingDetails(Unknown Source:54)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingPlanController.updateProgressLabels(Unknown Source:62)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingPlanController.updateBuildProgress(Unknown Source:134)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.MwmActivity.updateBuildProgress(Unknown Source:20)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingController.updateProgress(Unknown Source:8)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingController.updatePlan(Unknown Source:0)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingController.processRoutingEvent(Unknown Source:86)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingController.l(Unknown Source:0)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.routing.RoutingController$1.onRoutingEvent(Unknown Source:106)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.MwmApplication.nativeProcessTask(Native Method)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0(Unknown Source:0)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.MwmApplication.a(Unknown Source:0)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at app.organicmaps.h0.run(Unknown Source:2)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at android.os.Handler.handleCallback(Handler.java:942)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at android.os.Looper.loopOnce(Looper.java:226)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at android.os.Looper.loop(Looper.java:313)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
07-02 08:18:57.562 E/AndroidRuntime(24915): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by biodranik** [comment]
The crash happens in the landscape layout.

**Comment by j13m126** [comment]
Could it be that this is already fixed with the latest beta release (2023-07-02-17-Google-beta)? I've tried it several times, it doesn't crash anymore. Neither car nor pedestrian navigation.

**Comment by biodranik** [comment]
Unlikely. Did you try it on a tablet? It may crash only on a tablet in landscape mode.

**Comment by j13m126** [comment]
Sure, same device, same route, same orientation.

**Comment by rtsisyk** [comment]
This is fixed already.
