### ISSUE TITLE
[android] android.os.RemoteException at com.android.server.job.JobServiceContext.assertCallerLocked

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#543]
```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:354)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.SecurityException: 
  at android.os.Parcel.createException (Parcel.java:1966)
  at android.os.Parcel.readException (Parcel.java:1934)
  at android.os.Parcel.readException (Parcel.java:1884)
  at android.app.job.IJobCallback$Stub$Proxy.completeWork (IJobCallback.java:222)
  at android.app.job.JobParameters.completeWork (JobParameters.java:267)
  at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete (JobIntentService.java:267)
  at androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:393)
  at androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:382)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
Caused by: android.os.RemoteException: 
  at com.android.server.job.JobServiceContext.assertCallerLocked (JobServiceContext.java:481)
  at com.android.server.job.JobServiceContext.doCompleteWork (JobServiceContext.java:382)
  at com.android.server.job.JobServiceContext$JobCallback.completeWork (JobServiceContext.java:165)
  at android.app.job.IJobCallback$Stub.onTransact (IJobCallback.java:101)
  at android.os.Binder.execTransact (Binder.java:739)
```

Samsung Galaxy Note10+
Android 9 (SDK 28)
21052106.aab

https://play.google.com/console/u/0/developers/8084273541548442467/app/4972992444534608608/vitals/crashes/03c65976/details?days=30

**Comment by rtsisyk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1525290

> Now writing in FileOutputStream on a background thread instead of the main thread.

**Comment by rtsisyk** [comment]
I double-checked that we don't write in FileOutputStream from the main thread. Found nothing. Let's wait for mor reports.

**Comment by paralytic123** [comment]
Hello, has this problem been solved? I am also experiencing this problem when using JobIntentService now, I don't know how to solve it

Remote stack trace: at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:487)
at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:365)
at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83) at android.os.Binder.execTransact(Binder.java:732)

**Comment by biodranik** [comment]
Are you speaking about Organic Maps? This issue has been fixed a long time ago.
