### ISSUE TITLE
[android] Properly notify users about permission denied GPX/KML import error

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5432]
Organic Maps does not have READ_EXTERNAL_STORAGE permission and can't read from other apps' folders. Users should be notified about these import issues and provided with a workaround.

```
I/BaseActivityDelegate( 7860): DownloadResourcesLegacyActivity: onCreate() activity: app.organicmaps.DownloadResourcesLegacyActivity@2d446d66
I/BaseActivityDelegate( 7860): DownloadResourcesLegacyActivity: onSafeCreate() activity: app.organicmaps.DownloadResourcesLegacyActivity@2d446d66
I/DownloadResourcesLegacyActivity( 7860): Incoming intent uri: Intent { act=android.intent.action.VIEW dat=file:///storage/emulated/0/Android/data/com.mendhak.gpslogger/files/20230402.gpx typ= flg=0x3000000 cmp=app.organicmaps.beta/app.organicmaps.SplashActivity (has extras) }
I/Timeline( 7860): Timeline: Activity_launch_request id:app.organicmaps.beta time:6682999
E/PersonaManagerService(  990): inState():  stateMachine is null !!
I/ActivityManager(  990): do not start freezing screen for locked container getKeyguardshowstate = false
W/BookmarkManager( 7860): Downloading bookmarks file file:///storage/emulated/0/Android/data/com.mendhak.gpslogger/files/20230402.gpx with file name 20230402.gpx
W/BookmarkManager( 7860): Failed to download bookmarks file from file:///storage/emulated/0/Android/data/com.mendhak.gpslogger/files/20230402.gpx
W/BookmarkManager( 7860): java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.mendhak.gpslogger/files/20230402.gpx: open failed: EACCES (Permission denied)
W/BookmarkManager( 7860): 	at libcore.io.IoBridge.open(IoBridge.java:456)
W/BookmarkManager( 7860): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
W/BookmarkManager( 7860): 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
W/BookmarkManager( 7860): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:648)
W/BookmarkManager( 7860): 	at app.organicmaps.util.StorageUtils.copyFile(SourceFile:2)
W/BookmarkManager( 7860): 	at app.organicmaps.bookmarks.data.BookmarkManager.importBookmarksFile(SourceFile)
W/BookmarkManager( 7860): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.lambda$process$0(SourceFile)
W/BookmarkManager( 7860): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.a(SourceFile)
W/BookmarkManager( 7860): 	at app.organicmaps.intent.b.run(SourceFile)
W/BookmarkManager( 7860): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/BookmarkManager( 7860): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/BookmarkManager( 7860): 	at java.lang.Thread.run(Thread.java:818)
W/BookmarkManager( 7860): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/BookmarkManager( 7860): 	at libcore.io.Posix.open(Native Method)
W/BookmarkManager( 7860): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/BookmarkManager( 7860): 	at libcore.io.IoBridge.open(IoBridge.java:442)

```

**Comment by abhinavs1920** [comment]
Can I work on this issue?

**Comment by Jean-BaptisteC** [comment]
Don't ask to work on issue, create PR if you want :)

**Comment by cyber-toad** [comment]
What should be displayed as a workaround? Notify user about lack of permission and suggest to move file somewhere? Do we know what folder works for sure?

**Comment by biodranik** [comment]
@cyber-toad this is a good question. We need to investigate possible workarounds for different Android versions and test them first. Downloads folder is also not accessible since Android 11 AFAIR.
Enabling READ_EXTERNAL_STORAGE permission is not a good option, as it gives app access to all other apps files. It would be great to find workarounds without it.

**Comment by abhinavs1920** [comment]
I have got a way to do this, whenever an app is saving the file then we can generate a script file with it too which can run itself to move the file to the downloads folder, so no need to access external storage.
