### ISSUE TITLE
[android][auto] IllegalArgumentException: displayDistance must be a positive value

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5758]
**App:** b0e9a8b6c2f5b6450939fd05227dae65df06a36a Wed Jul 12 21:48:53 2023 +0200 [android-auto] Fix bugs
**Phone:** Samsung S10, Android 12 from Samsung, Android Auto 10.1.633034-release (latest)
**Auto:** Desktop Head Unit, Version 2.0-mac-arm64, Build 2022-03-30-438482292 (latest)

Mocked GPS in the driving mode. Istanbul map, 2023-07-10.

```
 Process: app.organicmaps.debug, PID: 32713
 java.lang.IllegalArgumentException: displayDistance must be a positive value
        at androidx.car.app.model.Distance.create(Distance.java:126)
        at app.organicmaps.car.util.RoutingHelpers.createDistance(RoutingHelpers.java:39)
        at app.organicmaps.car.util.RoutingUtils.createTravelEstimate(RoutingUtils.java:115)
        at app.organicmaps.car.util.RoutingUtils.createTrip(RoutingUtils.java:71)
        at app.organicmaps.car.NavigationSession.updateTrip(NavigationSession.java:263)
        at app.organicmaps.car.NavigationSession.onCompassUpdated(NavigationSession.java:183)
        at app.organicmaps.location.LocationHelper.notifyCompassUpdated(LocationHelper.java:180)
        at app.organicmaps.location.SensorHelper.onSensorChanged(SensorHelper.java:66)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:982)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Reproducibility:** sometimes during navigation

**Steps to reproduce:**

1. [auto] Start a navigation to any destination
2. [auto] Just wait... It crashes periodically on the turns.

**Comment by rtsisyk** [comment]
Probably related:

```
 D LocationHelper: LocationHelper.java:572 attach(): activity = app.organicmaps.MwmActivity@9259cd2
 D LocationHelper: LocationHelper.java:401 addListener(): listener: app.organicmaps.MwmActivity@9259cd2 count was: 1
 E OMcore  : routing/turns_sound_settings.cpp:36 ComputeTurnDistanceM(): CHECK(IsValid())
--------- beginning of crash
 F libc    : /Users/roman/code/organicmaps/organicmaps/routing/turns_sound_settings.cpp:36: uint32_t routing::turns::sound::Settings::ComputeTu
rnDistanceM(double) const: assertion "false" failed
 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 31768 (ganicmaps.debug), pid 31768 (ganicmaps.debug)
```

**Comment by rtsisyk** [comment]
Probably related to https://github.com/organicmaps/organicmaps/issues/5766
