### ISSUE TITLE
[android][auto] IllegalArgumentException: All non-browsable rows must have a distance span attached to either its title or texts

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5764]
**App:** b0e9a8b6c2f5b6450939fd05227dae65df06a36a Wed Jul 12 21:48:53 2023 +0200 [android-auto] Fix bugs
**Phone:** Samsung S10, Android 12 from Samsung, Android Auto 10.1.633034-release (latest)
**Auto:** Desktop Head Unit, Version 2.0-mac-arm64, Build 2022-03-30-438482292 (latest)

Mocked GPS in the driving mode. Istanbul map, 2023-07-10, 40.954131, 29.093032.

```
 D OMcore  : search/processor.cpp:235 SetInputLocale(): New input locale: en_US locale code: 1
 D OMcore  : search/processor.cpp:242 SetQuery(): query: Gas isCategorial: 1
 D AndroidRuntime: Shutting down VM
--------- beginning of crash
 E AndroidRuntime: FATAL EXCEPTION: main
 E AndroidRuntime: Process: app.organicmaps.debug, PID: 28150
 E AndroidRuntime: java.lang.RuntimeException: java.lang.IllegalArgumentException: All non-browsable rows must have a distance span attached to
 either its title or texts
        at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:154)
        at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39)
        at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:146)
        at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:185)
        at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
 Caused by: java.lang.IllegalArgumentException: All non-browsable rows must have a distance span attached to either its title or texts
        at androidx.car.app.model.ModelUtils.validateAllNonBrowsableRowsHaveDistance(ModelUtils.java:65)
        at androidx.car.app.navigation.model.PlaceListNavigationTemplate$Builder.setItemList(PlaceListNavigationTemplate.java:407)
        at app.organicmaps.car.screens.search.SearchOnMapScreen.onGetTemplate(SearchOnMapScreen.java:59)
        at androidx.car.app.Screen.getTemplateWrapper(Screen.java:361)
        at androidx.car.app.ScreenManager.getTopTemplate(ScreenManager.java:279)
        at androidx.car.app.AppManager$1$$ExternalSyntheticLambda1.dispatch(Unknown Source:2)
        at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:149)
        ... 13 more
D OMcore  : search/geocoder.cpp:452 SetParamsForCategorialSearch(): QueryParams { m_tokens: [0: ], m_prefixToken: Token [ m_original=gas, m_sy
nonyms=[0: ] ], m_typeIndices: [1: [2: 66 1085 ] ], m_langs: SafeSmallSet<64> [5: 0 1 7 53 55 ], m_isCommonToken: [1: 0 ] }
```

**Steps to reproduce**:

1. [phone] Kill the app
2. [auto] Connect USB and start Organic Maps
3. [auto] Tap on Categories -> Gas

**Reproducibility**: it looks like that this issue reproduces 100% on any viewport.

**Comment by rtsisyk** [comment]
Search -> "?cids" -> "Map" icon also causes this crash.
