### ISSUE TITLE
fill-color: none; issue when regenerating styles

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#5807]
@pastk i tried to regenerate styles with drules after https://github.com/organicmaps/organicmaps/pull/5789 using `fill-color: none;`, but got this error:

```
Traceback (most recent call last):
  File "/home/harry/Documents/Git/organicmaps/tools/kothic/src/mapcss/__init__.py", line 327, in parse
    sc.addStyles(self.subst_variables(parseDeclaration(decl)))
  File "/home/harry/Documents/Git/organicmaps/tools/kothic/src/mapcss/StyleChooser.py", line 262, in addStyles
    ra = make_nice_style(ra)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/harry/Documents/Git/organicmaps/tools/kothic/src/mapcss/StyleChooser.py", line 40, in make_nice_style
    ra[a] = colorparser(b)
            ^^^^^^^^^^^^^^
  File "/home/harry/Documents/Git/organicmaps/tools/kothic/src/mapcss/webcolors/webcolors.py", line 870, in whatever_to_cairo
    return a[0] / 255., a[1] / 255., a[2] / 255.
           ~^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/Documents/Git/organicmaps/./tools/unix/../../tools/kothic/src/libkomwm.py", line 961, in <module>
    main()
  File "/home/harry/Documents/Git/organicmaps/./tools/unix/../../tools/kothic/src/libkomwm.py", line 951, in main
    komap_mapswithme(options)
  File "/home/harry/Documents/Git/organicmaps/./tools/unix/../../tools/kothic/src/libkomwm.py", line 542, in komap_mapswithme
    style.parse(clamp=False, stretch=LAYER_PRIORITY_RANGE,
  File "/home/harry/Documents/Git/organicmaps/tools/kothic/src/mapcss/__init__.py", line 381, in parse
    raise Exception(msg)
Exception: 'NoneType' object is not subscriptable
File: ./tools/unix/../../data/styles/clear/style-clear/../include/Basemap.mapcss
Line: 443

```

basemap.mapcss
```
439: area|z15-[amenity=parking][location=underground],
440: area|z15-16[amenity=parking][access=private],
441: area|z15-16[amenity=parking][parking=lane],
442: area|z15-16[amenity=parking][parking=street_side],
443: {fill-color: none;}
```

**Comment by pastk** [comment]
Sorry, I didn't test this case properly!
Here is the fix: https://github.com/organicmaps/kothic/pull/20

Once its merged you can add a `[tools] Update kothic (Fix fill-color: none; handling)` commit into your PR to update submodule commit hash.
