### ISSUE TITLE
[android] A crash when rotating the screen while showing an alert dialog

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5838]
**Steps to reproduce**

1. Clean data
2. Start making a route and wait until "When following the route, please keep in mind" disclaimer.
3. Rotate the screen

**Logs**
Log when I rotate the device:

```
android.view.WindowLeaked: Activity app.organicmaps.MwmActivity has leaked window DecorView@1a16723[MwmActivity] that was originally added here
         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1168)
         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1143)
         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:490)
         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
         at android.app.Dialog.show(Dialog.java:512)
         at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
         at app.organicmaps.MwmActivity.onShowDisclaimer(MwmActivity.java:1639)
         at app.organicmaps.routing.RoutingController.prepare(RoutingController.java:368)
         at app.organicmaps.routing.RoutingController.prepare(RoutingController.java:358)
         at app.organicmaps.routing.RoutingController.lambda$new$2$app-organicmaps-routing-RoutingController(RoutingControlle
r.java:167)
         at app.organicmaps.routing.RoutingController$$ExternalSyntheticLambda1.onRoutePointsLoaded(Unknown Source:2)
         at app.organicmaps.MwmApplication.nativeProcessTask(Native Method)
         at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0(MwmApplication.java:253)
         at app.organicmaps.MwmApplication$$ExternalSyntheticLambda0.run(Unknown Source:2)
         at android.os.Handler.handleCallback(Handler.java:938)
         at android.os.Handler.dispatchMessage(Handler.java:99)
         at android.os.Looper.loopOnce(Looper.java:226)
         at android.os.Looper.loop(Looper.java:313)
         at android.app.ActivityThread.main(ActivityThread.java:8751)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**System information:**

    Operating system and its version: Android 12
    Organic Maps version: 2023.08.26-21-Google-debug
    Device Model: Samsung S10

This is the same issue as in #4570, but for other AlertDialogs.

**Comment by Jean-BaptisteC** [comment]
I think it's caused by this refactoring #4987

**Comment by rtsisyk** [comment]
> I think it's caused by this refactoring #4987

Not really. #4987 just the same code from one place to another https://github.com/organicmaps/organicmaps/pull/4987/files#diff-2d45e93a03b35b116350b431fab3c252cb818e1ce59871c1729d5c61e9a3771bL334-L358.
 
The actual problem is caused by internal bug in Android. It looks like that all AlertDialogs created in Activties must be dismissed onPause(). AlertDialogs in Fragments work fine and even automatically re-created on rotation.
