### ISSUE TITLE
Crash when I started OM from AA

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5865]
**Steps to reproduce**
1. Be sure OM is close on phone
2. Launch AA Emulator
```
FATAL EXCEPTION: main
Process: app.organicmaps.debug, PID: 20512
java.lang.RuntimeException: java.lang.NullPointerException
at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:154)
at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:207)
at androidx.car.app.ScreenManager.getTop(ScreenManager.java:67)
at app.organicmaps.car.NavigationSession.onMyPositionModeChanged(NavigationSession.java:173)
at app.organicmaps.car.NavigationSession.onLocationPermissionsGranted(NavigationSession.java:167)
at app.organicmaps.car.NavigationSession.onCreateScreen(NavigationSession.java:103)
at androidx.car.app.CarAppBinder.lambda$onAppCreate$0$androidx-car-app-CarAppBinder(CarAppBinder.java:140)
at androidx.car.app.CarAppBinder$$ExternalSyntheticLambda1.dispatch(Unknown Source:8)
at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:149)
at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6) 
at android.os.Handler.handleCallback(Handler.java:942) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7918) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: APK Web debug from #5843
 - Device Model: Pixel 6 + AA Emulator

**Comment by Jean-BaptisteC** [comment]
Reset location permission fixed problem

**Comment by AndrewShkrob** [comment]
Have you verified this with the latest modifications in #5843? I recall that I addressed and resolved this problem previously.

**Comment by Jean-BaptisteC** [comment]
Problem is fixed
