### ISSUE TITLE
Storage issue

### ISSUE THREAD

**Issue by victorbnl** [organicmaps/organicmaps#630]
When I open the app it directly crashes with this error

```
Failed to ensure /storage/F4FD-0FF1/Android/data/app.organicmaps/files: android.os.ServiceSpecificException

time: 1624036016014
msg: java.lang.IllegalArgumentException: Failed to find storage device at null
stacktrace: java.lang.IllegalArgumentException: Failed to find storage device at null
	at android.os.Environment.isExternalStorageEmulated(Environment.java:1245)
	at com.mapswithme.maps.settings.StoragePathManager.updateExternalStorages(StoragePathManager.java:3)
	at com.mapswithme.maps.settings.StoragePathManager.findMapsStorage(StoragePathManager.java:1)
	at com.mapswithme.maps.MwmApplication.initNativePlatform(MwmApplication.java:5)
	at com.mapswithme.maps.MwmApplication.init(MwmApplication.java:1)
	at com.mapswithme.maps.SplashActivity.init(SplashActivity.java:2)
	at com.mapswithme.maps.SplashActivity.access$000(SplashActivity.java:1)
	at com.mapswithme.maps.SplashActivity$1.run(SplashActivity.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
https://del.dog/nughostall.txt

**Comment by victorbnl** [comment]
I had created a "Android" file at the root of my SD card which prevented the access to that folder, making the app crash
