### ISSUE TITLE
[ios] Fastlane: Malformed version number string ﻿﻿2023.11.17 (ArgumentError)

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6589]
Somebody from Ruby decided that we can't use 2023.11.17 as a version. 

```
Run `fastlane env` to append the fastlane environment to your issue
/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize': \e[31m[!] Malformed version number string 2023.11.17\e[0m (ArgumentError)
        from /opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/version.rb:206:in `new'
        from /opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/version.rb:206:in `new'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/models/app.rb:269:in `block in get_edit_app_store_versi
on'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/models/app.rb:269:in `each'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/models/app.rb:269:in `sort_by'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/models/app.rb:269:in `get_edit_app_store_version'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:432:in `block in fetch_edit_app_store_version'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:452:in `block in retry_if_nil'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:449:in `loop'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:449:in `retry_if_nil'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:431:in `fetch_edit_app_store_version'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:536:in `verify_available_version_languages!'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/upload_metadata.rb:91:in `upload'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/runner.rb:152:in `upload_metadata'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/runner.rb:61:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize': Malformed version number string 2023.11.17 (ArgumentError)
```

https://github.com/rubygems/rubygems/blob/d38522f62efb952ee3f47905dcfb24900d43d6fa/lib/rubygems/version.rb#L176

Go figure that they wanted to say in they regex:

https://github.com/rubygems/rubygems/blob/d38522f62efb952ee3f47905dcfb24900d43d6fa/lib/rubygems/version.rb#L158-L159

**Comment by rtsisyk** [comment]
https://github.com/fastlane/fastlane/issues/21647
