### ISSUE TITLE
[android] NullPointerException at app.organicmaps.MwmActivity.showStartPointNotice

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6628]
Xiaomi pine (Redmi 7A)
Android 10 (SDK 29)
Version: 23111718 (2023.11.17-18-Google)

```
Exception java.lang.NullPointerException:
  at java.util.Objects.requireNonNull (Objects.java:203)
  at app.organicmaps.MwmActivity.showStartPointNotice (MwmActivity.java:1680)
  at app.organicmaps.MwmActivity.onRoutingStart (MwmActivity.java:2055)
  at app.organicmaps.routing.RoutingBottomMenuController.lambda$setStartButton$0 (RoutingBottomMenuController.java:288)
  at android.view.View.performClick (View.java:7184)
  at android.view.View.performClickInternal (View.java:7161)
  at android.view.View.access$3500 (View.java:818)
  at android.view.View$PerformClick.run (View.java:27677)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

UI inconsistency bug uncovered by 921cb80a20c963f6d46490e6ad3012014488fd4c.
The route button was displayed without the start point selected.

https://github.com/organicmaps/organicmaps/blob/add2242230fae973d7d12e95e55edd98d256fdbf/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1670-L1677

https://github.com/organicmaps/organicmaps/blob/add2242230fae973d7d12e95e55edd98d256fdbf/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1341-L1379

Need to find a way how to reproduce this issue.

**Comment by biodranik** [comment]
How can you open the routing ui without selecting a start and/or end points?

**Comment by rtsisyk** [comment]
> How can you open the routing ui without selecting a start and/or end points?

It is possible to remove the point from the list after opening the UI. However, I always see "Add a {starting point,destination} to plan route" in this case.  I wish to know how to get the start button without start point...

**Comment by Jean-BaptisteC** [comment]
I'm able to reproduce :)

- Select POI -> route to
- Touch the back button at same time, you touch the start button

```
Process: app.organicmaps.debug, PID: 24222
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:207)
at app.organicmaps.MwmActivity.showStartPointNotice(MwmActivity.java:1667)
at app.organicmaps.MwmActivity.onRoutingStart(MwmActivity.java:2026)
at app.organicmaps.routing.RoutingBottomMenuController.lambda$setStartButton$0$app-organicmaps-routing-RoutingBottomMenuController(RoutingBottomMenuController.java:288)
at app.organicmaps.routing.RoutingBottomMenuController$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:7659)
at android.view.View.performClickInternal(View.java:7636)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30156)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
