### ISSUE TITLE
[android] app.organicmaps.dialog.EditTextDialogFragment.lambda$onCreateDialog$1

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6631]
**Steps to reproduce**
1. Start OM
2. Select POI on map and open editor
3. Select street field
4. Touch in same time Add street and back button -> crash

```
FATAL EXCEPTION: main
Process: app.organicmaps.beta, PID: 31720
java.lang.IllegalStateException: Fragment EditTextDialogFragment{5a65fb9} (138f478a-9007-4288-a8d2-4badb03366de) not attached to an activity.
at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1000)
at app.organicmaps.dialog.EditTextDialogFragment.lambda$onCreateDialog$1(EditTextDialogFragment.java:131)
at app.organicmaps.dialog.EditTextDialogFragment.$r8$lambda$EbM-pB_zorLh2KEuO_0_E72xTvA(EditTextDialogFragment.java:0)
at app.organicmaps.dialog.EditTextDialogFragment$$ExternalSyntheticLambda1.onShow(R8$$SyntheticClass:0)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1484)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.11.17-17-Google-beta
 - Device Model: Pixel 6

**Comment by rtsisyk** [comment]
Touching at the same time Add street and back button generates two events in the event loop - one to show EditTextDialogFragment and another is to close the activity. `editTextDialog.setOnShowListener((dialog) -> {` callback is called when activity has gone already.

It's not a regression. This code has been there for a very long time, since ea816b28cbb.
