### ISSUE TITLE
[android] Crash with java.lang.SecurityException on KML/KMZ import

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7149]
Looks like a permissions issue when a file is located in other app folders. There are 70 such crashes [in Google Play Console](https://play.google.com/console/u/0/developers/8084273541548442467/app/4972992444534608608/vitals/crashes/54c8e21d204536d601059ef661695c43/details?days=28&versionCode=24010906&isUserPerceived=true) in the latest binary for last 3 days.

```
01-10 05:58:00.415 W/BookmarkManager(21289): Downloading bookmarks file content://com.whatsapp.provider.media/item/a446db57-38a1-42b0-b1f2-062ef4098eef with file name a446db57-38a1-42b0-b1f2-062ef4098eef.kml
01-10 05:58:00.417 E/AndroidRuntime(21289): FATAL EXCEPTION: pool-3-thread-1
01-10 05:58:00.417 E/AndroidRuntime(21289): Process: app.organicmaps, PID: 21289
01-10 05:58:00.417 E/AndroidRuntime(21289): java.lang.SecurityException: Permission Denial: opening provider com.whatsapp.contentprovider.MediaProvider from ProcessRecord{cf04026 21289:app.organicmaps/u0a378} (pid=21289, uid=10378) that is not exported from UID 10370
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.os.Parcel.createException(Parcel.java:2358)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.os.Parcel.readException(Parcel.java:2341)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.os.Parcel.readException(Parcel.java:2283)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6080)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6996)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3114)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2494)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1980)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1811)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1488)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at app.organicmaps.util.StorageUtils.copyFile(StorageUtils.java:168)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at app.organicmaps.bookmarks.data.BookmarkManager.importBookmarksFile(BookmarkManager.java:485)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.lambda$process$0(Factory.java:58)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.$r8$lambda$gkCbNXZP0-WDUKlvqIXVT3IAfMc(Factory.java:0)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at app.organicmaps.intent.Factory$KmzKmlProcessor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-10 05:58:00.417 E/AndroidRuntime(21289): 	at java.lang.Thread.run(Thread.java:923)
```

```
01-10 05:43:51.472 E/AndroidRuntime( 8802): FATAL EXCEPTION: pool-4-thread-1
01-10 05:43:51.472 E/AndroidRuntime( 8802): Process: app.organicmaps, PID: 8802
01-10 05:43:51.472 E/AndroidRuntime( 8802): java.lang.SecurityException: Permission Denial: opening provider com.whatsapp.contentprovider.MediaProvider from ProcessRecord{f70ec4c 8802:app.organicmaps/u0a378} (pid=8802, uid=10378) that is not exported from UID 10370
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.os.Parcel.createException(Parcel.java:2358)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.os.Parcel.readException(Parcel.java:2341)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.os.Parcel.readException(Parcel.java:2283)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6080)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6996)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3114)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2494)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1980)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1811)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1488)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at app.organicmaps.util.StorageUtils.copyFile(StorageUtils.java:168)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at app.organicmaps.bookmarks.data.BookmarkManager.importBookmarksFile(BookmarkManager.java:485)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.lambda$process$0(Factory.java:58)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at app.organicmaps.intent.Factory$KmzKmlProcessor.$r8$lambda$gkCbNXZP0-WDUKlvqIXVT3IAfMc(Factory.java:0)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at app.organicmaps.intent.Factory$KmzKmlProcessor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-10 05:43:51.472 E/AndroidRuntime( 8802): 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by ststeiger** [comment]
Possibly related to Security Patch December 1 2023.

**Comment by biodranik** [comment]
Affected users 895 
Events 2.81K 

This is a CRITICAL issue.

@ststeiger what was done in that patch? Any details? Any similar issues in other apps? Any workarounds/fixes?

**Comment by biodranik** [comment]
@rtsisyk did you try to import any KML file from Telegram? Did it work for you?

**Comment by ststeiger** [comment]
@[biodranik](https://github.com/biodranik): 
Trying KML is the first thing i did after gpx didn't work. 
KML does not work either.
