### ISSUE TITLE
Unable to run generate_localizations.sh

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7510]
getting the error:
```
++ dirname /home/harry/Documents/Git/organicmaps/tools/unix/generate_localizations.sh
+ OMIM_PATH=/home/harry/Documents/Git/organicmaps/tools/unix/../..
+ case $OSTYPE in
++ which ruby
+ '[' '!' -x /usr/bin/ruby ']'
+ TWINE_SUBMODULE=tools/twine
+ TWINE_PATH=/home/harry/Documents/Git/organicmaps/tools/unix/../../tools/twine
+ GEM_PATH=/home/harry/Documents/Git/organicmaps/tools/unix/../../tools/twine/gem
+ '[' '!' -e /home/harry/Documents/Git/organicmaps/tools/unix/../../tools/twine/twine ']'
+ gem install twine --install-dir /home/harry/Documents/Git/organicmaps/tools/unix/../../tools/twine/gem
ERROR:  Use --install-dir or --user-install but not both
```

temporary workaround is to comment out line 35:
```gem install twine --install-dir $GEM_PATH```

gem version: 3.4.10

**Comment by biodranik** [comment]
@RedAuburn this "workaround" command disables the installation of a locally built gem, and (likely?) uses the unpatched twine gem installed from their official repo.

The proper fix should guarantee that only our locally built/patched version of twine is used. 

Does `gem list` print `twine` module installed?

**Comment by RedAuburn** [comment]
> @RedAuburn this "workaround" command disables the installation of a locally built gem, and (likely?) uses the unpatched twine gem installed from their official repo.
> 
> The proper fix should guarantee that only our locally built/patched version of twine is used.
> 
> Does `gem list` print `twine` module installed?

hmm, it does, but i can't uninstall it...

```
harry@fedora-framework:~/Documents/Git/organicmaps$ gem list| grep twine
twine (1.1.2)
harry@fedora-framework:~/Documents/Git/organicmaps$ gem uninstall twine
Remove executables:
	twine

in addition to the gem? [Yn]  y
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /home/harry/bin directory.
	/usr/share/rubygems/rubygems/uninstaller.rb:214:in `remove_executables'
	/usr/share/rubygems/rubygems/uninstaller.rb:164:in `uninstall_gem'
	/usr/share/rubygems/rubygems/uninstaller.rb:143:in `uninstall'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:198:in `uninstall'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:184:in `uninstall_gem'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:170:in `each'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
	/usr/share/rubygems/rubygems/commands/uninstall_command.rb:136:in `execute'
	/usr/share/rubygems/rubygems/command.rb:327:in `invoke_with_build_args'
	/usr/share/rubygems/rubygems/command_manager.rb:252:in `invoke_command'
	/usr/share/rubygems/rubygems/command_manager.rb:192:in `process_args'
	/usr/share/rubygems/rubygems/command_manager.rb:150:in `run'
	/usr/share/rubygems/rubygems/gem_runner.rb:51:in `run'
	/usr/bin/gem:10:in `<main>'
harry@fedora-framework:~/Documents/Git/organicmaps$ sudo gem uninstall twine
Gem 'twine' is not installed

```

**Comment by RedAuburn** [comment]
managed to uninstall it, so no result in gem list, but still getting the same error

**Comment by dvdmrtnz** [comment]
I don't know why but after some time, twine just seems to stop working fine and trying  to run `./tools/unix/generate_localizations.sh` complains with this error:

```
++ gem contents --show-install-dir twine
+ TWINE='Unable to find gem '\''twine'\'' in default gem paths

Directories searched:/bin/twine'
```

I am leaving this message for future me and other developers that run into this problem and don't know what to do. It seems to get fixed by running:

```
rm tools/twine/*.gem
```

**Comment by biodranik** [comment]
@dvdmrtnz is it Mac OS or Linux? The directory /bin/twine looks invalid...

**Comment by dvdmrtnz** [comment]
MacOS

**Comment by biodranik** [comment]
There could be an issue with your ruby homebrew installation. The issue is present when instead of homebrew's ruby there is a system ruby in path:
```
➜  omim git:(master) PATH="${HOMEBREW_PREFIX:-/opt/homebrew}/opt/ruby/bin:$PATH" gem contents --show-install-dir twine 
/Users/alex/.gem/ruby/3.3.0/gems/twine-1.1.2.pre.om
➜  omim git:(master) gem contents --show-install-dir twine                                                       
Unable to find gem 'twine' in default gem paths

Directories searched:

```

**Comment by willcohen** [comment]
In my case, I needed to rerun `git submodule update --init --recursive` to get past this.
