### ISSUE TITLE
Can't configure driving options

### ISSUE THREAD

**Issue by kslcsdalsadg** [organicmaps/organicmaps#7514]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
A FC is issued when clicking app settings -> Driving options

**Steps to reproduce**
1. Go to App Settings
2. Click on Driving options
3. Main app activity is displayed and and error is displayed at logcat

**Expected behaviour**
Driving Options activity is displayed

**System information:**
 - Operating system and its version: Android 14, GrapheneOS
 - Organic Maps version: 2024.02.06-11-android
 - Device Model: Pixel 7 Pro

**Additional context**

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240205.002/2024030300:user/release-keys
package: app.organicmaps.web:24021202
process: app.organicmaps.web
processUptime: 72567 + 217 ms
installer: com.android.packageinstaller

android.content.ActivityNotFoundException: Unable to find explicit activity class {app.organicmaps/app.organicmaps.settings.DrivingOptionsActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2247)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1884)
	at android.app.Activity.startActivityForResult(Activity.java:5661)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
	at android.app.Activity.startActivityForResult(Activity.java:5581)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
	at android.app.Activity.startActivity(Activity.java:6124)
	at android.app.Activity.startActivity(Activity.java:6091)
	at androidx.preference.Preference.performClick(Preference.java:1215)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7658)
	at android.view.View.performClickInternal(View.java:7635)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30167)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359) 
```

**Comment by kslcsdalsadg** [comment]
Also tried in a Xiaomi Redmi Note 9 Pro with MIUI then the issue persist

**Comment by Jean-BaptisteC** [comment]
@rtsisyk can you check?
I think it's caused because handle is different for web version.

**Comment by kslcsdalsadg** [comment]
> @rtsisyk can you check? I think it's caused because handle is different for web version.
> 
> https://github.com/organicmaps/organicmaps/blob/a037a5a53328036d8a18a1ffb17aa62b3f7efaf8/android/app/src/main/res/xml/prefs_main.xml#L130
> 
> 
> @kslcsdalsadg can you try also to open TTS settings?

TTS settings works well

**Comment by kslcsdalsadg** [comment]
I think is caused by the intent you use at prefs_main.xml to open the driving settings.
you use android:targetClass="app.organicmaps.settings.DrivingOptionsActivity" but the target class will be "app.organicmaps.web.settings.DrivingOptionsActivity" in the app that is linked at github releases page.

```
<PreferenceScreen
      android:key="@string/prefs_routing"
      android:order="5"
      android:title="@string/driving_options_title">
      <intent
        android:targetClass="app.organicmaps.settings.DrivingOptionsActivity"
        android:targetPackage="@string/app_id">
        <extra android:name="from" android:value="settings" />
      </intent>
```

**Comment by biodranik** [comment]
This crash was already fixed by https://github.com/organicmaps/organicmaps/pull/7394
