### ISSUE TITLE
[android] j$.time.DateTimeException: Invalid value for SecondOfMinute (valid values 0 - 59): 60

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#7704]
```
j$.time.DateTimeException: Invalid value for SecondOfMinute (valid values 0 - 59): 60

     FATAL EXCEPTION: main
Process: app.organicmaps.beta, PID: 31473
j$.time.DateTimeException: Invalid value for SecondOfMinute (valid values 0 - 59): 60
	at j$.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at j$.time.temporal.ChronoField.checkValidValue(ChronoField.java:713)
	at j$.time.LocalTime.withSecond(LocalTime.java:929)
	at app.organicmaps.routing.RoutingController.formatArrivalTime(RoutingController.java:921)
	at app.organicmaps.routing.RoutingBottomMenuController.showRoutingDetails(RoutingBottomMenuController.java:377)
	at app.organicmaps.routing.RoutingBottomMenuController.showAltitudeChartAndRoutingDetails(RoutingBottomMenuController.java:162)
	at app.organicmaps.routing.RoutingPlanController.updateProgressLabels(RoutingPlanController.java:214)
	at app.organicmaps.routing.RoutingPlanController.updateBuildProgress(RoutingPlanController.java:257)
	at app.organicmaps.MwmActivity.updateBuildProgress(MwmActivity.java:1472)
	at app.organicmaps.routing.RoutingController.updateProgress(RoutingController.java:229)
	at app.organicmaps.routing.RoutingController.updatePlan(RoutingController.java:464)
	at app.organicmaps.routing.RoutingController.processRoutingEvent(RoutingController.java:175)
	at app.organicmaps.routing.RoutingController.-$$Nest$mprocessRoutingEvent(RoutingController.java:0)
	at app.organicmaps.routing.RoutingController$1.onRoutingEvent(RoutingController.java:124)
	at app.organicmaps.MwmApplication.nativeProcessTask(Native Method)
	at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0(MwmApplication.java:277)
	at app.organicmaps.MwmApplication.$r8$lambda$0EkodVMt2eEYEGuNfwibPGIm4z4(MwmApplication.java:0)
	at app.organicmaps.MwmApplication$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

Brand:Google
Model:Pixel Tablet
Orientation:Landscape
RAM free: 2.99 GB
Disk free: 104.87 GB
Operating system
Version:Android 13
Orientation:Landscape
Rooted:No
Date:27 Mar 2024, 09:02:48
App version:2024.03.27-1-Google-beta (24032701)

[video](https://github.com/organicmaps/organicmaps/assets/1799054/fafa8cd9-4041-4500-8f5e-98ae9c3dfecd)
[logcat.log](https://github.com/organicmaps/organicmaps/files/14769631/2024-03-27_06.52.21.140062_zsiD_tangorpro-33-en-landscape_logcat.log)

CC:  @Isira-Seneviratne

**Comment by biodranik** [comment]
Where 60 minutes come from?
