### ISSUE TITLE
[android-auto] androidx.car.app.HostException: Remote setSurfaceListener call failed

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#8106]
Brand:Google
Model:Pixel 6
Orientation:Portrait
RAM free: 2.03 GB
Disk free: 74.76 GB
Version:Android 14
Orientation:Portrait
Rooted:No
Crash
Date:5 May 2024, 19:19:53
App version:2024.05.04-8-Google-beta (24050408)

```
Fatal Exception: java.lang.RuntimeException: androidx.car.app.HostException: Remote setSurfaceListener call failed
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:153)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 ```
  
```
Caused by androidx.car.app.HostException: Remote getHost(App) call failed
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:91)
       at androidx.car.app.HostDispatcher.getHost(HostDispatcher.java:152)
       at androidx.car.app.HostDispatcher.lambda$dispatch$1(HostDispatcher.java:102)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:85)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHost(RemoteUtils.java:104)
       at androidx.car.app.HostDispatcher.dispatch(HostDispatcher.java:101)
       at androidx.car.app.AppManager.setSurfaceCallback(AppManager.java:96)
       at app.organicmaps.car.SurfaceRenderer.onCreate(SurfaceRenderer.java:107)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
       at androidx.car.app.Session$LifecycleObserverImpl.onCreate(Session.java:250)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
       at androidx.car.app.Session.handleLifecycleEvent(Session.java:187)
       at androidx.car.app.CarAppBinder.lambda$onAppCreate$0(CarAppBinder.java:138)
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:148)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
  ```
  
```
  Caused by java.lang.IllegalStateException: Accessed the car host after it became invalidated
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3190)
       at android.os.Parcel.createException(Parcel.java:3166)
       at android.os.Parcel.readException(Parcel.java:3149)
       at android.os.Parcel.readException(Parcel.java:3091)
       at androidx.car.app.ICarHost$Stub$Proxy.getHost(ICarHost.java:148)
       at androidx.car.app.HostDispatcher.lambda$getHost$2(HostDispatcher.java:153)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:85)
       at androidx.car.app.HostDispatcher.getHost(HostDispatcher.java:152)
       at androidx.car.app.HostDispatcher.lambda$dispatch$1(HostDispatcher.java:102)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:85)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHost(RemoteUtils.java:104)
       at androidx.car.app.HostDispatcher.dispatch(HostDispatcher.java:101)
       at androidx.car.app.AppManager.setSurfaceCallback(AppManager.java:96)
       at app.organicmaps.car.SurfaceRenderer.onCreate(SurfaceRenderer.java:107)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
       at androidx.car.app.Session$LifecycleObserverImpl.onCreate(Session.java:250)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
       at androidx.car.app.Session.handleLifecycleEvent(Session.java:187)
       at androidx.car.app.CarAppBinder.lambda$onAppCreate$0(CarAppBinder.java:138)
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:148)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
   ```

**Comment by AndrewShkrob** [comment]
@rtsisyk If there is only one crash, then it may not be our responsibility. However, if there are many crashes, we may have a bug on our side.

**Comment by AndrewShkrob** [comment]
https://issuetracker.google.com/issues/340578711

**Comment by AndrewShkrob** [comment]
Should already been fixed:

> Thank you for verifying it works for you! Closing out this bug. Please feel free to re-open or create a new one if you run into any follow-up issues.

https://issuetracker.google.com/issues/340578711
