### ISSUE TITLE
[android] ArrayIndexOutOfBoundsException on PlacePageLinksFragment.refreshLinks()

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#8107]
Brand:Motorola
Model:Moto G4 Play
Orientation:Portrait
RAM free: 1008.74 MB
Disk free: 9.05 GB
Operating system
Version:Android 6.0.1
Orientation:Portrait
Rooted:No
Date:4 May 2024, 23:09:41
App version:2024.05.04-10-Google-beta (24050410)

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=16; index=524289
       at j$.time.Instant.plus(Instant.java:852)
       at app.organicmaps.bookmarks.data.MapObject.getKayakUrl(MapObject.java:293)
       at app.organicmaps.widget.placepage.sections.PlacePageLinksFragment.refreshLinks(PlacePageLinksFragment.java:196)
       at app.organicmaps.widget.placepage.sections.PlacePageLinksFragment.onChanged(PlacePageLinksFragment.java:243)
       at app.organicmaps.widget.placepage.sections.PlacePageLinksFragment.onChanged(PlacePageLinksFragment.java:32)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
       at androidx.lifecycle.LiveData.observe(LiveData.java:205)
       at app.organicmaps.widget.placepage.sections.PlacePageLinksFragment.onStart(PlacePageLinksFragment.java:227)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3187)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3196)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3202)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:646)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:296)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2966)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:333)
       at app.organicmaps.MwmActivity.onResumeFragments(MwmActivity.java:1083)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:322)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:245)
       at app.organicmaps.base.BaseMwmFragmentActivity.onPostResume(BaseMwmFragmentActivity.java:123)
       at android.app.Activity.performResume(Activity.java:6359)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3113)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
       at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
       at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
       at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
       at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Tap.java)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:23)
       at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(ViewInteraction.java)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
  ```

**Comment by vng** [comment]
Hm, again looks like R8 issues ..
What is wrong here?
```
final long lastDaySec = firstDay.plus(1, ChronoUnit.DAYS).getEpochSecond();
```
What kind of ```ArrayIndexOutOfBoundsException``` possible?

**Comment by biodranik** [comment]
It's unlikely an R8 issue, because Java Instant class support on older devices comes from [desugaring](https://developer.android.com/studio/write/java8-support-table).

[Here a similar issue was reported](https://stackoverflow.com/a/51122167) as a bug in Android 6 runtime, disabling Instant Run helped. I wonder if Instant Run is enabled on our Monkey @rtsisyk ?
