### ISSUE TITLE
[android] Allow users to share bug reports without requiring an email client

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#8287]
The only way to get any meaningful logs from Production/Beta versions is to use "Enable loggin" + "Report a bug" (see https://github.com/organicmaps/organicmaps/issues/5943 and https://github.com/organicmaps/organicmaps/issues/5942). Unfortunately, The "Report a Bug" button requires email client:

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND dat=content://app.organicmaps.beta.provider/... typ=message/r
fc822 flg=0x1 clip={message/rfc822 {T(0) U(content)}} (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2363)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1949)
        at android.app.Activity.startActivityForResult(Activity.java:5743)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
        at android.app.Activity.startActivityForResult(Activity.java:5701)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
        at android.app.Activity.startActivity(Activity.java:6199)
        at android.app.Activity.startActivity(Activity.java:6166)
        at app.organicmaps.util.Utils$SupportInfoWithLogsCallback.lambda$onCompleted$0(Utils.java:720)
        at app.organicmaps.util.Utils$SupportInfoWithLogsCallback.$r8$lambda$yus6t_DtUR4gaTG9XX9O_dpy8RI(Utils.java:0)
        at app.organicmaps.util.Utils$SupportInfoWithLogsCallback$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
        at android.os.Handler.handleCallback(Handler.java:959)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

It would be nice to have an an option to save report as file to file system. 

Workaround:

```
adb pull /storage/emulated/0/Android/data/app.organicmaps.beta/files/logs/app.log .
```

**Comment by biodranik** [comment]
@rtsisyk can this exception be handled, and the system "Save file" dialog is displayed instead of "share" dialog?

**Comment by krozhdestvenski** [comment]
This issue will be easy to do after merging of the https://github.com/organicmaps/organicmaps/issues/8306.

**Comment by krozhdestvenski** [comment]
> > This issue will be easy to do after merging of #8306.
> 
> Could you please try to play with the Intent used by "Report a Bug" button?  

Almost done. PR will be soon)

**Comment by biodranik** [comment]
@rtsisyk a try-catch + toast about with the (untranslated) details is better than a crash. Is it hard to fix?
