### ISSUE TITLE
Segmentation fault when using Nvidia on Fedora (native only, not Flatpak)

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8341]
**Describe the issue**
trying to run the desktop app after building it results in a segmentation fault

**Steps to reproduce**
1. use fedora system with an Nvidia graphics card (drivers at 550)
2. build OM, try to launch with ./OMaps

**System information:**
 - Operating system and its version: Fedora 40, Nvidia 1080ti (550 proprietary drivers)
 - Organic Maps version: master

gdb log:
```
I(1) 1.01261 qt_common/map_widget.cpp:351 initializeGL(): OpenGL version is at least 3.0, enabling GLSL '#version 300 es'
[New Thread 0x7fff9f4006c0 (LWP 7918)]
[New Thread 0x7fff9ea006c0 (LWP 7919)]
[New Thread 0x7fff9e0006c0 (LWP 7920)]
[New Thread 0x7fff9d6006c0 (LWP 7921)]
[New Thread 0x7fff9cc006c0 (LWP 7922)]
I(1) 1.01308 drape_frontend/visual_params.cpp:52 Init(): Visual scale = 1 ; Tile size = 1024 ; Resources = mdpi
[New Thread 0x7fff93e006c0 (LWP 7923)]
[New Thread 0x7fff934006c0 (LWP 7924)]
[New Thread 0x7fff92a006c0 (LWP 7925)]
I(3) 1.01327 drape_frontend/backend_renderer.cpp:724 Do(): Start routine.
I(3) 1.01329 drape_frontend/backend_renderer.cpp:692 OnContextCreate(): On context create.
[New Thread 0x7fff920006c0 (LWP 7926)]
I(4) 1.01357 drape_frontend/frontend_renderer.cpp:2401 Do(): Start routine.
I(4) 1.01360 drape_frontend/frontend_renderer.cpp:2318 OnContextCreate(): On context create.
[New Thread 0x7fff86a006c0 (LWP 7930)]
[New Thread 0x7fff860006c0 (LWP 7931)]
[New Thread 0x7fff856006c0 (LWP 7932)]
[New Thread 0x7fff84c006c0 (LWP 7933)]
I(3) 1.04072 drape/support_manager.cpp:33 Init(): Renderer = NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 | Api = OpenGLES3 | Version = OpenGL ES 3.2 NVIDIA 550.78
I(3) 1.04073 drape/support_manager.cpp:77 Init(): Max line width = 10 | Max texture size = 32768
[New Thread 0x7fff7be006c0 (LWP 7934)]
[New Thread 0x7fff7b4006c0 (LWP 7935)]
[New Thread 0x7fff7aa006c0 (LWP 7936)]
I(3) 1.04106 platform/platform.cpp:215 GetFontNames(): Available font files: [10: 00_NotoNaskhArabic-Regular.ttf 00_NotoSansThai-Regular.ttf 00_NotoSerifDevanagari-Regular.ttf 01_dejavusans.ttf 02_droidsans-fallback.ttf 03_jomolhari-id-a3d.ttf 04_padauk.ttf 05_khmeros.ttf 06_code2000.ttf 07_roboto_medium.ttf ]
[New Thread 0x7fff7a0006c0 (LWP 7937)]
[New Thread 0x7fff796006c0 (LWP 7938)]
I(4) 1.04122 shaders/program_manager.cpp:68 InitForOpenGL(): VTF enabled
                                                                                                                                                                            
Thread 1 "OMaps" received signal SIGSEGV, Segmentation fault.
0x0000000040159c41 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install xorg-x11-drv-nvidia-libs-550.78-1.fc40.x86_64

```

**Comment by biodranik** [comment]
@RedAuburn is it a debug build? Can you please run a binary under the gdb and get a backtrace using bt command?

**Comment by RedAuburn** [comment]
log + backtrace:

```
I(1) 0.95931 qt_common/map_widget.cpp:351 initializeGL(): OpenGL version is at least 3.0, enabling GLSL '#version 300 es'
[New Thread 0x7fff9f4006c0 (LWP 5557)]
[New Thread 0x7fff9ea006c0 (LWP 5558)]
[New Thread 0x7fff9e0006c0 (LWP 5559)]
[New Thread 0x7fff9d6006c0 (LWP 5560)]
[New Thread 0x7fff9cc006c0 (LWP 5561)]
I(1) 0.95972 drape_frontend/visual_params.cpp:52 Init(): Visual scale = 1 ; Tile size = 1024 ; Resources = mdpi
[New Thread 0x7fff93e006c0 (LWP 5562)]
[New Thread 0x7fff934006c0 (LWP 5563)]
[New Thread 0x7fff92a006c0 (LWP 5564)]
I(3) 0.95988 drape_frontend/backend_renderer.cpp:724 Do(): Start routine.
I(3) 0.95990 drape_frontend/backend_renderer.cpp:692 OnContextCreate(): On context create.
[New Thread 0x7fff920006c0 (LWP 5565)]
I(4) 0.96016 drape_frontend/frontend_renderer.cpp:2401 Do(): Start routine.
I(4) 0.96019 drape_frontend/frontend_renderer.cpp:2318 OnContextCreate(): On context create.
[New Thread 0x7fff86a006c0 (LWP 5569)]
[New Thread 0x7fff860006c0 (LWP 5570)]
[New Thread 0x7fff856006c0 (LWP 5571)]
[New Thread 0x7fff84c006c0 (LWP 5572)]
I(3) 0.99114 drape/support_manager.cpp:33 Init(): Renderer = NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 | Api = OpenGLES3 | Version = OpenGL ES 3.2 NVIDIA 550.78
[New Thread 0x7fff7be006c0 (LWP 5573)]
I(3) 0.99116 drape/support_manager.cpp:77 Init(): Max line width = 10 | Max texture size = 32768
[New Thread 0x7fff7b4006c0 (LWP 5574)]
[New Thread 0x7fff7aa006c0 (LWP 5575)]
I(3) 0.99147 platform/platform.cpp:215 GetFontNames(): Available font files: [10: 00_NotoNaskhArabic-Regular.ttf 00_NotoSansThai-Regular.ttf 00_NotoSerifDevanagari-Regular.ttf 01_dejavusans.ttf 02_droidsans-fallback.ttf 03_jomolhari-id-a3d.ttf 04_padauk.ttf 05_khmeros.ttf 06_code2000.ttf 07_roboto_medium.ttf ]
[New Thread 0x7fff7a0006c0 (LWP 5576)]
[New Thread 0x7fff796006c0 (LWP 5577)]
I(4) 0.99177 shaders/program_manager.cpp:68 InitForOpenGL(): VTF enabled
                                                                                                                                                                                                  
Thread 1 "OMaps" received signal SIGSEGV, Segmentation fault.
0x0000000040159d41 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install xorg-x11-drv-nvidia-libs-550.78-1.fc40.x86_64
(gdb) bt
#0  0x0000000040159d41 in ??? ()
#1  0x00007fffc277e4d7 in ??? () at /lib64/libnvidia-eglcore.so.550.78
#2  0x00007fffc2429cd3 in ??? () at /lib64/libnvidia-eglcore.so.550.78
#3  0x0000000000718d8f in qt::common::MapWidget::paintGL() ()
#4  0x00007ffff7a2d325 in QOpenGLWidgetPrivate::render (this=0x150f260) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/openglwidgets/qopenglwidget.cpp:977
#5  0x00007ffff6debf90 in QWidget::event (this=0x38646b0, event=0x7fffffffa1f0) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidget.cpp:9402
#6  0x00007ffff6d8b168 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x38646b0, e=0x7fffffffa1f0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3287
#7  0x00007ffff5b95b18 in QCoreApplication::notifyInternal2 (receiver=0x38646b0, event=0x7fffffffa1f0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1134
#8  0x00007ffff5b95d8d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1589
#9  0x00007ffff6de27fc in QWidgetPrivate::sendPaintEvent (this=this@entry=0x150f260, toBePainted=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidget.cpp:5647
#10 0x00007ffff7a2cb97 in QOpenGLWidget::resizeEvent (this=<optimized out>, e=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/openglwidgets/qopenglwidget.cpp:1513
#11 0x00007ffff6dec7aa in QWidget::event (this=0x38646b0, event=0x7fffffffa4d0) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidget.cpp:9192
#12 0x00007ffff6d8b168 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x38646b0, e=0x7fffffffa4d0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3287
#13 0x00007ffff5b95b18 in QCoreApplication::notifyInternal2 (receiver=0x38646b0, event=0x7fffffffa4d0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1134
#14 0x00007ffff5b95d7d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1575
#15 0x00007ffff6de1326 in QWidgetPrivate::setGeometry_sys (this=this@entry=0x150f260, x=0, y=23, w=3380, h=<optimized out>, isMove=<optimized out>, isMove@entry=true)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidget.cpp:7411
#16 0x00007ffff6de22f6 in QWidget::setGeometry (this=0x38646b0, r=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidget.cpp:7299
#17 0x00007ffff6dee722 in QWidget::qt_metacall (this=this@entry=0x38646b0, _c=_c@entry=QMetaObject::WriteProperty, _id=3, _a=_a@entry=0x7fffffffa6a0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/redhat-linux-build/src/widgets/Widgets_autogen/include/moc_qwidget.cpp:723
#18 0x00007ffff7a2e04e in QOpenGLWidget::qt_metacall (this=0x38646b0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffffffa6a0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/redhat-linux-build/src/openglwidgets/OpenGLWidgets_autogen/include/moc_qopenglwidget.cpp:180
#19 0x000000000071c145 in qt::common::MapWidget::qt_metacall(QMetaObject::Call, int, void**) ()
#20 0x000000000051c4a5 in qt::DrawWidget::qt_metacall(QMetaObject::Call, int, void**) ()
#21 0x00007ffff5d3345a in QPropertyAnimationPrivate::updateProperty (this=<optimized out>, newValue=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qpropertyanimation.cpp:105
#22 QPropertyAnimationPrivate::updateProperty (this=0x3eedfd0, newValue=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qpropertyanimation.cpp:91
#23 QPropertyAnimation::updateCurrentValue (this=<optimized out>, value=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qpropertyanimation.cpp:237
#24 0x00007ffff5d3cbb0 in QVariantAnimationPrivate::setCurrentValueForProgress (this=0x3eedfd0, progress=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qvariantanimation.cpp:253
#25 0x00007ffff5d3d4db in QVariantAnimationPrivate::recalculateCurrentInterval (this=<optimized out>, force=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qvariantanimation.cpp:236
#26 0x00007ffff5d3d96e in QVariantAnimationPrivate::setDefaultStartEndValue (this=<optimized out>, value=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qvariantanimation.cpp:301
#27 0x00007ffff5d35a3d in QPropertyAnimation::updateState (this=<optimized out>, newState=<optimized out>, oldState=QAbstractAnimation::Stopped)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qpropertyanimation.cpp:284
#28 0x00007ffff5d2b11a in QAbstractAnimationPrivate::setState (this=0x3eedfd0, newState=QAbstractAnimation::Running)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qabstractanimation.cpp:943
#29 0x00007ffff5d2b431 in QAbstractAnimation::start (this=<optimized out>, policy=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/animation/qabstractanimation.cpp:1385
#30 0x00007ffff6e8860d in QWidgetAnimator::animate (this=this@entry=0x38f96e0, widget=<optimized out>, _final_geometry=..., animate=animate@entry=false)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qwidgetanimator.cpp:78
#31 0x00007ffff6f04dc0 in QDockAreaLayout::apply (this=0x38f90f0, animate=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qdockarealayout.cpp:3239
#32 0x00007ffff6f4ccf2 in QMainWindowLayoutState::apply (this=0x38f8fd8, animated=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qmainwindowlayout.cpp:845
#33 QMainWindowLayout::applyState (this=this@entry=0x38f8f50, newState=..., animate=animate@entry=false)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qmainwindowlayout.cpp:3179
#34 0x00007ffff6f521e3 in QMainWindowLayout::applyState (this=0x38f8f50, newState=..., animate=false)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qmainwindowlayout.cpp:3146
#35 QMainWindowLayout::setGeometry (this=0x38f8f50, _r=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/widgets/qmainwindowlayout.cpp:2309
#36 0x00007ffff6dbff59 in QLayoutPrivate::doResize (this=0x37c6550) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qlayout.cpp:506
#37 0x00007ffff6dc172f in QLayout::widgetEvent (this=<optimized out>, e=e@entry=0x7fffffffaec0) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qlayout.cpp:530
#38 0x00007ffff6d8b14d in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x7fffffffb570, e=0x7fffffffaec0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3276
#39 0x00007ffff5b95b18 in QCoreApplication::notifyInternal2 (receiver=0x7fffffffb570, event=0x7fffffffaec0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1134
#40 0x00007ffff5b95b5a in QCoreApplication::forwardEvent (receiver=<optimized out>, event=<optimized out>, originatingEvent=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1149
#41 0x00007ffff6dff1a6 in QWidgetWindow::handleResizeEvent (this=0x36436e0, event=event@entry=0x7fffffffaec0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidgetwindow.cpp:816
#42 0x00007ffff6e02cd9 in QWidgetWindow::event (this=0x36436e0, event=0x7fffffffaec0) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qwidgetwindow.cpp:285
#43 0x00007ffff6d8b168 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x36436e0, e=0x7fffffffaec0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3287
#44 0x00007ffff5b95b18 in QCoreApplication::notifyInternal2 (receiver=0x36436e0, event=0x7fffffffaec0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1134
#45 0x00007ffff5b95d8d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1589
#46 0x00007ffff63e2528 in QGuiApplicationPrivate::processGeometryChangeEvent (e=<optimized out>) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/gui/kernel/qguiapplication.cpp:2711
#47 0x00007ffff644952c in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/gui/kernel/qwindowsysteminterface.cpp:1114
#48 0x00007ffff6449740 in QWindowSystemInterface::flushWindowSystemEvents (flags=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/gui/kernel/qwindowsysteminterface.cpp:1083
#49 0x00007ffff5bebdeb in QObject::event (this=0x1525ff0, e=0x42a5110) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qobject.cpp:1452
#50 0x00007ffff6d8b168 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x1525ff0, e=0x42a5110)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3287
#51 0x00007ffff5b95b18 in QCoreApplication::notifyInternal2 (receiver=0x1525ff0, event=0x42a5110) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1134
#52 0x00007ffff5b95d7d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1575
#53 0x00007ffff5b998c1 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x1402ae0)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1932
#54 0x00007ffff5b99b6d in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1789
#55 0x00007ffff5e7d39f in postEventSourceDispatch (s=0x1404810) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:244
#56 0x00007ffff350f6ac in g_main_dispatch (context=0x7fffdc000f00) at ../glib/gmain.c:3344
#57 g_main_context_dispatch_unlocked (context=0x7fffdc000f00) at ../glib/gmain.c:4152
#58 0x00007ffff3570708 in g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffdc000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4217
#59 0x00007ffff3510b23 in g_main_context_iteration (context=0x7fffdc000f00, may_block=1) at ../glib/gmain.c:4282
#60 0x00007ffff5e7cb53 in QEventDispatcherGlib::processEvents (this=0x1403b60, flags=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:394
#61 0x00007ffff5ba2713 in QEventLoop::exec (this=this@entry=0x7fffffffb440, flags=..., flags@entry=...) at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/global/qflags.h:34
#62 0x00007ffff5b9e69c in QCoreApplication::exec () at /usr/src/debug/qt6-qtbase-6.7.1-2.fc40.x86_64/src/corelib/global/qflags.h:74
#63 0x00000000004d8bde in main ()

```

**Comment by biodranik** [comment]
Thanks! Does it crash on an older Qt version?

**Comment by RedAuburn** [comment]
tested on qt 6.6.2, it's working! i guess it's an upstream bug?

**Comment by biodranik** [comment]
It could be, as we discovered, there is a black screen on the Mac too with Qt 6.7 #7838 . It would be great to report them.

**Comment by RedAuburn** [comment]
> It could be, as we discovered, there is a black screen on the Mac too with Qt 6.7 #7838 . It would be great to report them.

yup i also get black screen when not using an Nvidia gpu. will try to figure out how to report 👍️

**Comment by RedAuburn** [comment]
closing as not reproduceable
