### ISSUE TITLE
Wrong changeset number

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#8705]
**Steps to reproduce**
1. Open app go to settings -> profile
2. Allow app access to internet
3. Close app and turn off wifi and data
4. Open app go to settings -> profile
5. Number of changeset is -1

**Expected behaviour**
If we don't have internet at the first time, value is 0
If we don't have internet but we have already number of changeset, do not refresh the value

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: [2024.07.14-3-FDroid-beta](https://github.com/organicmaps/organicmaps/pull/8701)
 - Device Model: Pixel 6

**Comment by RedAuburn** [comment]
thanks, can you re-test with a new build? should be fixed now :)

**Comment by Jean-BaptisteC** [comment]
Yes it's fixed but now username disappear if refresh fails
How reproduce:
- Open app go to settings -> profile
- Connect you to OSM
- Allow access to internet
- Go back to main screen
- Go to profile settings and shut internet during refresh

**Comment by RedAuburn** [comment]
should have fixed it now, please retry again :)

**Comment by Jean-BaptisteC** [comment]
Now I have a crash

```
Process: app.organicmaps.beta, PID: 30975
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
at app.organicmaps.editor.OsmOAuth.getUsername(OsmOAuth.java:75)
at app.organicmaps.editor.ProfileFragment.lambda$refreshViews$5(ProfileFragment.java:99)
at app.organicmaps.editor.ProfileFragment.$r8$lambda$TMQlSeoDo6cAgiz40nO_4g-HevA(ProfileFragment.java:0)
at app.organicmaps.editor.ProfileFragment$$ExternalSyntheticLambda5.onResult(R8$$SyntheticClass:0)
at app.organicmaps.util.NetworkPolicy$Type$1.check(NetworkPolicy.java:30)
at app.organicmaps.util.NetworkPolicy.checkNetworkPolicy(NetworkPolicy.java:107)
at app.organicmaps.util.NetworkPolicy.checkNetworkPolicy(NetworkPolicy.java:113)
at app.organicmaps.editor.ProfileFragment.lambda$refreshViews$6(ProfileFragment.java:93)
at app.organicmaps.editor.ProfileFragment.$r8$lambda$rGS4TJIQNUD1FiydjIQ18SEk0Tk(ProfileFragment.java:0)
at app.organicmaps.editor.ProfileFragment$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by RedAuburn** [comment]
@Jean-BaptisteC how about now? it _should_ work now i think. Sorry for asking so much, I can't reproduce it myself :/

**Comment by Jean-BaptisteC** [comment]
Yes problem is fixed
Thanks for your patience
