### ISSUE TITLE
[android] Crash in the editor

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8738]
```
          Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8; index=-1
       at app.organicmaps.editor.StreetAdapter$StreetViewHolder.onClick(StreetAdapter.java:117)
       at android.view.View.performClick(View.java:7741)
       at android.view.View.performClickInternal(View.java:7711)
       at android.view.View.-$$Nest$mperformClickInternal()
       at android.view.View$PerformClick.run(View.java:30643)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8848)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.organicmaps.beta/issues/4a4ade1bc6bd8b97fbc93844de0d8d59?time=last-seven-days&types=crash&sessionEventKey=66961DCE01EF0001517E55CE33E6DFCB_1970577675937735304

**Comment by Jean-BaptisteC** [comment]
Able to reproduce, select two streets in the editor at the same time
