### ISSUE TITLE
Unable to run maps_generator on Mac

### ISSUE THREAD

**Issue by willcohen** [organicmaps/organicmaps#8756]
**Describe the issue**
When trying to add a new POI (camp_pitch), running the map generator tool to test fails on my M2 Mac.

**Steps to reproduce**
```
$ python -m maps_generator --countries="US_Massachusetts*" --skip="Coastline"                
Loading configuration from /Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/var/etc/map_generator.ini
[2024-07-24 11:53:24,680] INFO env Start setup ...
[2024-07-24 11:53:24,680] INFO env Check for the osmctools binaries...
[2024-07-24 11:53:24,680] INFO env Found osmctools at /Users/wcohen/programming/organicmaps/organicmaps/../osmctools/osmconvert, /Users/wcohen/programming/organicmaps/organicmaps/../osmctools/osmupdate, /Users/wcohen/programming/organicmaps/organicmaps/../osmctools/osmfilter
[2024-07-24 11:53:24,680] INFO env Check generator tool ...
[2024-07-24 11:53:24,693] INFO env Looking for generator tool in /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release ...
[2024-07-24 11:53:24,693] INFO env Generator tool found - /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool
[2024-07-24 11:53:24,693] INFO env Build name is 2024_07_24__11_53_24.
[2024-07-24 11:53:24,693] INFO env Build path is /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24.
[2024-07-24 11:53:24,693] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24 ...
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data ...
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/borders ...
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/draft ...
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/osm2ft ...
[2024-07-24 11:53:24,694] INFO env The following 5 maps will build: US_Massachusetts_Boston, US_Massachusetts_Central, US_Massachusetts_Plymouth, US_Massachusetts_West, US_Massachusetts_Southeastern.
[2024-07-24 11:53:24,694] INFO env Finish setup
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/logs ...
[2024-07-24 11:53:24,694] INFO stages Stage DownloadAndConvertPlanet: start ...
[2024-07-24 11:53:24,694] INFO env Create /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/status ...
[2024-07-24 11:53:24,700] INFO file Trying to download /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.osm.pbf from https://download.geofabrik.de/north-america/us/massachusetts-240722.osm.pbf.
[2024-07-24 11:53:24,700] INFO file Trying to download /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.osm.pbf.md5 from https://download.geofabrik.de/north-america/us/massachusetts-240722.osm.pbf.md5.
[2024-07-24 11:53:25,118] INFO file File /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.osm.pbf.md5 was downloaded from https://download.geofabrik.de/north-america/us/massachusetts-240722.osm.pbf.md5.
[2024-07-24 11:53:53,305] INFO file File /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.osm.pbf was downloaded from https://download.geofabrik.de/north-america/us/massachusetts-240722.osm.pbf.
[2024-07-24 11:53:58,051] INFO stages Stage DownloadAndConvertPlanet: finished in 0:00:33.356789
[2024-07-24 11:53:58,051] INFO stages Stage Preprocess: start ...
[2024-07-24 11:53:58,119] INFO gen_tool Run generator tool [generator_tool version 2024.07.24-1-8a4996d6-Darwin]: /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool --threads_count=1 --data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --intermediate_data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --cache_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m --node_storage=map --user_resource_path=/Users/wcohen/programming/organicmaps/organicmaps/data --preprocess=true 
[2024-07-24 11:54:06,131] INFO stages Stage Preprocess: finished in 0:00:08.078924
[2024-07-24 11:54:06,131] INFO stages Stage Features: start ...
[2024-07-24 11:54:06,131] INFO stages Test test_booking_data was skipped.
[2024-07-24 11:54:06,152] INFO gen_tool Run generator tool [generator_tool version 2024.07.24-1-8a4996d6-Darwin]: /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool --threads_count=8 --data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --intermediate_data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --cache_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m --node_storage=map --user_resource_path=/Users/wcohen/programming/organicmaps/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --addresses_path= --generate_packed_borders=true 
[2024-07-24 11:54:13,401] INFO stages Stage Features: finished in 0:00:07.269795
[2024-07-24 11:54:13,401] ERROR env Uncaught exception: The launch of /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool failed.
Arguments used: --threads_count=8 --data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --intermediate_data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --cache_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m --node_storage=map --user_resource_path=/Users/wcohen/programming/organicmaps/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --addresses_path= --generate_packed_borders=true
See details in /Users/wcohen/programming/organicmaps/maps_build/2024_07_24__11_53_24/logs/Features.log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/__main__.py", line 250, in <module>
    main()
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/__main__.py", line 246, in main
    generate_maps(env, from_stage)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/maps_generator.py", line 43, in generate_maps
    run_generation(env, stages, from_stage)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/maps_generator.py", line 24, in run_generation
    generation.run(from_stage)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/generation.py", line 79, in run
    self.run_stages()
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/generation.py", line 85, in run_stages
    stage(self.env)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 87, in __call__
    return self.apply(env, **self.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 199, in apply
    method(obj, env, *args, **kwargs)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 371, in apply
    method(obj, env, *args, **kwargs)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/stages.py", line 295, in apply
    method(obj, env, *args, **kwargs)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/stages_declaration.py", line 137, in apply
    steps.step_features(env, **extra)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/steps.py", line 119, in step_features
    run_gen_tool(
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 162, in run_gen_tool
    GenTool(*args, **kwargs).run()
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/gen_tool.py", line 138, in run
    wait_and_raise_if_fail(self)
  File "/Users/wcohen/programming/organicmaps/organicmaps/tools/python/maps_generator/generator/exceptions.py", line 43, in wait_and_raise_if_fail
    raise BadExitStatusError(msg)
maps_generator.generator.exceptions.BadExitStatusError: The launch of /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool failed.
Arguments used: --threads_count=8 --data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --intermediate_data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --cache_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m --node_storage=map --user_resource_path=/Users/wcohen/programming/organicmaps/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --addresses_path= --generate_packed_borders=true
See details in /Users/wcohen/programming/organicmaps/maps_build/2024_07_24__11_53_24/logs/Features.log
(organicmaps) ➜  python git:(camp_pitch) cat /Users/wcohen/programming/organicmaps/maps_build/2024_07_24__11_53_24/logs/Features.log
[2024-07-24 11:54:06,131] INFO stages Stage Features: start ...
[2024-07-24 11:54:06,131] INFO stages Test test_booking_data was skipped.
[2024-07-24 11:54:06,152] INFO gen_tool Run generator tool [generator_tool version 2024.07.24-1-8a4996d6-Darwin]: /Users/wcohen/programming/organicmaps/organicmaps/../omim-build-release/generator_tool --threads_count=8 --data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --intermediate_data_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --cache_path=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m --node_storage=map --user_resource_path=/Users/wcohen/programming/organicmaps/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --addresses_path= --generate_packed_borders=true 
I(1) 0.00000 generator/intermediate_data.cpp:188 MapFilePointStorageReader(): Nodes reading is started
I(1) 4.02869 generator/intermediate_data.cpp:205 MapFilePointStorageReader(): Nodes reading is finished
I(1) 4.02887 Offsets reading is started for file /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/ways.dat.offs
I(1) 4.09223 Offsets reading is finished
I(1) 4.09248 Offsets reading is started for file /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/relations.dat.offs
I(1) 4.09271 Offsets reading is finished
I(1) 4.09275 Offsets reading is started for file /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/nodes.dat.id2rel
I(1) 4.09362 Offsets reading is finished
I(1) 4.09368 Offsets reading is started for file /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/ways.dat.id2rel
I(1) 4.12635 Offsets reading is finished
I(1) 4.12658 Offsets reading is started for file /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/relations.dat.id2rel
I(1) 4.12662 Offsets reading is finished
I(1) 4.12665 generator/borders.cpp:192 LoadCountriesList(): Loading countries in borders/ folder in /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/
I(1) 4.13724 generator/borders.cpp:204 LoadCountriesList(): Countries loaded: 5
I(1) 4.85692 Reading OSM data from /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/planet.o5m
I(1) 4.96877 generator/raw_generator.cpp:59 Log(): Read 820224 elements [pos: 8.46863 MiB, avg read speed: 78.8733  MiB/s, read speed: 78.8733 MiB/s [n: 820218 , w: 0 , r: 0 ]]
I(1) 5.04908 generator/raw_generator.cpp:59 Log(): Read 1640448 elements [pos: 17.5095 MiB, avg read speed: 93.2959  MiB/s, read speed: 112.579 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 5.11342 generator/raw_generator.cpp:59 Log(): Read 2460672 elements [pos: 26.5503 MiB, avg read speed: 105.35  MiB/s, read speed: 140.511 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(2) 5.14531 generator/raw_generator_writer.cpp:61 Write(): Start writing to  /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/tmp/US_Massachusetts_Plymouth.mwm.tmp
I(2) 5.14578 generator/raw_generator_writer.cpp:61 Write(): Start writing to  /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/tmp/US_Massachusetts_Boston.mwm.tmp
I(2) 5.14590 generator/raw_generator_writer.cpp:61 Write(): Start writing to  /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/tmp/US_Massachusetts_Central.mwm.tmp
I(2) 5.14596 generator/raw_generator_writer.cpp:61 Write(): Start writing to  /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/tmp/US_Massachusetts_West.mwm.tmp
I(2) 5.14602 generator/raw_generator_writer.cpp:61 Write(): Start writing to  /Users/wcohen/programming/organicmaps/organicmaps/../maps_build/2024_07_24__11_53_24/intermediate_data/tmp/US_Massachusetts_Southeastern.mwm.tmp
W(3) 5.17254 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 257496069 Types: man_made-lighthouse
I(1) 5.21006 generator/raw_generator.cpp:59 Log(): Read 3280896 elements [pos: 34.79 MiB, avg read speed: 99.7836  MiB/s, read speed: 85.2662 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 5.26167 generator/raw_generator.cpp:59 Log(): Read 4101120 elements [pos: 42.9153 MiB, avg read speed: 107.216  MiB/s, read speed: 157.425 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 5.31532 generator/raw_generator.cpp:59 Log(): Read 4921344 elements [pos: 51.1551 MiB, avg read speed: 112.696  MiB/s, read speed: 153.582 MiB/s [n: 820224 , w: 0 , r: 0 ]]
W(4) 5.33288 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 358276254 Types: man_made-mast
W(5) 5.33996 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 358269018 Types: landuse-residential
W(6) 5.35787 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 358275170 Types: natural-beach-sand
W(7) 5.41082 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 433558275 Types: cuisine-argentinian
W(3) 5.42258 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985378 Types: aeroway-aerodrome
W(3) 5.42281 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985485 Types: aeroway-aerodrome
W(3) 5.42302 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985512 Types: aeroway-aerodrome
W(3) 5.42314 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985530 Types: aeroway-aerodrome
W(3) 5.42347 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985578 Types: aeroway-aerodrome
W(3) 5.42351 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985579 Types: aeroway-aerodrome
W(3) 5.42358 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985592 Types: aeroway-aerodrome
W(3) 5.42376 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985602 Types: aeroway-aerodrome
W(3) 5.42382 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 368985610 Types: aeroway-aerodrome
W(3) 5.42787 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 595944000 Types: landuse-industrial
W(8) 5.44411 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 846309936 Types: highway-bus_stop psurface-paved_good
W(9) 5.45806 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 947121506 Types: man_made-mast
I(1) 5.50747 generator/raw_generator.cpp:59 Log(): Read 5741568 elements [pos: 59.5665 MiB, avg read speed: 92.1984  MiB/s, read speed: 43.7753 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 5.57939 generator/raw_generator.cpp:59 Log(): Read 6561792 elements [pos: 68.1496 MiB, avg read speed: 94.9175  MiB/s, read speed: 119.344 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 5.64577 generator/raw_generator.cpp:59 Log(): Read 7382016 elements [pos: 76.7326 MiB, avg read speed: 97.8277  MiB/s, read speed: 129.306 MiB/s [n: 820224 , w: 0 , r: 0 ]]
W(7) 5.67985 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1042005531 Types: aeroway-aerodrome
W(7) 5.67992 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1042005645 Types: aeroway-aerodrome
W(7) 5.67997 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1042017329 Types: aeroway-aerodrome
W(7) 5.68002 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1042047811 Types: aeroway-aerodrome
W(9) 5.71455 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1399809852 Types: public_transport-platform highway-bus_stop wheelchair-yes
W(7) 5.77876 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1399777036 Types: public_transport-platform highway-bus_stop
W(10) 5.82134 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1399798442 Types: public_transport-platform highway-bus_stop
I(1) 5.87208 generator/raw_generator.cpp:59 Log(): Read 8202240 elements [pos: 85.4874 MiB, avg read speed: 84.5851  MiB/s, read speed: 38.6861 MiB/s [n: 820224 , w: 0 , r: 0 ]]
W(7) 5.91803 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1602700481 Types: cuisine-regional
W(8) 5.93939 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 1721313320 Types: man_made-mast
I(1) 6.01186 generator/raw_generator.cpp:59 Log(): Read 9022464 elements [pos: 92.2394 MiB, avg read speed: 80.1767  MiB/s, read speed: 48.3029 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.07456 generator/raw_generator.cpp:59 Log(): Read 9842688 elements [pos: 98.877 MiB, avg read speed: 81.5043  MiB/s, read speed: 105.865 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.12054 generator/raw_generator.cpp:59 Log(): Read 10662912 elements [pos: 105.114 MiB, avg read speed: 83.481  MiB/s, read speed: 135.626 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.17248 generator/raw_generator.cpp:59 Log(): Read 11483136 elements [pos: 111.351 MiB, avg read speed: 84.9322  MiB/s, read speed: 120.126 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.22884 generator/raw_generator.cpp:59 Log(): Read 12303360 elements [pos: 117.588 MiB, avg read speed: 85.9918  MiB/s, read speed: 110.633 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.28383 generator/raw_generator.cpp:59 Log(): Read 13123584 elements [pos: 123.825 MiB, avg read speed: 87.0528  MiB/s, read speed: 113.441 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.34223 generator/raw_generator.cpp:59 Log(): Read 13943808 elements [pos: 130.062 MiB, avg read speed: 87.8308  MiB/s, read speed: 106.777 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.38664 generator/raw_generator.cpp:59 Log(): Read 14764032 elements [pos: 136.299 MiB, avg read speed: 89.3628  MiB/s, read speed: 140.45 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.42479 generator/raw_generator.cpp:59 Log(): Read 15584256 elements [pos: 142.536 MiB, avg read speed: 91.1713  MiB/s, read speed: 163.464 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.46228 generator/raw_generator.cpp:59 Log(): Read 16404480 elements [pos: 148.773 MiB, avg read speed: 92.9323  MiB/s, read speed: 166.37 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.54387 generator/raw_generator.cpp:59 Log(): Read 17224704 elements [pos: 154.953 MiB, avg read speed: 92.099  MiB/s, read speed: 75.7478 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.59826 generator/raw_generator.cpp:59 Log(): Read 18044928 elements [pos: 161.19 MiB, avg read speed: 92.8056  MiB/s, read speed: 114.662 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.64104 generator/raw_generator.cpp:59 Log(): Read 18865152 elements [pos: 167.427 MiB, avg read speed: 94.0801  MiB/s, read speed: 145.836 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.68902 generator/raw_generator.cpp:59 Log(): Read 19685376 elements [pos: 173.664 MiB, avg read speed: 95.0227  MiB/s, read speed: 129.985 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.73442 generator/raw_generator.cpp:59 Log(): Read 20505600 elements [pos: 179.901 MiB, avg read speed: 96.0488  MiB/s, read speed: 137.346 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.78029 generator/raw_generator.cpp:59 Log(): Read 21325824 elements [pos: 186.195 MiB, avg read speed: 97.033  MiB/s, read speed: 137.221 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.85009 generator/raw_generator.cpp:59 Log(): Read 22146048 elements [pos: 192.432 MiB, avg read speed: 96.7636  MiB/s, read speed: 89.3559 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.91315 generator/raw_generator.cpp:59 Log(): Read 22966272 elements [pos: 198.669 MiB, avg read speed: 96.8301  MiB/s, read speed: 98.9282 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 6.96734 generator/raw_generator.cpp:59 Log(): Read 23786496 elements [pos: 204.906 MiB, avg read speed: 97.3008  MiB/s, read speed: 115.126 MiB/s [n: 820224 , w: 0 , r: 0 ]]
I(1) 7.02208 generator/raw_generator.cpp:59 Log(): Read 24606720 elements [pos: 211.143 MiB, avg read speed: 97.7207  MiB/s, read speed: 113.863 MiB/s [n: 820224 , w: 0 , r: 0 ]]
W(6) 7.03556 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 2295360232 Types: cuisine-italian
W(5) 7.04139 generator/osm2type.cpp:1500 GetNameAndType(): Have house number for _non-address_: Osm Node 2350127254 Types: cuisine-pizza
W(3) 7.04514 generator/osm2type.cpp:1497 GetNameAndType(): Exceeded types count for: Osm Node 2411563915 Types: 12 amenity-cafe cuisine-american cuisine-burger cuisine-chicken cuisine-coffee_shop cuisine-greek cuisine-international cuisine-italian cuisine-pizza cuisine-sandwich cuisine-vegan cuisine-vegetarian
I(1) 7.10351 generator/raw_generator.cpp:59 Log(): Read 25426944 elements [pos: 217.781 MiB, avg read speed: 97.1324  MiB/s, read speed: 81.5223 MiB/s [n: 820224 , w: 0 , r: 0 ]]
 0# generator::ErrorHandler(int) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 2# feature::IsUsefulType(unsigned int) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 3# ftype::GetNameAndType(OsmElement*, FeatureBuilderParams&, std::__1::function<bool (unsigned int)> const&, std::__1::function<std::__1::optional<m2::Point<double>> (OsmElement const*)> const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 4# generator::FeatureMaker::ParseParams(FeatureBuilderParams&, OsmElement&) const in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 5# generator::FeatureMakerBase::Add(OsmElement&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 6# generator::Translator::Emit(OsmElement const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 7# generator::TranslatorCollection::Emit(OsmElement const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 8# threads::FunctionWrapper::ImplType<std::__1::__bind<generator::TranslatorsPool::Emit(std::__1::vector<OsmElement, std::__1::allocator<OsmElement>>&&)::$_73>>::Call() in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 9# base::ComputationalThreadPool::Worker() in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
10# void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (base::ComputationalThreadPool::*)(), base::ComputationalThreadPool*>>(void*) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
11# _pthread_start in /usr/lib/system/libsystem_pthread.dylib
 0# generator::ErrorHandler(int) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 2# pthread_kill in /usr/lib/system/libsystem_pthread.dylib
 3# raise in /usr/lib/system/libsystem_c.dylib
 4# generator::ErrorHandler(int) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 5# _sigtramp in /usr/lib/system/libsystem_platform.dylib
 6# feature::IsUsefulType(unsigned int) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 7# ftype::GetNameAndType(OsmElement*, FeatureBuilderParams&, std::__1::function<bool (unsigned int)> const&, std::__1::function<std::__1::optional<m2::Point<double>> (OsmElement const*)> const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 8# generator::FeatureMaker::ParseParams(FeatureBuilderParams&, OsmElement&) const in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
 9# generator::FeatureMakerBase::Add(OsmElement&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
10# generator::Translator::Emit(OsmElement const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
11# generator::TranslatorCollection::Emit(OsmElement const&) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
12# threads::FunctionWrapper::ImplType<std::__1::__bind<generator::TranslatorsPool::Emit(std::__1::vector<OsmElement, std::__1::allocator<OsmElement>>&&)::$_73>>::Call() in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
13# base::ComputationalThreadPool::Worker() in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
14# void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (base::ComputationalThreadPool::*)(), base::ComputationalThreadPool*>>(void*) in /Users/wcohen/programming/organicmaps/omim-build-release/generator_tool
15# _pthread_start in /usr/lib/system/libsystem_pthread.dylib
[2024-07-24 11:54:13,401] INFO stages Stage Features: finished in 0:00:07.269795
```

**Expected behaviour**
Generate a new .mwm for Massachusetts.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Sonoma 14.5.
 - Organic Maps version: HEAD (at time of bug, 2f8f9de)
 - Device Model: MacBook Air M2.

**Comment by willcohen** [comment]
The PR leading me to run into this problem is #8757, which I have been unable to test locally.

**Comment by biodranik** [comment]
Looks like the new type/its drules weren't properly added into the classificator.

**Comment by willcohen** [comment]
Thank you. Will dig further!

**Comment by pastk** [comment]
Is it an issue still?

**Comment by willcohen** [comment]
I have to assume this was a configuration issue for me. Thanks!
