### ISSUE TITLE
[android] AndroidRuntimeException: FORWARD_RESULT_FLAG used while also requesting a result

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#8984]
```
Fatal Exception: android.util.AndroidRuntimeException: FORWARD_RESULT_FLAG used while also requesting a result
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2250)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
at android.app.Activity.startActivityForResult(Activity.java:5717)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:239)
at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:173)
at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
at app.organicmaps.SplashActivity.processNavigation(SplashActivity.java:188)
at app.organicmaps.MwmApplication.nativeProcessTask(MwmApplication.java)
at app.organicmaps.MwmApplication.lambda$forwardToMainThread$0(MwmApplication.java:280)
at android.os.Handler.handleCallback(Handler.java:1000)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loopOnce(Looper.java:242)
at android.os.Looper.loop(Looper.java:362)
at android.app.ActivityThread.main(ActivityThread.java:8393)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
```

Version:Android 12,13,14
App version:2024.08.15-16-Google-beta (24081516)

**Comment by biodranik** [comment]
Was there a way to reproduce it?
