### ISSUE TITLE
Sharing location to Organic Maps leads to crash

### ISSUE THREAD

**Issue by soshial** [organicmaps/organicmaps#9048]
**Describe the issue**
Sharing location to Organic Maps leads to crash

**Steps to reproduce**
1. Go to [Fossify Gallery App](https://f-droid.org/en/packages/org.fossify.gallery/) and open any photo with location in EXIF
2. Click on "Settings (the dots icon)" and then "Show on map"
3. Crash
<img width="1135" alt="Screenshot 2024-08-22 at 09 10 00" src="https://github.com/user-attachments/assets/173d99fa-facf-41d2-8994-825bb635bc86">

```kotlin
fun openLocation(exif....) {
    val latLon = FloatArray(2)
    if (exif.getLatLong(latLon)) {
        showLocationOnMap("${latLon[0]}, ${latLon[1]}")
    } else {
        toast(R.string.unknown_location)
    }
}

fun Activity.showLocationOnMap(coordinates: String) {
    val uriBegin = "geo:${coordinates.replace(" ", "")}"
    val encodedQuery = Uri.encode(coordinates)
    val uriString = "$uriBegin?q=$encodedQuery&z=16"
    val intent = Intent(Intent.ACTION_VIEW, Uri.parse(uriString))
    launchActivityIntent(intent)
}
```

**Expected behaviour**
No crash.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: [Android 14]
 - Organic Maps version: 2024.08.15-21-FDroid
 - Device Model: Samsung S22

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by biodranik** [comment]
@soshial what is Simple Gallery app, and how exactly are you opening OM from it? Do you have a crash callstack?

**Comment by RicoElectrico** [comment]
> what is Simple Gallery app

https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro (and https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery non-pro version)

**Comment by soshial** [comment]
I added a link to the app, @biodranik

**Comment by soshial** [comment]
At the moment, I cannot reproduce the crash even though it reproduced each time 3 days ago. I assure you, I am not crazy :)

**Comment by biodranik** [comment]
Are you testing the master branch?

**Comment by soshial** [comment]
I was testing the latest F-Droid build at the moment.

**Comment by shtrophic** [comment]
This also happens with https://github.com/MM2-0/Kvaesitso. However, to reproduce, a little configuration is required - you need to go into the settings and enable location search. Then, in the search bar, search for some nearby location or location category, for example "restaurant", and tap on "online results". This will bring up a location search result. Tapping on the OSM map or opening the item (the box icon with the arrow pointing up right) will crash Organicmaps. The stacktrace is:

```
type: crash
osVersion: google/cheetah/cheetah:15/BP1A.250505.005.B1/2025062000:user/release-keys
flags: dev options enabled
package: app.organicmaps:25061203, targetSdk 36
process: app.organicmaps
processUptime: 902 + 358 ms
installer: app.accrescent.client

java.lang.RuntimeException: Unable to resume activity {app.organicmaps/app.organicmaps.MwmActivity}: java.lang.IllegalStateException: Can't change activity type once set: { mBounds=Rect(0, 0 - 1440, 3120) mAppBounds=Rect(0, 0 - 1440, 3120) mMaxBounds=Rect(0, 0 - 1440, 3120) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mActivityType=home mAlwaysOnTop=undefined mRotation=ROTATION_0} activityType=standard
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5501)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5534)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:73)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:169)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:101)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2782)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8973)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Can't change activity type once set: { mBounds=Rect(0, 0 - 1440, 3120) mAppBounds=Rect(0, 0 - 1440, 3120) mMaxBounds=Rect(0, 0 - 1440, 3120) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mActivityType=home mAlwaysOnTop=undefined mRotation=ROTATION_0} activityType=standard
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3278)
	at android.os.Parcel.createException(Parcel.java:3254)
	at android.os.Parcel.readException(Parcel.java:3230)
	at android.os.Parcel.readException(Parcel.java:3172)
	at android.app.IUiModeManager$Stub$Proxy.setApplicationNightMode(IUiModeManager.java:905)
	at android.app.UiModeManager.setApplicationNightMode(UiModeManager.java:918)
	at app.organicmaps.util.ThemeSwitcher$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at app.organicmaps.util.ThemeSwitcher.setThemeAndMapStyle(ThemeSwitcher.java:112)
	at app.organicmaps.util.ThemeSwitcher.-$$Nest$msetThemeAndMapStyle(ThemeSwitcher.java:0)
	at app.organicmaps.util.ThemeSwitcher$1.run(ThemeSwitcher.java:52)
	at app.organicmaps.util.ThemeSwitcher.restart(ThemeSwitcher.java:81)
	at app.organicmaps.MwmActivity.onResume(MwmActivity.java:1108)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1737)
	at android.app.Activity.performResume(Activity.java:9292)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5491)
	... 16 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.WindowConfiguration.setActivityType(WindowConfiguration.java:419)
	at android.app.WindowConfiguration.setTo(WindowConfiguration.java:435)
	at android.content.res.Configuration.setTo(Configuration.java:1120)
	at com.android.server.wm.ConfigurationContainer.applyAppSpecificConfig(ConfigurationContainer.java:673)
	at com.android.server.wm.PackageConfigurationUpdaterImpl.updateConfig(PackageConfigurationUpdaterImpl.java:127)

```

**Comment by biodranik** [comment]
@soshial was your issue already fixed? https://github.com/organicmaps/organicmaps/issues/8984 looks related.

@shtrophic you have a different type of crash, please make a separate issue with a video on how to reproduce it. The crash log shows some theme switching-related context, e.g. `setApplicationNightMode()` call.

**Comment by shtrophic** [comment]
Sorry for the delay. I've written up an issue with repro-instructions: #10978

**Comment by biodranik** [comment]
@shtrophic thanks!

@soshial I've checked your issue in the Android 14 and 16 emulators, and could not reproduce it with a debug build of Organic Maps. Please reopen the issue again if it reproduces for you.
