### ISSUE TITLE
[android] Crash upon entering a bookmarks list

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#9522]
OM crashes when a user taps on the My Places list (to see its contents).
```
10-15 14:07:48.865 E/AndroidRuntime(17408): FATAL EXCEPTION: main
10-15 14:07:48.865 E/AndroidRuntime(17408): Process: app.organicmaps, PID: 17408
10-15 14:07:48.865 E/AndroidRuntime(17408): java.lang.ArrayIndexOutOfBoundsException: length=27; index=30
10-15 14:07:48.865 E/AndroidRuntime(17408): 	at app.organicmaps.bookmarks.data.Icon.getResId(Icon.java:241)
10-15 14:07:48.865 E/AndroidRuntime(17408): 	at app.organicmaps.bookmarks.Holders$BookmarkViewHolder.bind(Holders.java:374)
10-15 14:07:48.865 E/AndroidRuntime(17408): 	at app.organicmaps.bookmarks.BookmarkListAdapter.onBindViewHolder(BookmarkListAdapter.java:462)
10-15 14:07:48.865 E/AndroidRuntime(17408): 	at app.organicmaps.bookmarks.BookmarkListAdapter.onBindViewHolder(BookmarkListAdapter.java:27)
```

**Comment by pastk** [comment]
Out of bounds crash here:
```
  @DrawableRes
  public int getResId()
  {
    return TYPE_ICONS[mType];
  }
```

```
  private static final int[] TYPE_ICONS = { R.drawable.ic_bookmark_none,
                                            R.drawable.ic_bookmark_hotel,
                                            R.drawable.ic_bookmark_animals,
                                            R.drawable.ic_bookmark_buddhism,
                                            R.drawable.ic_bookmark_building,
                                            R.drawable.ic_bookmark_christianity,
                                            R.drawable.ic_bookmark_entertainment,
                                            R.drawable.ic_bookmark_money,
                                            R.drawable.ic_bookmark_food,
                                            R.drawable.ic_bookmark_gas,
                                            R.drawable.ic_bookmark_judaism,
                                            R.drawable.ic_bookmark_medicine,
                                            R.drawable.ic_bookmark_mountain,
                                            R.drawable.ic_bookmark_museum,
                                            R.drawable.ic_bookmark_islam,
                                            R.drawable.ic_bookmark_park,
                                            R.drawable.ic_bookmark_parking,
                                            R.drawable.ic_bookmark_shop,
                                            R.drawable.ic_bookmark_sights,
                                            R.drawable.ic_bookmark_swim,
                                            R.drawable.ic_bookmark_water,
                                            R.drawable.ic_bookmark_bar,
                                            R.drawable.ic_bookmark_transport,
                                            R.drawable.ic_bookmark_viewpoint,
                                            R.drawable.ic_bookmark_sport,
                                            R.drawable.ic_bookmark_start,
                                            R.drawable.ic_bookmark_finish };
```

Its likely caused by #9287 / #9448 as they changed the hardcoded list of possible bookmark icons e.g. https://github.com/organicmaps/organicmaps/pull/9448/files#diff-92a2f7100da6ccaa76e9803ca32575115fdae69b04d7a8fdd91ec63036c17ec4

**Comment by pastk** [comment]
FYI @dvdmrtnz @AndrewShkrob @vng

**Comment by pastk** [comment]
The sample kmz file is imported just fine but the list is crashing upon trying to enter it.

The only bookmark that causes the crash has
```
<mwm:icon>Stadium</mwm:icon>
```
which was added recently and is absent in Icon.java.

Once its deleted the crash is gone.

**Comment by pastk** [comment]
For easy reproduction:
add a bookmark to any newly added BM icon category POI, e.g. a cafe, stadium, bank, pharmacy...
Then try to open the list containing it.

**Comment by pastk** [comment]
And maybe a related bug - when importing a GPX all newly imported bookmarks appear with a generic ("dot") icon.

**Comment by vng** [comment]
@pastk Please more details about the "dot" icon.

**Comment by pastk** [comment]
All poi-specific bookmark icons (i.e. cafe, pharmacy, etc inside a pin) become generic (a big dot inside a pin).

**Comment by pastk** [comment]
Did anyone check if iOS is affected?

**Comment by pastk** [comment]
> All poi-specific bookmark icons (i.e. cafe, pharmacy, etc inside a pin) become generic (a big dot inside a pin).

Actually there is no icon info in the generated gpx, only name and latlon. So I guess this is by design or a gpx limitation.

**Comment by vng** [comment]
iOS is ok.
