### ISSUE TITLE
Android 5 crash on complex Place Page.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#9624]
Crash when selecting some POI with a complex PP.
Moto G 1st Gen (XT1032) running on Android 5.1

```
11-08 23:28:22.727 E/AndroidRuntime(21900): FATAL EXCEPTION: main
11-08 23:28:22.727 E/AndroidRuntime(21900): Process: app.organicmaps, PID: 21900
11-08 23:28:22.727 E/AndroidRuntime(21900): android.view.InflateException: Binary XML file line #25: Error inflating class TextView
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at app.organicmaps.widget.placepage.sections.PlacePhoneAdapter.onCreateViewHolder(PlacePhoneAdapter.java:47)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at app.organicmaps.widget.placepage.sections.PlacePhoneAdapter.onCreateViewHolder(PlacePhoneAdapter.java:19)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4022)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1941)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:650)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.view.View.measure(View.java:17565)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(BottomSheetBehavior.java:515)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
11-08 23:28:22.727 E/AndroidRuntime(21900): 	at android.vie
```

**Comment by batterydotac** [comment]
I also had this same crash and associated stack trace on an LG G Pad 8.3 (VK810) running Android 5.0.2.  Using a process of elimination by removing lines in the affected file "android/app/src/main/res/layout/place_page_phone_item.xml", I found that this line:

`    android:textDirection="firstStrongLtr"`

...Was causing the crash for any Place Page that included a phone number.  This was committed on September 24, 2024 (836ce51).  Changing it to the following solved the issue (or removing the line completely, of course):

`    android:textDirection="ltr"`

In all left-to-right and right-to-left languages, [phone] numbers are still read left-to-right.  So I hope this doesn't cause any regressions, but I'm not sure what the commit was intending to solve - perhaps text included along with a phone number?  I don't see any other occurrences of "firstStrongLtr" in the codebase.  I've tried bringing up PPs in RTL countries after the change, but phone numbers are difficult to find, and the ones I do see look reasonable.

This unfortunately wasn't the end of complex PP crashes on Android 5.  After making a comparison to Android 15, I saw that any subtitle which included icons was problematic and instantly caused the Java VM to abort.  I was seeing a very similar message to what's shown in this thread:

[https://issuetracker.google.com/issues/37013126](https://issuetracker.google.com/issues/37013126)

Studying the problem further, I came across these instructions:

[https://developer.android.com/training/articles/perf-jni](https://developer.android.com/training/articles/perf-jni)

Essentially, C-style UTF-8 strings need to be converted to a format that Java can use (UTF-16, in the end).  Java also employs what's called "Modified UTF-8" as an intermediary, which is not directly compatible with UTF-8 but is fairly similar.  The instructions specify the following about a quarter of the way down the page:

> Data passed to NewStringUTF must be in Modified UTF-8 format. A common mistake is reading character data from a file or network stream and handing it to NewStringUTF without filtering it. Unless you know the data is valid MUTF-8 (or 7-bit ASCII, which is a compatible subset), you need to strip out invalid characters or convert them to proper Modified UTF-8 form. If you don't, the UTF-16 conversion is likely to provide unexpected results. CheckJNI—which is on by default for emulators—scans strings and aborts the VM if it receives invalid input.

Descriptions of the formats of UTF-8 and MUTF-8 follow:

[https://www.johndcook.com/blog/2019/09/09/how-utf-8-works/](https://www.johndcook.com/blog/2019/09/09/how-utf-8-works/)
[https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html](https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html)

The error report in the crash said that 0xF0 isn't a valid sequence-starting character in MUTF-8, which is true as can be seen from the Oracle link above (it's also a wholly invalid byte value as well).  So what was happening was that any inline icon such as a WiFi symbol or bank card with a UTF-8 codepoint of 0x10000 or above ("supplementary characters") would include a four-byte sequence with the very top four bits high, causing the VM to abort.  What needs to be done of course is to convert these four-byte sequences to six-byte sequences instead; two- and three-byte sequences can be left as-is since they are encoded identically between the two variants.  (In Marshmellow and after this is done automatically, but it was only added as a convenience and was never really a bug as can be seen by the documentation.)  This is my code in "android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp" to expand/repair the affected function which previously just called "NewStringUTF" directly:

`jstring ToJavaString(JNIEnv * env, char const * s)
{
  int i=0, j=0, len=strlen(s);
  char *conv=new char[(((int) (len*3))>>1)+1];

  while(i<len) {
    if((s[i]&0xF8)==0xF0) {
      if((i+4)>len) break;
      conv[j++]=0xED;
      conv[j++]=0xA0|((((s[i]&0x07)<<2)|((s[i+1]&0x30)>>4))-1);
      conv[j++]=0x80|((s[i+1]&0x0F)<<2)|((s[i+2]&0x30)>>4);
      conv[j++]=0xED;
      conv[j++]=0xB0|(s[i+2]&0x0F);
      conv[j++]=s[i+3];
      i+=4;
    } else {
      conv[j++]=s[i++];
    }
  }

  conv[j]=0x00;
  jstring value=env->NewStringUTF(conv);
  delete[] conv;
  return value;
}`

After making this change, everything seems to work marvelously.  I can't cause any crashes by opening PPs after trying quite a fair number of them, and they all seem to display correctly.  The bathroom icons are now coming through properly and I'm even getting elevation values which I don't remember seeing before.  I've very lightly tested the change on Android 15 but more confirmation is needed; it might be preferred to just enable this code for API 21&22 but I wasn't sure how to do that.  Thanks to the clear build instructions I was able to create an fdroidRelease APK which I'm now using.

It's wonderful to have a mapping application like this on Android 5 because the choices are pretty slim otherwise.  Most have advertisements, and the new Mapquest - which I otherwise like - crashes immediately on startup.  So I hope these suggestions can be helpful to those with older hardware.

**Comment by batterydotac** [comment]
Thanks, Alexander, for your prompt reply.  I've never made a PR as I mainly program in assembly language as well as Qt3/4/5 non-collaboratively, and I find the whole Git system to be a little confusing honestly.  So I'd prefer if those with more expertise than I handle that part.  Regarding point 1, I think should we get the opinion of @vng since he made the original commit, possibly to fix something that perhaps we're not aware of.  Removing the line altogether would be best if it isn't necessary (this is the way it was a year ago).

I agree on point 2 and I've tried to accommodate your great suggestions.  The "ToJavaString" function therefore should be left alone, and we should add the following function right below it in "android/app/src/main/cpp/app/organicmaps/core/jni_helper.cpp":

```
jstring ToJavaStringWithSuppChar(JNIEnv * env, char const * s)
{
  int i=0, j=0, len_in=0, len_out=0;

  // Note: Only truncated input strings are detected; corrupt input bytes not
  //        compliant to UTF-8 will still result in a corrupt output or error;
  //        however, uncorrupted MUTF-8 can be processed without any problems.

  // Scan the original string to check for any supplementary characters
  while(s[len_in]!=0x00) {
    // Test the top five bits of this byte to detect a four-byte sequence marker
    if((s[len_in]&0xF8)==0xF0) {
      // Add two additional output bytes per four-byte sequence marker
      len_out+=2;
    }
    // Advance to the next input and output byte
    len_in++; len_out++;
  }

  // If the length had not increased, there were no supplementary characters
  if(len_in==len_out) return env->NewStringUTF(s);

  // Allocate space for an expanded conversion string
  char *conv=new char[len_out+1];

  // Loop over the input string and again detect four-byte sequence markers
  while(i<len_in) {
    if((s[i]&0xF8)==0xF0) {
      // A truncated input string will abort the four-to-six-byte conversion
      if((i+4)>len_in) break;
      // Convert the UTF-8 four-byte sequence to an MUTF-8 six-byte sequence
      conv[j++]=0xED;
      conv[j++]=0xA0|((((s[i]&0x07)<<2)|((s[i+1]&0x30)>>4))-1);
      conv[j++]=0x80|((s[i+1]&0x0F)<<2)|((s[i+2]&0x30)>>4);
      conv[j++]=0xED;
      conv[j++]=0xB0|(s[i+2]&0x0F);
      conv[j++]=s[i+3];
      // Skip past four input bytes
      i+=4;
    } else {
      // Directly copy any other bytes
      conv[j++]=s[i++];
    }
  }

  // Always null-terminate the conversion string at its conclusion
  conv[j]=0x00;

  // Find the Java string, delete the allocated conversion string, and return
  jstring result=env->NewStringUTF(conv);
  delete[] conv;
  return result;
}
```

Furthermore, in "android/app/src/main/cpp/app/organicmaps/core/jni_helper.hpp", these lines should be added which mirror those of the original function, for better or for worse:

```
jstring ToJavaStringWithSuppChar(JNIEnv * env, char const * s);
inline jstring ToJavaStringWithSuppChar(JNIEnv * env, std::string const & s)
{
  return ToJavaStringWithSuppChar(env, s.c_str());
}
inline jstring ToJavaStringWithSuppChar(JNIEnv * env, std::string_view sv)
{
  /// @todo Make conversion without a temporary some day.
  return ToJavaStringWithSuppChar(env, std::string(sv).c_str());
}
```

I considered the function name somewhat carefully.  I think "ToJavaStringFromModifiedUTF8" isn't preferable because it implies that the input could already be in MUTF-8, which it isn't (despite being supported as a pass-through).  The issue isn't solely related to emoji and icons, as some obscure languages may have characters in the higher space.  Also, to the contrary, some icons aren't in the higher space, such as the wheelchair which appears frequently.  So I decided on "ToJavaStringWithSuppChar" as I feel this is the most technically accurate description.  But other suggestions are of course welcome.

The only two places that I'm currently aware of that need to call this new function are lines 79 and 123 of "android/app/src/main/cpp/app/organicmaps/UserMarkHelper.cpp" where the subtitle is set for a POI.  These changes should be straightforward and are both:

`  jni::TScopedLocalRef jSubtitle(env, jni::ToJavaStringWithSuppChar(env, info.GetSubtitle()));`

It took a while to figure out why bookmarking a location would show a corrupt toilet icon (not sure why it didn't abort), but the fix was easy, as described above (line 123).  I'm a little worried that I'm missing something (see #9656) as I've only been using OM for under a week, though, so further checks would be helpful here.  Hopefully Viktor still has his XT1032 to this end.

As an aside, I noticed some slightly odd behavior with certain POIs, such as the toilet at GPS point 42.735086/-84.482443.  If it isn't bookmarked, it shows a subtitle of only the toilet icon.  However, if it is, it shows "My Places - Toilet - Icon".  So I'm getting an extra "Toilet" wording in there which I would probably prefer to have in the unbookmarked state, e.g. "Toilet - Icon".  I don't know enough about the code to understand why this is being added, and/or why it isn't there to begin with.  I'm also seeing similar behavior with the bicycle parking at 42.732507/-84.477951.  If it isn't bookmarked, the subtitle is hidden, but otherwise it's "My Places - Bicycle Parking".  Additionally with the bench at 42.731644/-84.476867 and the dumpster at 42.731084/-84.477146, the "issue" appears.  I didn't see any other reports of this directly, but perhaps #2168 is relevant somehow.  I wanted to check that this isn't intended before posting a new report, but I can do that if you think I should.  Overall it seems pretty minor, though.

Ideally the "ToJavaStringWithSuppChar" function would be tested along with a Java instance by probably converting the string back to UTF-8 at the end and possibly displaying it somehow, but I haven't a clue how to do that.  So I just made a simple demonstration program (why can't I attach C files?):

https://pastebin.com/d3TRVunU

> (note that, depending on the use case, the function signature may also accept a non-constant string reference, to avoid unnecessary allocation and to allow modifications in-place)

I don't think we can do in-place modifications too easily since the length potentially increases, and it would have to be processed all in reverse.  Hopefully how I have it now is pretty efficient.  Also, by the way, the fix is only for Android 5 as 6 has it taken care of internally (or so I see reported).

My current struggle is trying to add EV charging stations as a category, which has only been partially successful.  I can't get the skin generator to run which I thought would be straightforward, and I'm having another problem with amenity detection - is this something you'd be able to assist with via a Q&A discussion?

**Comment by biodranik** [comment]
Thanks for the code and pointing out the lines. I'll think about how to better integrate the remaining fix.

Btw, did you see this [commit](https://cs.android.com/android/_/android/platform/art/+/edc005e396947fb4fa681c4a0be7beba66354239)?

There are other interesting comments in [this discussion](https://stackoverflow.com/questions/77805633/is-modified-utf-8-handling-in-jninewstringutf-changed-in-recent-android-versio) that say the fix is also needed for Android 6. Did you test the issue on 6 (e.g. in simulator)?

> I noticed some slightly odd behavior with certain POIs, such as the toilet at GPS point 42.735086/-84.482443. If it isn't bookmarked, it shows a subtitle of only the toilet icon. However, if it is, it shows "My Places - Toilet - Icon". So I'm getting an extra "Toilet" wording in there which I would probably prefer to have in the unbookmarked state, e.g. "Toilet - Icon". I don't know enough about the code to understand why this is being added, and/or why it isn't there to begin with. I'm also seeing similar behavior with the bicycle parking at 42.732507/-84.477951. If it isn't bookmarked, the subtitle is hidden, but otherwise it's "My Places - Bicycle Parking". Additionally with the bench at 42.731644/-84.476867 and the dumpster at 42.731084/-84.477146, the "issue" appears.

This is a designed behavior (although it may look inconsistent, agree):
- When a POI is without a name, its type is displayed in the title, and is not displayed in the subtitle.
- When a bookmark is created, it has an editable, customizable name (equal to title/type of POI in such cases by default). To see a bookmark's title, we show it in the subtitle.

Please check my profile at GitHub and get in touch in Telegram/other messenger or Matrix, skin generator and adding new types should work. Did you check other similar merged PRs where new types were added?

**Comment by batterydotac** [comment]
> Thanks for the code and pointing out the lines. I'll think about how to better integrate the remaining fix.

Looking forward to see what you come up with.

> Btw, did you see this [commit](https://cs.android.com/android/_/android/platform/art/+/edc005e396947fb4fa681c4a0be7beba66354239)?

Not specifically, no.  But I looked it over a bit now.  How do you tell which Android version it was for (sorry, pretty new to all of this)?  It seems late, in 2021.

> There are other interesting comments in [this discussion](https://stackoverflow.com/questions/77805633/is-modified-utf-8-handling-in-jninewstringutf-changed-in-recent-android-versio) that say the fix is also needed for Android 6. Did you test the issue on 6 (e.g. in simulator)?

I haven't tested it, no, and my Galaxy S6 Edge running Android 7 doesn't want to install OM from the Play Store - not sure what that's about.  My emulator in Android Studio also doesn't seem to work correctly.  I was just duplicating what I saw in the last post here:

[https://issuetracker.google.com/issues/37013126](https://issuetracker.google.com/issues/37013126)

> > I noticed some slightly odd behavior with certain POIs, such as the toilet at GPS point 42.735086/-84.482443. If it isn't bookmarked, it shows a subtitle of only the toilet icon. However, if it is, it shows "My Places - Toilet - Icon". So I'm getting an extra "Toilet" wording in there which I would probably prefer to have in the unbookmarked state, e.g. "Toilet - Icon". I don't know enough about the code to understand why this is being added, and/or why it isn't there to begin with. I'm also seeing similar behavior with the bicycle parking at 42.732507/-84.477951. If it isn't bookmarked, the subtitle is hidden, but otherwise it's "My Places - Bicycle Parking". Additionally with the bench at 42.731644/-84.476867 and the dumpster at 42.731084/-84.477146, the "issue" appears.
> 
> This is a designed behavior (although it may look inconsistent, agree):
> 
> * When a POI is without a name, its type is displayed in the title, and is not displayed in the subtitle.
> * When a bookmark is created, it has an editable, customizable name (equal to title/type of POI in such cases by default). To see a bookmark's title, we show it in the subtitle.

Makes sense, thanks.  As long as there's some logic behind it.  It's nice to be able to customize bookmark names.

> Please check my profile at GitHub and get in touch in Telegram/other messenger or Matrix, skin generator and adding new types should work. Did you check other similar merged PRs where new types were added?

I'll reach out via E-mail if that's okay.  I didn't see any assistive comments on Github for what I'm facing.
