### ISSUE TITLE
Loses location after some time in nav mode

### ISSUE THREAD

**Issue by mrghosti3** [organicmaps/organicmaps#994]
After walking while in nav mode, my location pointer gets stuck in one places and is unable to update location, only the direction stays accurate. Have to manually exit nav mode, wait for my location to reset and then go to nav mode again. Mostly this happens after I switch apps or lock phone for a moment while walking.

I'm using stock android 9 on Xiaomi Mi A1. FDroid version app.

Don't know if this is a duplicate issue, but couldn't find anything similar here.

**Comment by biodranik** [comment]
Thanks! It would be great if you or someone else help with the exact steps to reproduce, and/or enable logs recording in the settings and send us the log after reproducing the issue via Help -> Feedback.

**Comment by mrghosti3** [comment]
I will enable logging and go walk to reproduce this error when I'll be travelling today.

**Comment by mrghosti3** [comment]
I went for a test walk and this time it worked without a problem. It would find actual location after some time instead of being stuck in the same place of last known location. I checked the logs and found nothing unusual except for 2 exceptions in the snippet below.

```
2021-08-03 22:42:44.537 main: D/LocationHelper: Stopped in background
2021-08-03 22:42:44.540 main: D/LocationHelper: stop()
2021-08-03 22:42:44.541 main: D/LocationHelper: removeListener(), listener: LocationHelper.mCoreLocationListener
2021-08-03 22:42:44.542 main: D/LocationHelper:  - listener count was: 2
2021-08-03 22:42:44.543 main: D/LocationHelper: stopInternal()
2021-08-03 22:42:44.544 main: D/AndroidNativeProvider: Android native provider is stopped
2021-08-03 22:42:44.545 main: D/BaseLocationProvider: setActive active = false
2021-08-04 04:43:48.272 main: D/LocationHelper: addListener(): com.mapswithme.maps.widget.placepage.RichPlacePageController@66236a7, forceUpdate: false
2021-08-04 04:43:48.273 main: D/LocationHelper:  - listener count was: 0
2021-08-04 04:43:49.278 main: D/LocationHelper: attach() callback = com.mapswithme.maps.MwmActivity@eaf6038
2021-08-04 04:43:49.318 main: D/LocationHelper: restart()
2021-08-04 04:43:49.318 main: D/LocationHelper: stopInternal()
2021-08-04 04:43:49.319 main: D/AndroidNativeProvider: Android native provider is stopped
2021-08-04 04:43:49.319 main: D/BaseLocationProvider: setActive active = false
2021-08-04 04:43:49.319 main: D/LocationHelper: addListener(): LocationHelper.mCoreLocationListener, forceUpdate: true
2021-08-04 04:43:49.319 main: D/LocationHelper:  - listener count was: 1
2021-08-04 04:43:49.320 main: D/LocationHelper: notifyLocationUpdated(), listener: LocationHelper.mCoreLocationListener
2021-08-04 04:43:49.320 main: D/LocationHelper: No saved location - skip
2021-08-04 04:43:49.320 main: I/LocationUtils: Available location providers: passive
2021-08-04 04:43:49.321 main: D/LocationHelper: notifyLocationError(): 2
2021-08-04 04:43:49.321 main: D/LocationHelper: onLocationError errorCode = 2
java.lang.Throwable
	at com.mapswithme.maps.location.LocationHelper$1.onLocationError(LocationHelper.java:1)
	at com.mapswithme.maps.location.LocationHelper.notifyLocationError(LocationHelper.java:3)
	at com.mapswithme.maps.location.LocationHelper.start(LocationHelper.java:9)
	at com.mapswithme.maps.location.LocationHelper.restart(LocationHelper.java:5)
	at com.mapswithme.maps.location.LocationHelper.attach(LocationHelper.java:14)
	at com.mapswithme.maps.MwmActivity.onRenderingCreated(MwmActivity.java:2)
	at com.mapswithme.maps.MapFragment.surfaceCreated(MapFragment.java:26)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:751)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

2021-08-04 04:43:49.321 main: D/LocationHelper: nativeOnLocationError errorCode = 2, current state = PENDING_POSITION
2021-08-04 04:43:49.461 main: D/LocationHelper: notifyMyPositionModeChanged(): PENDING_POSITION
2021-08-04 04:43:49.462 main: D/LocationHelper: onMyPositionModeChanged mode = PENDING_POSITION
2021-08-04 04:43:49.463 main: D/LocationHelper: Resumed in foreground
2021-08-04 04:43:49.464 main: D/LocationHelper: addListener(): LocationHelper.mCoreLocationListener, forceUpdate: true
2021-08-04 04:43:49.465 main: D/LocationHelper:  - listener count was: 2
2021-08-04 04:43:49.465 main: D/LocationHelper: notifyLocationUpdated(), listener: LocationHelper.mCoreLocationListener
2021-08-04 04:43:49.466 main: D/LocationHelper: No saved location - skip
2021-08-04 04:43:49.467 main: I/LocationUtils: Available location providers: passive
2021-08-04 04:43:49.468 main: D/LocationHelper: notifyLocationError(): 2
2021-08-04 04:43:49.468 main: D/LocationHelper: onLocationError errorCode = 2
java.lang.Throwable
	at com.mapswithme.maps.location.LocationHelper$1.onLocationError(LocationHelper.java:1)
	at com.mapswithme.maps.location.LocationHelper.notifyLocationError(LocationHelper.java:3)
	at com.mapswithme.maps.location.LocationHelper.start(LocationHelper.java:9)
	at com.mapswithme.maps.location.LocationHelper.onTransit(LocationHelper.java:5)
	at com.mapswithme.maps.background.AppBackgroundTracker.notifyTransitionListeners(AppBackgroundTracker.java:2)
	at com.mapswithme.maps.background.AppBackgroundTracker.access$200(AppBackgroundTracker.java:1)
	at com.mapswithme.maps.background.AppBackgroundTracker$1.run(AppBackgroundTracker.java:12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

2021-08-04 04:43:49.469 main: D/LocationHelper: nativeOnLocationError errorCode = 2, current state = PENDING_POSITION
2021-08-04 04:43:54.398 main: D/LocationHelper: detach(), delayed: true
```

**Comment by biodranik** [comment]
Thanks! @vng @rtsisyk The most concerning line here is `I/LocationUtils: Available location providers: passive`

> The passive location provider will provide you with location data when other apps that have requested location updates get their data. So if no other app on the phone is getting location updates, you won't get them either.

Why the current implementation doesn't get an active provider/GPS update?

**Comment by mrghosti3** [comment]
On while walking, I tested out whether the app would lose the gps and get stuck in trying to find it. I did that multiple times.

**Comment by rtsisyk** [comment]
On Wed, Aug 4, 2021 at 10:37 AM Alexander Borsuk ***@***.***>
wrote:

> Thanks! @vng <https://github.com/vng> @rtsisyk
> <https://github.com/rtsisyk> The most concerning line here is I/LocationUtils:
> Available location providers: passive
>
> The passive location provider will provide you with location data when
> other apps that have requested location updates get their data. So if no
> other app on the phone is getting location updates, you won't get them
> either.
>
> Why the current implementation doesn't get an active provider/GPS update?
>

A good question. I have no idea.

**Comment by mrghosti3** [comment]
Maybe "find my device" feature could have something to do in this case?

**Comment by mrghosti3** [comment]
The issue somehow doesn't surface anymore so might as well consider it resolved for now.
